### ISSUE TITLE
Update HD wallet path to separate main / test net

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#1010]
Currently the HD wallet path is hardcoded, and both main and test nets are sharing the same path. 

It is recommended that we use a different path (coin type part) for the testnet. 

Proposed change:
- Mainnet path uses `4343` as it is now
- Testnet path uses `1`
- Add a handler to set the correct path for different networktype

**Comment by cryptoBeliever** [comment]
HD derivation path is now changed. Clear warning about backuping private keys must be announced.
