### ISSUE TITLE
should not mix testnet and mainnet wallets in the same profile. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1013]
I wanted to import some private keys into the wallet and see what they looked like on the mainnet. I made a profile and selected "mainnet". I used a seed and my first x amount of child accounts created from the seed all started with "N". Then I went to create private key accounts added to the profile. In doing so, the addresses started with a "T".

Below is the screenshot of a "T" account and an "N" account in the same profile. 

![image](https://user-images.githubusercontent.com/10395907/106640438-6de43100-655c-11eb-8194-378cf88a8635.png)
![image](https://user-images.githubusercontent.com/10395907/106640462-776d9900-655c-11eb-9ef6-8eff161ded91.png)

**Comment by jabo38** [comment]
Basically, when somebody creates a profile, ideally all other accounts whether from the seed or private key should stay on that same network.

**Comment by cryptoBeliever** [comment]
may be related to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1010

**Comment by cryptoBeliever** [comment]
It's fixed now. Accounts mainnet/testnet are not mixed in one profile.
