### ISSUE TITLE
The Cosign Aggregate Bonded Modal displays wrong information for a couple of seconds

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1034]
![image](https://user-images.githubusercontent.com/33131259/106889047-20003200-66f0-11eb-85c3-7c06e2ab02b1.png)
![image](https://user-images.githubusercontent.com/33131259/106889055-2393b900-66f0-11eb-8a67-e0bdd854a173.png)

**Comment by cryptoBeliever** [comment]
Fixed.
