### ISSUE TITLE
FIXED. No defaults should be used for network configuration

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1046]
Currently there are network configuration defaults defined which are used in case the data could not be retrieved from the node (defaultNetworkConfig.networkConfigurationDefaults in NetworkConfig.ts). In that case, values that are calculated with one of those are displayed but probably wrong because the default values most likely differ from the correct values. But the user cannot know those values are not correct because they seem plausible.

I suggest not to use default values for any data that is normally retrieved from the network but instead show something like "N/A" where such data is needed.

I'm not sure if it's actually in use but CustomValidationRules depends only on the default values with a todo note to use the real values. Such issues need to be resolved before we can remove the defaults.

**Comment by coiki** [comment]
Seems like this issue was fixed on #1113

**Comment by bassemmagdy** [comment]
fixed
