### ISSUE TITLE
Wrong message when importing seed

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1058]
Steps:

1. Open desktop wallet
2. Copy mnemonic from paper wallet
3. Import an account with mnemonic

There is message "Successfully generated a random mnemonic passphrase" but the user is importing it not generating.

![image](https://user-images.githubusercontent.com/17684281/107073122-3a690700-67e7-11eb-998b-9fdd120aef25.png)

**Comment by myxmaster** [comment]
fixed with #1069

**Comment by cryptoBeliever** [comment]
Fixed.
