### ISSUE TITLE
Overlapping text under "Invoice"

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1061]
Overlapping text ( Fee 0.005 symbol.xym, 0 symbol.xym ) under "Invoice" 
(linux version 0.14.0 - http://desktop-build.symboldev.com/#/invoice)

---

![overlapping_text](https://user-images.githubusercontent.com/46584115/107120069-ad2bbe00-688b-11eb-86fd-1b8a949a68f9.png)

**Comment by cryptoBeliever** [comment]
Fixed.
