### ISSUE TITLE
Messages under "Invoice" and "Send" are not displayed correctly and cannot be edited

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1062]
longer message entered under Invoice is not visible and cannot be edited.

---

![Text](https://user-images.githubusercontent.com/46584115/107120566-a5214d80-688e-11eb-8641-52680696fc3b.png)

---------------------------------------------------------------------------------
---------------------------------------------------------------------------------

A message without spaces (e.g. a series of numbers) is not completely visible in the upper message area. For better illustration I have entered text without spaces.

---

![Text2](https://user-images.githubusercontent.com/46584115/107120587-bd916800-688e-11eb-9c2a-a18850331e09.png)

**Comment by cryptoBeliever** [comment]
@garm01 I'm unable to reproduce. Which one OS and wallet version? 

Video: https://share.getcloudapp.com/o0uEER4P

**Comment by garm01** [comment]
To test it, in the first example, I also used the Enter key when entering text. The text is then moved without this being visible in the message field.
With the arrow keys you can scroll up and down. But this is not so optimal. The same effect is sometimes seen with Copy & Past of a text.
I am sorry, I should have described this better.

**Comment by garm01** [comment]
Under "Transfers" , a longer message disappear without the message being made visible with the existing scroll bar.
You can only see it here because the fees are rising.

---

![send](https://user-images.githubusercontent.com/46584115/107878135-e76f0e00-6ed0-11eb-83cc-605ed31ef229.png)

---

![send2](https://user-images.githubusercontent.com/46584115/107878138-ec33c200-6ed0-11eb-9ddc-2b28956107c4.png)

**Comment by cryptoBeliever** [comment]
@garm01 could you check? Not sure if it's fixed.

**Comment by garm01** [comment]
At "http://desktop-build.symboldev.com", there is no change yet.

You have the possibility to enter 98 characters.
From 99 characters on, an empty field with a scroll bar appears.
By moving the scroll bar, the message can no longer be made visible.
So there is no possibility to edit the message at the beginning without deleting the whole rest (backspace key) before (e.g. for error correction).
If you press enter after the 98 characters, the message is no longer visible and neither is the scroll bar.
The only possibility are the up and down keys. If a user unintentionally pressed enter while entering text (under "Send"), the text disappeared. Under "Sign transaction(s)" the message appears, but this will surely lead to many errors. 
Under "Invoice" you can see the message, but the behavior of the message field is the same as under "Send".
Furthermore, the line break under "Invoice" doesn't seem to work properly either. If you enter additional characters after 98 characters, they are simply placed in the middle of the message.

**Comment by garm01** [comment]
**correction:** 
"Furthermore, the line break under "Invoice" doesn't seem to work properly either. If you enter additional characters after 98 characters, they are simply placed in the middle of the message." 

This happens only if you click in the message box after 99 characters.
