### ISSUE TITLE
Wrong amount presented on dashboard

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1064]
Steps:

1. Create a mosaic with divisibility 0 and amount 500 000 000
2. Sent transaction with amount 100 000 000 to other address.
3. On dashboard correct amount is presented (100 000 000) 
4. Send next transaction with amount 400 000 000

Result: After confirmation amount is presented as 100 and 400.

Additional question: Amount column is used for XYM and other mosaics. This may be confusing. Maybe we should mark someow that this amount is not XYM but other mosaic?

Video regarding bug:

https://share.getcloudapp.com/5zuA1gwG

**Comment by OlegMakarenko** [comment]
In the block explorer and mobile wallet we display amount only for native currency. If the transfer transaction contains non-native mosaic or message we display icons of it

**Comment by rg911** [comment]
> In the block explorer and mobile wallet we display amount only for native currency. If the transfer transaction contains non-native mosaic or message we display icons of it

@cryptoBeliever @OlegMakarenko  Not sure I understood why wallet wouldn't show the amount. The root cause of the issue afaik is when the none native coin balance dropped to zero, the divisibility is used the default xym's.  It looks to be a bug. The custom-created mosaic should be preserved and show the correct amount in the transaction history.

**Comment by OlegMakarenko** [comment]
@rg911 not regarding a bug

> Additional question: Amount column is used for XYM and other mosaics. This may be confusing. Maybe we should mark someow that this amount is not XYM but other mosaic?

We are about the amount field in the transaction list. I think there are two ways: display amounts only for native mosaic or display amounts for all transferred mosaics [{mosaicName, amount}]. The second one may overload the list view.

The transaction details definitely should display all transferred mosaics with amounts.

**Comment by cryptoBeliever** [comment]
Also related to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1090

**Comment by bassemmagdy** [comment]
@cryptoBeliever not reproducible

**Comment by cryptoBeliever** [comment]
I'm not able reproduce it now too.
