### ISSUE TITLE
Lite UI Feature Request

### ISSUE THREAD

**Issue by evias** [nemgrouplimited/symbol-desktop-wallet#107]
This feature request will be discussed in upcoming #sig-client discussions. It is hereby proposed to provide with a **lite UI** (lighter / less overwhelming).

1. Compact - Like calculator or Electrum wallet, so I don't have to fill the entire screen to run it, and I'm not overwhelmed with info I don't need. This may even help alleviate the color problem, as filling an entire screen with that much purple is overwhelming. - Yet the NEM wallet pro managed to use purple well. 
2. Easy access to Send & Receive
3. Easy access to QR code - maybe even display on main wallet page
4. Ability to search transactions (EG: to pull all the transaction history from a specific address)
5. Ability to scroll through transaction history, instead of tabbing
6. Add something like a 1-click "refresh node", so beginners can just click it, and it auto tries a different node.

**Comment by evias** [comment]
Next #sig-client call planned for July 22nd, 2020 - 13:00 GMT+2

**Comment by yilmazbahadir** [comment]
I believe, this issue is not relevant anymore. Please feel free to create another one with up to date definition.
