### ISSUE TITLE
After using the "Back" button under "Finish", the wallet creation cannot be completed.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1071]
When creating a new wallet, the "Back" button displays the option to go back one step.(v0.14.0)

1) Create Profile
2) Import Mnemonic
3) Select some Accounts and go to Finish
4) push the "Back" Button at the "Finish" Page

Afterwards, the user has no possibility to go one step forward again, but has to start from the beginning.

**Comment by cryptoBeliever** [comment]
Fixed.
