### ISSUE TITLE
You can use the "Settings" page for node management or to configure a new network

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1076]
The link should point directly to "Network settings" and not first to "General settings", the user only wants to change network settings here.

![settings](https://user-images.githubusercontent.com/46584115/107277269-71902000-6a54-11eb-8b24-66b11e48d73e.png)

**Comment by cryptoBeliever** [comment]
Not fixed. Still when I'm click "Settings" in node selection I go to:
![image](https://user-images.githubusercontent.com/17684281/115459205-14b89f00-a227-11eb-8ca0-6790d81f5186.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever could you re-check the latest updates?

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
