### ISSUE TITLE
Request to display delegated harvesting request more clearly

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1081]
One thing that the mobile app does a little better than the desktop app is when there is a delegated harvesting request tx, it more clear says "delegated harvesting request".  

But in the desktop wallet as seen in the screenshot below, it is shown as a message tx. That could be confusing to most casual users. The went to set up delegated harvesting and instead of seeing a delegated harvesting tx, instead they see an strange message. 

This was also clearly indicated in NIS1 when it is a delegated harvesting tx so the community will be used to that. I know..... I get it, how Symbol does things is different, but the majority of users won't get that. 

![image](https://user-images.githubusercontent.com/10395907/107294853-9c727800-6a44-11eb-9656-e3c93cbea423.png)

**Comment by cryptoBeliever** [comment]
Looks ok on branch gh1081-display-delegated-harvesting-message

**Comment by cryptoBeliever** [comment]
Done in integration branch.
