### ISSUE TITLE
Uniform format of the Chain height

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1082]
The Chain height display should be valid in a uniform format for the entire wallet. The Chain height always displayed without a comma even outside the wallet. (v0.14.0 linux)

---

![Chain_height2](https://user-images.githubusercontent.com/46584115/107345349-c0c16980-6ac3-11eb-9197-d34eace586c4.png)

**Comment by garm01** [comment]
And here should be only "90554", without "Block #".

---

![Chain_height4](https://user-images.githubusercontent.com/46584115/107350624-f5382400-6ac9-11eb-9c04-be729aecae01.png)

**Comment by cryptoBeliever** [comment]
@myxmaster @OlegMakarenko  if you have time :)

**Comment by myxmaster** [comment]
Well, with 30 s blocktime we have more than 1 million blocks per year. Should we really have no thousands separator?

**Comment by garm01** [comment]
I am not sure, but I guess that most users use Copy & Paste.
If you then enter this e.g. in the search of the explorer you first get an error message.
I think we should trust in a uniform format here.

It looks different in this case #502 .

**Comment by garm01** [comment]
I just saw Copy & Paste is not possible in the Dashboard. It always pops up the pop-up "Details about a transaction".
Mmmmhhh ..., is that the way it should be?
But this does not change the fact that we need, in my opinion, a uniform format.

**Comment by myxmaster** [comment]
Ok you are right, I removed the thousands separator and the "Block #" part.

I didn't look at the csv export yet though.
