### ISSUE TITLE
Ledger connection issue on MacOS

### ISSUE THREAD

**Issue by TriPhan96** [nemgrouplimited/symbol-desktop-wallet#1084]
**[Only happen on MacOS]** 
When Ledger devices are connecting with another app (for example [Ledger Live](https://www.ledger.com/ledger-live)) can't connect with the wallet (Electron build or release only) and show error as this picture 

![image](https://user-images.githubusercontent.com/62920562/107359760-a90bd480-6b07-11eb-8b61-ec048261c38e.png)

**Comment by cryptoBeliever** [comment]
Unfortunately, I'm unable to check. @rg911 if you have some time (just joked) you can verify.

**Comment by cryptoBeliever** [comment]
I have confirmation from people on Mac that it worked and the message was presented.
