### ISSUE TITLE
Aggregate Form. Add Mosaic Supply Change to the Mosaic Transaction 

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1088]
![image](https://user-images.githubusercontent.com/33131259/107407026-ce9ddb80-6b11-11eb-952b-6c74ffe5e342.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko related with https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/723

**Comment by bassemmagdy** [comment]
@OlegMakarenko @cryptoBeliever we added mosaic supply transaction as a separate type of transactions in aggregate.
