### ISSUE TITLE
After a mosaic is created with a single Mosaic Definition transaction it is not presented on the mosaics list

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1089]

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I mentioned it here: https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/723
There is the proposition of two solutions (add supply to aggregate with mosaic or/and fix issue with presentation).
Please increase priority if you think P3 is too low.
