### ISSUE TITLE
Unify the notation of key link transaction.

### ISSUE THREAD

**Issue by tomotomo9696** [nemgrouplimited/symbol-desktop-wallet#1092]
In the language file, the three Key link transactions are inconsistent in their notation.
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/e1336ef24e949f14d4eb70068a0fbe6b2e022fc8/src/language/en-US.json#L930
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/e1336ef24e949f14d4eb70068a0fbe6b2e022fc8/src/language/en-US.json#L942
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/e1336ef24e949f14d4eb70068a0fbe6b2e022fc8/src/language/en-US.json#L944

I think they should be unified to "Link ~ key" or "~ Key Link".

This problem is also true for the Japanese translation.

**Comment by segfaultxavi** [comment]
Throughout the documentation they are referred to as "~ Key Link":
https://docs.symbolplatform.com/serialization/coresystem

**Comment by cryptoBeliever** [comment]
@rg911 just wonder how translations will be handled?

**Comment by rg911** [comment]
yeah, we need to review all the translation tbh,

**Comment by rg911** [comment]
`Link node key` should be `node key Link`,

**Comment by segfaultxavi** [comment]
`Node Key Link` has already been changed in the `integration` branch in commit https://github.com/nemgrouplimited/symbol-desktop-wallet/commit/cb953b360a8918f8e06809fdced3daaf15d3e948

**Comment by cryptoBeliever** [comment]
@segfaultxavi that's correct.
Because as @rg911 told transactions will be reviewed I'm closing this issue.
@tomotomo9696 if you like you can do pull request with fix for Japanese translation.
