### ISSUE TITLE
Mosaic supply amount shows no fractional part. 

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#1100]
![image](https://user-images.githubusercontent.com/4384931/107620978-779d2100-6c4d-11eb-876d-34205202f290.png)

**Comment by cryptoBeliever** [comment]
For Polish/Russian locale I got NaN

![image](https://user-images.githubusercontent.com/17684281/108260163-44352780-7162-11eb-9487-5d135c7ad55d.png)

**Comment by cryptoBeliever** [comment]
Fixed.
