### ISSUE TITLE
Terms & Privacy policy verification

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1104]
In wallet we have terms and privacy policy:

![image (1)](https://user-images.githubusercontent.com/17684281/107706061-08ace000-6cc0-11eb-8515-b24fafbaa38b.png)
![image (2)](https://user-images.githubusercontent.com/17684281/107706084-11051b00-6cc0-11eb-8eb5-5196e04d5715.png)

@Pow1404  for verification:

1) If those are up-to-date.
2) Maybe both regulations should be outside wallet (easier to edit) and wallet should only link to them? (can be separate improvement issue)

**Comment by surekabpm** [comment]
The terms and conditions are tagged outside the wallet when you are in the process of creating a profile , this issue is tested and can be closed 
![image](https://user-images.githubusercontent.com/49143210/114493316-f7d50800-9c37-11eb-92d4-0df03fa17f7a.png)
