### ISSUE TITLE
The node connected to the wallet is not displayed in the delegation destination when setting the delegation harvest

### ISSUE THREAD

**Issue by dusanjp** [nemgrouplimited/symbol-desktop-wallet#1106]
in v0.14.0
The node connected to the wallet is not displayed in the delegation destination when setting the delegation harvest

in this case
You can find the desired delegation destination peer node and reconnect to it to find the target delegation destination.

I think it is desirable to be able to display the wallet connection node as the delegation destination without changing the wallet connection node.

**Comment by cryptoBeliever** [comment]
@bassemmagdy I think it's because /node/peers for the current node don't return it. I think it should be improved and we should add the current node if it meets the harvesting nodes list requirements.

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
@bassemmagdy this was fixed but doesn't work again...

**Comment by cryptoBeliever** [comment]
INFO: Remember to check if the current node is a peer node.

**Comment by cryptoBeliever** [comment]
Fixed on branch gh1106-fix

**Comment by cryptoBeliever** [comment]
@bassemmagdy 

branch: sprint-fixes

1. I added node 162.55.86.156
2. Switched to harvesting view
3. Check harvesting node list 

Result: 162.55.86.156 is not visible on the list
Expected result: 162.55.86.156 is visible on the list

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
