### ISSUE TITLE
the "Profile Import" area should already have the correct width before selecting an address 

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1110]
When creating a new wallet, the width for "Profile import" and "Address to interact with" should not move when selecting the first address.

- Select the address, the width of the "Profile import" area will be increased.
- Deselect address again, area will be reduced in width

Even if no address has been selected yet, an appropriate width should already be specified.
There is already an empty area reserved for "Profile Import" and the widening is annoying, although the difference is not that big.

---

![profile2](https://user-images.githubusercontent.com/46584115/107791206-f1b7cd80-6d53-11eb-8b69-af70bacd4695.png)

**Comment by cryptoBeliever** [comment]
Video: https://share.getcloudapp.com/WnuBBqL4

**Comment by cryptoBeliever** [comment]
Fixed.
