### ISSUE TITLE
Account metadata transaction is not signable

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1112]
Aggregate transaction looks the same for the initiator and target account

![image](https://user-images.githubusercontent.com/33131259/107798011-3ea3a000-6d64-11eb-8239-270828305c4f.png)

![image](https://user-images.githubusercontent.com/33131259/107797724-f1273300-6d63-11eb-808d-b1d977ee15bc.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko it's metadata, not restriction.

Video: https://share.getcloudapp.com/p9u88XWw

**Comment by cryptoBeliever** [comment]
@rg911 somehow I'm again able to reproduce ...
https://share.getcloudapp.com/Jru1xq9Z
