### ISSUE TITLE
when click on "Learn more about Symbol Optin" I get an error

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1114]
![image](https://user-images.githubusercontent.com/10395907/107837879-a5c35380-6d68-11eb-9571-22acc909d823.png)
  
Then I get this error. 

![image](https://user-images.githubusercontent.com/10395907/107837888-b4116f80-6d68-11eb-83ff-55ded74047a4.png)

I'm using a Ledger on 2.5.0

-----BEGIN REPORT-----
eyJtZXNzYWdlIjoiYzJiNDhhZjdkNTFhY2Y3MjBmM2Y1OWYxZGZlY2YxMDEw
NDA2ZmYxNmExMWZlNDdkZmQ0ZDZjZDkyNGRiODk2ZGM3ZGQwM2E1MGJjNGYz
NTA0NzU3YTA0ZGQ2NDg4YjczNzhmMDBmMmQ0NGI1MzE2MGZhOGE1NzE1YjNh
MGU1ZDQ4MDc2Y2U0YzFlYjhhZDk5NGIzNTZhYWU0Yzk0MjkxY2U5NWQ0YmZk
NTliZTFhZDc2NjhjY2ZlNWJjMzMzNWFiZDg0NDQ5NGMwNDllMjUxODhlY2I1
MjdiNzZiYzdiNGJhYjMzNWY0ZjkzMDY1M2RiZjMzOTFhNDE4YjcyM2JlZjcw
Y2ZkOWVmZmRkMmY0OWY0NDkxY2U5NWRlNjhjODJhN2E1MWQ0YzAxNWFhNzQ3
MzAwNGY1NGJlMzFhZGQ2ODIxMDIxOTlhNWI1ODhiMzBjMzc0YWQ3ZDVhMGU4
M2JiOGFiZWE2ODE2NzhlMTM3YjZlMGI2ZjM5ZmNlZGZjNjRjMjkzNTAxNTlm
ODgyMDliNWRmNGYyZjYzYzQyMmJjMTI4NzJmMGFmNGZjNjAxM2Q1NDdjN2I5
YTQ0M2JhYjdkMmYwOGY3ZjIxMzc4NjI5NDJiZjgxOTQyNzgxOGE4ZDE2ZGJi
MWMxMTViYTc2M2YyNGJjYWM5MWQyZTAyZjk1ZjY4OTQzNmE4MzYyMDBiN2Fm
NzMxOTg0MDJjN2FjNTJmYWMwMmIyZGNmM2M2ZTQzNjlhMWRhOGQ5ZGI4NTBl
NDQyMDBiYTRiNTAzNjhkODI4ZWI4MWYyOWMwMTA5N2VhNTdlYWNjMzcwZmZi
OThjNGRjZWY3YzM3ZTUzYjE4OGZkOGJjZWY5OTVjYWEyNGQxZTBmZjNjZDUz
ZThkMTg5ODMzYjY5ZWZkMmRmZTIzMmRlZTZmNjcyOGEyMTNiMmQ0MjRmNTky
ODU3YmM1OTIwNDMwMGFjYjM0ZmIzMDI3OWUwMWU3YmYzOGJiNWFiMjNmY2Qz
ZWRhODAyYjg5YzYzM2FlZTNjMGZhZGVlODFiZTNhZmFhYjk4ODAzMjE1MTVi
YTcwOTJmZTU4ZjM5NDgzN2Q2MTUwMjg5MDM2YmE1MjE0MzZiZDZiMGJjZjE0
ODZmMTk3NzgwYzI3YTQwZjRlMjFjMDZlYTNiNjQyNmRlYmU2MDMzN2M0OTc2
MDFiOWI1ZGZkNDJhZDBhNDQxMzdkMjA0ZGE0ZTFlNDdiOGVhZDI2ZGJmOWE0
MzUyM2JkZmJjNGU5ZDE0YmFjZjY5ZTZhNDNiYTQxMTBjMmQzMWJmMzY5YTg3
Mjc2YWViMDg0OWQ5ZjkzZTA2NmRmZjU5ZTFjNjk1N2NhODJjYzQ5MWM0NWQ3
M2MzMTJmYzY0NjNmMGUwNGYzMDQ0MjY0NGFiMThjYTlkMTZiODI2MTA2MjVh
ZGI5NjExNjA1YjFkZmJlNDVhYzM1ZTg2OTZjNDA5ODdjZjI0ZjkzZmQ3MjQx
OTMzYzYyMWRjMThlNGZlNWU5Y2U3NjdlZDA5YjU4OGU5OWZlYzk3Y2FlZTJi
NzE5NWI1YmYyMTE4OTE4NWE5NTQxMzBlZGI3NTk5YmQyNjQ3NTNlMzE4OGZh
NjgwNjBlMjg4YTIxMGE0YmMzMzExN2IwMzE1YTdkZTZmMGQ3NWEyYmEyZDEy
N2U0MGMzZWI5ZDE4ZWZkZmYxNGE3MTU2NmZmZTc4ZDEzOTg5ZDY3N2IzYzUw
MzM4MGNkMjBhYTVkNzI1ZmJlZDNiNmUxYjI3OTAzNzc0MjQ3ZWRiZTVhOThi
MTA0MzJjMTFhNDdhZWI5M2NiNzMxOWZhMzA1ODg4ZjQ2OWJmYTk2YWRhZDUw
ZjdhZTQ5MThjYjVmNjdmNmQ4ODU3M2M3MDc1ZWE1NGZlZjY5NDg1Mzg2NTJj
ZDIxNmE4OTJlZjNlMzczOTI4NWRiMTA3ZjQ0MzVkODY5NTA4NDAwNDA3NjA5
NTdkMTBkMmNlMjY1MDYzZTVlMjVlZTUxZTJhNWIwNTNkMTMyODczZjI2YmU5
NGJkZjNjYWIyODVhOTAyYzJkZTE4NmUxZGQwZGNjMWM4MWU2Y2NmZGRjYjg2
YzBiMWVkNzc4MzRjMDMxZTk3NzBkZGQzODU1MmQ2YzE3MWEwM2E0MjU3MDQz
MTg3NTE2NDUzZTE5ZDUxODhmN2UwZGYyODhlZWYzNGFlMzIwNjM1NWQ3MmNk
YmI1YjRjZTQwODlmMzJhNjA2OTVmNzY1YmRjNDk1MDEzODAzODVhN2FiMWRm
Y2YzZTVjNGJkZGQ0NzQ5OWMwZjU5ZmE3OWM2YjI4ZDM4ZDhlNjczNWUwZjk0
ZmEyNzEyYjliMzIzNTA0NzUxZDI0ZGQ5ODlmODEwNTRkZjYyZTIxZmQ4MWEy
MDdiNTc4NTYwNDQ4MGVhZDVhYzY2ZmIzOTM3ZGRmZjg2YjFmNzQ3Y2IyZTkz
YzlkZWNhMzQ4YWQwOWNmNzIzNjE1YmQ1NTNjZjM2NGZiNDljOGNlYWJmZDBh
ZDBhNmNmYTIwNTRmMjNkYjIzZjIyOTg1ZGIyZmNkYWU2NmNhYTRhMWIzIiwi
c2lnbmF0dXJlIjoiN2Q1N2EyNWViOWZhZGFiMzVmMmMyNWIwNjllZTgwMzU3
N2ZhNDAyNjhkNWVmYmFhZDlkZTBhYWY4ODE1YmRlODUyZGE3ODE1MTljOTVm
MzgzNjRlOTQ0MTg1OThhOTg0OWNkMmY4ZGRjMDlhZmIxYTg4ZDIxYjUxYzcw
Mjc2MWFiNWNhZGVlY2JkODIxNDQ5M2Y0MTZlNGU1MjNjYmJjMTk1NWU3OTdi
NDg1MzYzYTQyMGYwODViNWEwOTEwYTAzNTNmYWE5ZmMwZDJiOWE2MDk3Yjkw
ZmMwYmM5ZjZlNTU4NTExMWU1YjlkZmY1YzFlMzVlMjM0M2Q4ZjA5MGEwMDAy
YWVmZGM4ZDExYjllNmZiOWI1NzFiNTI5M2JkOGNhOWYzNTUxY2QzMTkwY2Jk
ODIwYzYzZjNjNzQyMzIyZGQwYWI3YzhiY2Q5Nzc2ZjYzNjIxNDJiZTBkNzgz
YmI0M2I4NWY3MDcxNWYzYmQ5NjQzYTJiOWNlZDZiNzE3MTg2ZTgzY2ZjOWZk
YzhhM2Q0ZWI1NzhhZDZhNTAwY2Y5MTUwN2E1ZmRiNDc5NmI0ZGExOWJmZmJk
ZGE3YTBiYjdiM2QwZDlmODg0NmY4MmQ4NzQ0MjIxODA5NDdlNTQyZjk5N2I2
MmU5OTRiNDE3NGE3NjljNDRiZWJkN2ZlNTJjMmEifQ==
-----END REPORT-----

**Comment by cryptoBeliever** [comment]
@jabo38 
1) It's not Symbol desktop wallet
2) This links opens a webpage https://nemplatform.com/symbol-migration. Looks like your IP is blocked by page (maybe you are using VPN or sth). You can check directly in other browser.

Closing as not related with Symbol wallet.
