### ISSUE TITLE
Harvesting node list - UX suggesting that it's possible put custom node.

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1115]
Currently, the harvesting node list doesn't allow put a custom node.
UX is not clear that input should be used only for searching. I would improve that.

![image](https://user-images.githubusercontent.com/17684281/107849081-08fcc680-6df9-11eb-917a-421ba7e5e4df.png)

**Comment by cryptoBeliever** [comment]
Related with https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1116

**Comment by surekabpm** [comment]
Tested and can be closed
