### ISSUE TITLE
Harvesting - vrf and remote account private keys shared between profiles

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1117]
Steps:

1. Create a profile with password X
2. Send more than 10000 XYM and start harvesting
3. Create a second profile with a password Y
4. Import private key of harvesting account from profile X

Result: On harvesting page we have "Show private key" for VRF and Remote but of course they can't be decrypted because password don't match.

Expected result: VRF/Remote account keys shouldn't be shared between profiles.

**Comment by cryptoBeliever** [comment]
It's a very rare case. We aggreged change it to P3.

**Comment by Peersyst** [comment]
Duplicate of #1370
