### ISSUE TITLE
Dashboard transactions list not scrollable in Firefox

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1119]
The transactions list on dashboard page cannot be scrolled when using Firefox:

![grafik](https://user-images.githubusercontent.com/77545287/107858091-a0cad680-6e32-11eb-9fc1-5ebcc569c574.png)

This is because Firefox does not support `overflow: overlay`. Should the wallet be compatible with most browsers or will it only be released as an electron app anyway?

**Comment by cryptoBeliever** [comment]
@rg911 I think we will release anyway as Electron apps, right? Marking as P3 for now.

**Comment by myxmaster** [comment]
Yes, but question is, if it is released as Electron app **only**...

**Comment by cryptoBeliever** [comment]
That's correct. Right now browser build is in the release so I'm increasing to P2.

**Comment by cryptoBeliever** [comment]
Fixed.
