### ISSUE TITLE
After the snapshot, the snapshot balance is displayed on the "symbol opt in" screen.

### ISSUE THREAD

**Issue by LynxJekyll** [nemgrouplimited/symbol-desktop-wallet#1123]
After the snapshot, I request that you view the snapshot balance on the "symbol opt in" screen.

**Comment by cryptoBeliever** [comment]
Hello @LynxJekyll . 
Please be more precise. What screen exactly you mean? What you want to be presented?
Please include a screenshot.

**Comment by LynxJekyll** [comment]
Hello @cryptoBeliever .
This screen(send image).I want this screen to show the balance when the snapshot was taken.That way, I can rest assured that the snapshot was taken reliably.
![optinScreen](https://user-images.githubusercontent.com/79050037/107889257-ae787d00-6f54-11eb-969c-5c0e0a02dc69.png)

**Comment by cryptoBeliever** [comment]
This is NEM  NIS1 wallet, and you reported the issue to the Symbol wallet. Please report here if you want https://github.com/NemProject/NanoWallet/issues.

Snapshot will be taken at the specific block. There will be separate tools that will present your balance at snapshot height.

**Comment by LynxJekyll** [comment]
Thank you for your reply.
