### ISSUE TITLE
Redundant error messages when sending transaction fails.

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1124]
When trying to send a transaction with too large amount, multiple messages are shown.

The two "Validation failed" messages are originating from RESTService line 55 (error listener). This is because the message was received from two different websockets, which is probably not intended...?

The "Failed to sign transaction" message originates from ModalTransactionConfirmationTs line 346.

There should only be one error message.

![grafik](https://user-images.githubusercontent.com/77545287/107880819-8b60b580-6ee1-11eb-8046-405915f1e443.png)

**Comment by cryptoBeliever** [comment]
For Ledger I have duplicated notifications:
- when sending tx
- when receiving confirmation

**Comment by cryptoBeliever** [comment]
If we want merge https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1122 this has to be fixed.

**Comment by cryptoBeliever** [comment]
Closing because I reported https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1171
