### ISSUE TITLE
could make icons clickable like they are for import icon 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1128]
![image](https://user-images.githubusercontent.com/10395907/107886737-87c03500-6ec7-11eb-9195-b9f4e9a47c71.png)

in the pic you can see, the clicking experience isn't consistent for the user 

I can click on the icon for the import qr and it is clickable but the icons for faucet, explorer, and wallet are not only the text is. I don't see any reason why both the icon and text shouldn't be clickable IMO or maybe there is? And of course, the edit icon is clickable too.

**Comment by cryptoBeliever** [comment]
Fixed.
