### ISSUE TITLE
verifying address on Ledger harder to do without it being displayed on screen

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1129]
**Steps to reproduce**
when setting up a Ledger, one is taken to the screen below where one enters a password and network type. 

![image](https://user-images.githubusercontent.com/10395907/107887118-63655800-6ec9-11eb-9058-90ba8fbbf724.png)

**Current behavior**
at this point in time, I'm asked to verify my address on my ledger hardware device

**Expected behavior**
how do I know that the address I'm verifying on my ledger is the one being displayed in the wallet. 

Basically, the problem is this, in basically most other hardware wallets for other chains, the address is displayed on the hardware device and the computer screen simultaneously. Then the user compares the hardware wallet address on the device to the one on the screen and clicks "verify".  What we are verifying is that the addresses are the same. but in this case, I can't actually see that address on the screen. I will be able to see it shortly thereafter when I log into my profile dashboard, but not just right there. So it isn't the end of the world but is untypical of industry best practices. 
 
**Affected Version**
pre-launch version of Symbol Bolos and Symbol desktop wallet 0.14.0

**Additional context**
Like I said, this isn't the end of the world, but I was a little surprised Ledger didn't suggest it as it is the MO for their Ledger Live as well as Trezor wallets. 

Basically, we are asking the user to go through a "blind verification" instead of a "verified verification"

**Suggested Behavior**
When I click "Next" there is a pop up with the address that shows the same address in popup as shown in my Ledger.

**Comment by cryptoBeliever** [comment]
Hmm. It works exactly the same as for Trezor (NIS1) and Ledger (NIS1). When you are creating a profile (login) on the wallet screen is not presented address because first, you need to export it the first time. How would wallet know it?

Besides that, after you login into wallet, you have an account "Show on Ledger" button where you can compare.
Also, before each transaction address verification is also done.

**Comment by jabo38** [comment]
Yes. We shouldn't use the NIS1 integration as the standard to follow, it too wasn't following best practices IMO. 

The "show on Ledger" button is really good and solves the problem and as you point out is available for one to see later, so I'm really glad that was added. That also means this issue isn't critical at all.  

I don't think it is a priority, but just saying, that usually whenever one is using a hardware wallet and there is a "verify" address function in the hardware wallet, the screen also usually displays the address so one can verify they are the same.

**Comment by cryptoBeliever** [comment]
@TriPhan96 are you aware of another mode to export address? Where the device is presenting that you exporting it and don't ask to verify?

**Comment by TriPhan96** [comment]
We can get public key and address from Ledger device automatically without user verification steps.
  IMO now we can have 2 options for this flow issue
  
  1. Keep current flow, but do not show Ledger user verification screen. Ledger device will return address without user approval to create profile on Symbol desktop wallet
  2. First get address on Ledger device without user verification then show it on the desktop wallet. Then ask users to verify address on Ledger device, if yes Symbol wallet will be created, if no will not create profile

**Comment by cryptoBeliever** [comment]
@jabo38 what you think? @TriPhan96 it requires changes in the BOLOS app or only wallet?

**Comment by jabo38** [comment]
Either option 1 or 2 seems like an improvement to me. I’d be curious which one others liked. I guess my preference is 1. People will have the “verify address” button in the wallet. And will be verifying each tax they send.

**Comment by rg911** [comment]
Option 1 is my take as well. Address is randomly generated anyway?

**Comment by cryptoBeliever** [comment]
@rg911 it's Ledger flow. For the same seed, you get each time same address ;)
For me also 1 is ok

**Comment by TriPhan96** [comment]
For both options, just modify the code on Symbol wallet @cryptoBeliever

**Comment by TriPhan96** [comment]
Should we use option 1 for child account creation flow for Ledger profile?

**Comment by jabo38** [comment]
adding extra accounts is very time consuming, so I would say if we can make that easier, we should.

**Comment by jabo38** [comment]
like for instance, let's say I have 8 accounts on Ledger as a power user. having to recreated them each time one by one and verify on the ledger one by one, takes a lot of time. 

this could maybe be a separate issue where the "profile" remembers the accounts and address and keeps them in the profile so they don't have to be recreated each time, 

But to answer the question above, yes, if I didn't have to verify on Ledger each time with a blind verification, it would speed up the process.

**Comment by cryptoBeliever** [comment]
@TriPhan96 all good but can you remove this message when creating a profile and child account?

![image](https://user-images.githubusercontent.com/17684281/108605313-a769c880-73b3-11eb-97bb-a3f2fda349de.png)

**Comment by TriPhan96** [comment]
Hi @cryptoBeliever, the message ("Verify information in your device") has been removed. Please have a look at it. Thank you

**Comment by cryptoBeliever** [comment]
Fixed.
