### ISSUE TITLE
problems creating child accounts for Symbol mainnet with Ledger

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1132]
**Steps to reproduce**
Choose mainnet when setting up a profile in the desktop wallet. 
You will get Symbol addresses that start with "N" and should match accounts that have had been opted in to receive a balance. 

Having done this, I created the first two child accounts, but could not get to a third. Every time I tried to get to a third child account, instead the 2nd child account was recreated. 

**Current behavior**
Accounts 2-8 are all the same address. 

![image](https://user-images.githubusercontent.com/10395907/107895149-eac9c000-6ef7-11eb-902c-91f02d6ae90b.png)

**Expected behavior**
Accounts 2-8 to be different addresses
 
**Affected Version**
Symbol Bolos app and desktop wallet 0.14.0

**Platform details**
Mac dmg install
 
**Additional context**
The first two accounts created in the Symbol app are the same as those created in the NIS1-> Symbol optin module so that was good. 

Creating child accounts on the Symbol Testnet worked fine as expected.

**Comment by cryptoBeliever** [comment]
I was unable to reproduce on the Linux version. @jabo38 this happens each time? Could you try to create a new profile using same Ledger?
Will ask someone with Mac to verify.

**Comment by TriPhan96** [comment]
Hi @jabo38 i have tried to reproduce your issue on [symbol-desktop-wallet-mac-0.14.0.dmg
](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/download/v0.14.0/symbol-desktop-wallet-mac-0.14.0.dmg) but it works as it should be for mainnet. Could you please try again with the above package link? And give us more information on how to produce if it's not solved.

**Comment by TriPhan96** [comment]
FYI: On NIS1 Nano Wallet, mainnet wallets are using the same derivation path as Symbol Wallet to create Symbol Optin wallet (`m/44'/4343'/{index}'/0'/0'`). But testnet wallet are using different path to optin Symbol wallet (NIS1 Nano Wallet: `m/44'/4343'/{index}'/0'/0'`, Symbol desktop wallet `m/44'/1'/{index}'/0'/0'`). 
So it might works correctly on mainnet optin function but i don't think that we can create correct testnet wallet on Symbol optin function usig Symbol wallet

**Comment by jabo38** [comment]
I'm using 0.14.0 and tried to reproduce and it didn't reproduce. Not sure if we should close the issue or not as it seems restarting the wallet and Ledger fixed the issue.

**Comment by cryptoBeliever** [comment]
I tried couple times to reproduce without success.
If it will happen again please let us know.
