### ISSUE TITLE
"To" field on Invoice tab is editable for non-multisig account

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1139]
**Steps to reproduce:**

1. Go to the Invoice tab under non-multisig account
2. Click on the To field
3. Edit the address

**Actual result:** The To field allows a user to edit a recipient address
**Expected result:** An address in the To field is not editable, like for a multisig account or on mobile

[Video for non-multisig account](https://share.getcloudapp.com/nOuloOWJ)
[Video for a multisig account (as it should be)](https://share.getcloudapp.com/mXu1pRQ2)

**Comment by cryptoBeliever** [comment]
Why allowing put custom address is a bad idea?

**Comment by Eugenity** [comment]
Because it breaks the feature's logic IMHO. Please compare with Receive feature on mobile.

**Comment by cryptoBeliever** [comment]
For me it's more like a feature not a bug. For sure not P2.

**Comment by Eugenity** [comment]
I agree with a priority and could agree also with that it's a feature but more tend to consider it as a bug.

**Comment by rg911** [comment]
I wouldn't even put a P3 on it, sounds an enhancement to me anyway

**Comment by cryptoBeliever** [comment]
I like here flexibility but leaving the decision to the discussion when the time will come.

**Comment by bassemmagdy** [comment]
@Eugenity  thanks for reporting, after discussion we agreed that it's better for flexibility reasons to give users the option to choose to whom they're gonna generating the invoice.
