### ISSUE TITLE
"Delete Contact" dialog appears again when a user clicks on a contact after removing another one

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1140]
**Steps to reproduce:**

0. You may import the address book if no contacts in a profile
1. Delete any of the contacts
2. Click on the another one remaining in the address book

**Actual result:** The Delete Contact dialog appears again until dismissed
Note: this issue occurs also after deleting all contacts and importing an address book again, then clicking on any of the entries
[Video](https://share.getcloudapp.com/yAu66p2P)

**Comment by cryptoBeliever** [comment]
Fixed.
