### ISSUE TITLE
Private Network Support on Desktop Wallet

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#1142]
Currently, the desktop wallet doesn't support private networks but it should.

On the profile creation page, we should be able to select `Private` or `Private Test` and specify the private network node's URL in the form.

**Comment by cryptoBeliever** [comment]
@yilmazbahadir is this bug or more enhancement?

**Comment by yilmazbahadir** [comment]
Yes, I think it's a duplicate. I think it's an enhancement.

**Comment by cryptoBeliever** [comment]
Closed as duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/752
