### ISSUE TITLE
Account meta data transactions timing out. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1159]
I'm trying to apply a metadata tx to a second party account. 

The second party is never given the option to approve because the deposit tx times out very quickly. 

I'm using the webwallet http://desktop-build.symboldev.com/ and the desktop wallet and had the same result.

**Comment by cryptoBeliever** [comment]
@jabo38 are you still able to reproduce? Around 20min there was some websocket fix.

**Comment by jabo38** [comment]
well, somehow better. I can now see the tx on my dashboard to improve, so I guess this issue can be closed, but..... it isn't asking me to sign the tx, instead it is saying I have already signed it and am waiting on the other person. But the other person was the initiator. 

The target account I'm in right now is the one that needs to sign but can't. 

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/10395907/108270983-be02ec00-7135-11eb-8991-f6930d9e07ab.png">

This was with the desktop wallet.

**Comment by jabo38** [comment]
On the web wallet, all is working as intended :-)

**Comment by cryptoBeliever** [comment]
:ok_hand:
