### ISSUE TITLE
Harvesting - improvements

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1161]
Persistent message will be rejected by node if:

- account has balance >= 10000 but importance = 0. It's for a fresh accounts for which recalculation did not happened. We should not allow sending user Persistent Message if importance = 0 and notify him to wait a little bit (recalculation is each 180 blocks - 90min afaik)
- if account > 50m XYM. Rare case but maybe worth verify ;)
- if there is no free slots on node. At this moment API don't return this information (how many slots is available). Can be extracted to separate issue + issue for rest

**Comment by segfaultxavi** [comment]
Please note recalculation happens every 720 blocks now (6h).

**Comment by bassemmagdy** [comment]
fixed

**Comment by cryptoBeliever** [comment]
@bassemmagdy 
"if there is no free slots on node. At this moment API don't return this information (how many slots is available). Can be extracted to separate issue + issue for rest" 
This is not done I believe? Please confirm. I will create separate issue for that.

**Comment by bassemmagdy** [comment]
@cryptoBeliever that part is not done yet as rest still misses that endpoint.
