### ISSUE TITLE
Hints / messages that are displayed in the upper right corner of the wallet are not meaningful enough.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1162]
I think it should generally be checked whether the hints / messages that are displayed when using the wallet are really meaningful enough. The messages should be adapted for each case.

Here is an example:

Under "Profile Import" there is no direct input field. Instead of  "Fields cannot be empty. Please, verify your input." 
a message should be displayed that describes that the user has to select an address.

---
![profile_import2](https://user-images.githubusercontent.com/46584115/108270451-bfe9a100-716f-11eb-879a-8c6167886ebf.png)

**Comment by garm01** [comment]
In this case, the message should also be deleted after selecting the first address.  Otherwise the message remains visible even under "Finish".

**Comment by cryptoBeliever** [comment]
@bassemmagdy maybe we can change message to 
"Please select at least one account from the list." I think it's better than "Please, select 1 or more accounts from the list"

**Comment by cryptoBeliever** [comment]
Fixed.
