### ISSUE TITLE
Copy & Past of the password when creating the wallet should not be accepted.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1167]
v0.14.0 linux

1) Fill in the password under "Password".
2) Filling in the password under "Confirm Your Password".
3) Error message that the passwords do not match.
4) Copy the password under "Confirm Your Password".
5) Paste the password under "Password".

If a user assumes that he/she made a mistake when entering the password under "Password", but the second entry under "Confirm Your Password" was correct, it should not be possible to copy the password from the second entry and paste it under "Password".
It also works the other way round.
This should not be possible.

**Comment by cryptoBeliever** [comment]
@rg911 if you think that this should have higher priority, please increase

**Comment by cryptoBeliever** [comment]
@garm01 are you able reproduce on latest version? http://desktop-build.symboldev.com/

**Comment by garm01** [comment]
I cannot reproduce it under http://desktop-build.symboldev.com/ .

**Comment by garm01** [comment]
Sry.  one way is to copy the password from a texteditor and paste it in both fields.

**Comment by cryptoBeliever** [comment]
@bassemmagdy is possible to block pasting to this field?

**Comment by cryptoBeliever** [comment]
@bassemmagdy it's possible to block pasting to the password confirmation field?

**Comment by cryptoBeliever** [comment]
Not merged. Moving back to feature tests.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch. Copying was blocked only on create profile page.
