### ISSUE TITLE
Cannot add multisig accounts when all cosigs are unknown to the network

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#1168]
When trying to create a multisig account with 3 cosigs where all cosigs are not know to the network (only public address).
I can't create the multisig, the transaction to sign does not appear at any of the cosigs and the transaction just times out.
Adding a cosig that is unknow to the network to an existing multisig worked however

**Comment by cryptoBeliever** [comment]
@meyns what wallet version? When you trying? There is ongoing stress test. Fees are high. Did you try increase it?

**Comment by meyns** [comment]
Hi, I just retried it when the testnet is calm, looks like its working now. My apologies for posting this
