### ISSUE TITLE
Harvesting for multisig does not work

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#1169]
I cannot create a remote and vrf key from a multisig account. After doing 'link all keys' there is a funds lock, but there is no transaction to sign on any of the cosigs.

After linking the remote and vrf key with the symbol-cli tool, the desktop wallet cannot unlink the keys.
Same thing, there is a funds lock transaction, but no transaction with the other cosigs to sign.

**Comment by cryptoBeliever** [comment]
@meyns are you trying to do it now when 400 TPS stress is ongoing. Did you tried increase fee?

**Comment by meyns** [comment]
Hi, I just retried it when the testnet is calm, looks like its working now. My apologies for posting this
