### ISSUE TITLE
Can't scan QR codes on 0.14.0 Mac DMG

### ISSUE THREAD

**Issue by TriPhan96** [nemgrouplimited/symbol-desktop-wallet#1178]
![Screen Shot 2021-02-19 at 20 04 05](https://user-images.githubusercontent.com/62920562/108507972-af5f3500-72ed-11eb-9b7f-58d0572ae47d.png)

Can't open webcam to scan QR code on MacOS release files. Work on development version (web (npm run dev) and electron (npm run start)

**Comment by jabo38** [comment]
Just as a reference.  The NanoWallet build had the same issue too. https://github.com/NemProject/NanoWallet/issues/634#issuecomment-787484892

**Comment by NikolaiB** [comment]
@bassemmagdy I think the permission should be asked to use camera by browser?

**Comment by bassemmagdy** [comment]
@NikolaiB Browser already asks for permission to open the camera
