### ISSUE TITLE
Mainnet - no amount input on transfer/invoice views

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1197]
There is no amount for mainnet sending form:

![image](https://user-images.githubusercontent.com/17684281/108759696-fa2ab800-754c-11eb-9abe-f16a2ac456d8.png)

**Comment by cryptoBeliever** [comment]
I'm also unable to init transaction for mainnet with message:

![image](https://user-images.githubusercontent.com/17684281/108759790-1f1f2b00-754d-11eb-9d53-16ae55dd3896.png)

Is this intentional?

**Comment by bassemmagdy** [comment]
@cryptoBeliever is it reproducible here? http://desktop-build.symboldev.com

**Comment by bassemmagdy** [comment]
@cryptoBeliever blocking transactions is intentional, but you should be able to see the amount field displayed as normal

**Comment by cryptoBeliever** [comment]
Fixed.
