### ISSUE TITLE
Incorrect Min Namespace Duration shown

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#1208]
In the Namespace creation form, an invalid Min Namespace Duration is shown:
![image](https://user-images.githubusercontent.com/10949043/108975517-dc616e00-7686-11eb-97e2-f40d710903f4.png)
It says 172800 (blocks, I assume), but at 30s per block that is 60 days, not 30 as the network announces:

http://api-01.ap-northeast-1.testnet.symboldev.network:3000/network/properties
```
"blockGenerationTargetTime":"30s"
"minNamespaceDuration":"30d"
```

This is already confusing users, which requested changes in the docs to match what the Wallet says: https://github.com/nemtech/symbol-docs/issues/584

**Comment by cryptoBeliever** [comment]
Fixed.
