### ISSUE TITLE
Profile import account selection: no balances are shown

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1219]
When importing a profile, on the account selection page all accounts are shown with balance N/A. This is because the repositoryFactory cannot be retrieved from the network store. Probably a network/CONNECT call is missing somewhere.

**Comment by cryptoBeliever** [comment]
This is regression (it worked before). In logs I can see:

![image](https://user-images.githubusercontent.com/17684281/109234533-2bfd8200-77cc-11eb-9842-631936ef7fd0.png)

**Comment by cryptoBeliever** [comment]
Fixed.
