### ISSUE TITLE
Language selection button should have an icon

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#1220]
If, for whatever reason, the app is set to a language I cannot read, I won't know how to set it back to my language.

The button at the top of the login screen that says `English`, `中文` or `日本語` should have a recognizable icon (like an Earth globe 🌍 🌐 or similar).

This was already highlighted along other UI problems in #451.

**Comment by Eugenity** [comment]
@bassemmagdy @OlegLialin have it been merged already?

**Comment by bassemmagdy** [comment]
Yes

**Comment by Eugenity** [comment]
Verified. Closing. However there is functional issue with changing language on the login page, checking, may need reporting.

**Comment by bassemmagdy** [comment]
@Eugenity no need to report, we already addressed the issue in another [pr](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1241) but not merged yet.
