### ISSUE TITLE
Show accurate Harvesting status by periodic polling

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#1222]
It seems like whether a node has accepted an account's persistent delegation requests or not is only updated when entering the Harvesting screen.
This means that the user needs to go back and forth between Home and Harvesting for a while until the node updates, which might never happen.

It would be easier if the node was periodically polled (say every 30s) to reflect the current state of the link.
This would only be needed in the "ACTIVATION IN PROGRESS" and "ACTIVE" states.

**Comment by cryptoBeliever** [comment]
Checked.
