### ISSUE TITLE
Deleting profile from local computer

### ISSUE THREAD

**Issue by nav1d** [nemgrouplimited/symbol-desktop-wallet#1228]
It would be nice if there is an option to delete local profile from local system/computer for more safety. AFAIK NemWallet had that option. So implementing an option to removing the local profile/wallet would be nice.

![photo_2021-02-27_04-10-20](https://user-images.githubusercontent.com/19347632/109383564-7251fe80-78fc-11eb-8919-288ef6923938.jpg)

**Comment by cryptoBeliever** [comment]
Checked.
