### ISSUE TITLE
Provide SHA256 checksum values for downloading

### ISSUE THREAD

**Issue by roleerob** [nemgrouplimited/symbol-desktop-wallet#1234]
It would be a nice and welcome addition to future updates to have this value made available to us.  Not an expert, but I understand this provides at least some additional level of confidence we are installing a valid executable file onto our personal workstations.

Thanks! 🙂

**Comment by cryptoBeliever** [comment]
Yes. I think it will be added same as for NEM Wallet.

**Comment by jabo38** [comment]
yep, checksums are nice to have

**Comment by rg911** [comment]
will do from v1.0.0 release 👍

**Comment by cryptoBeliever** [comment]
Done.
