### ISSUE TITLE
Unable to add node when all default nodes offline

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1236]
I'm unable to add node (it's added but not visible) when all default nodes are offline:

https://share.getcloudapp.com/bLugy5Jl

**Comment by trestoJP** [comment]
I look forward to taking action as soon as possible.
The problem of not being able to connect to nodes is spreading a bit, probably due to this in Japanese SNS.

**Comment by cryptoBeliever** [comment]
Fixed. It's possible to add node when all others offline. Checked on branch gh1236-fix-unability-to-add-nodes-when-defaults-offline

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
