### ISSUE TITLE
Incorrect (Encrypt message) label in transaction summary

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#1242]
In the Send form there's a checkbox named `Encrypt message`, and then, when you click Send, there's a summary form that shows the encrypted message followed by `(Encrypt message)`.
The correct message should be `(Encrypted message)`, otherwise, it's confusing.

I've tried to provide a patch but there's only one instance of `Encrypt message` in the language json file, so I guess the same string is being used in both places.

(This is a cosmetic issue)

**Comment by NikolaiB** [comment]
fixed
