### ISSUE TITLE
Automatic refresh sometimes doesn't work

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1264]
Sometimes the refresh button has to be pressed to get new transactions. In that state, nothing on the dashboard is updated automatically (like balance, chain height etc.). Probably a problem with websockets?

**Comment by NikolaiB** [comment]
fixed.

**Comment by NikolaiB** [comment]
@bassemmagdy I am able to reproduce it sometimes for History page.

**Comment by bassemmagdy** [comment]
@NikolaiB that issue was related to automatic refresh for network panel (chain height - transactions - peer numbers)

**Comment by NikolaiB** [comment]
fixed in integration branch
