### ISSUE TITLE
Wallet not displaying on Mac

### ISSUE THREAD

**Issue by simonm99** [nemgrouplimited/symbol-desktop-wallet#1281]
Hi,

I am having issues with the Mac version of the wallet. When I open it I just get a blank screen and no content is ever loaded:

<img width="1680" alt="Screenshot 2021-03-10 at 11 41 21" src="https://user-images.githubusercontent.com/17701581/110624413-14dc6e00-8196-11eb-834a-287a508ff5f6.png">

However I noticed if I open a second instance it then this one does display and this is reproducible (first window always blank, second window always displays):

<img width="1680" alt="Screenshot 2021-03-10 at 11 42 07" src="https://user-images.githubusercontent.com/17701581/110624521-36d5f080-8196-11eb-90b3-be5750617e07.png">

Previously I have been using the universal wallet which works fine but I recently got a Ledger and it doesn't seem to work with that version so I would really like to be using the Mac application instead.

Some basic details of my system:

<img width="572" alt="Screenshot 2021-03-10 at 11 49 39" src="https://user-images.githubusercontent.com/17701581/110624977-c8456280-8196-11eb-8241-509191acf672.png">

Let me know if you need any further information.

Thanks :)

**Comment by simonm99** [comment]
Should also say that this is with 0.14.1. Going back over previous releases the issue seems to have arisen at release 0.13.6 and was working in 0.13.5.

**Comment by simonm99** [comment]
Spotted someone else with the same issue on the forum: https://forum.nem.io/t/symbol-wallet-release-desktop-android-ios-19-feb-2021/27699/7

**Comment by simonm99** [comment]
Also having the same problem with v0.15.0

**Comment by bassemmagdy** [comment]
can you use [debugtron](https://github.com/bytedance/debugtron) to check if any console errors.

**Comment by simonm99** [comment]
Thanks for getting back to me :)

> can you use [debugtron](https://github.com/bytedance/debugtron) to check if any console errors?

This is all I get:

```
Debugger listening on ws://127.0.0.1:49723/71a5e187-3b2e-452e-a284-5c4464aa3e64
For help, see: https://nodejs.org/en/docs/inspector

DevTools listening on ws://127.0.0.1:49724/devtools/browser/cfc667f2-b93c-4e2b-9263-91cb3ff9c9b5
(node:71775) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Debugger attached.
Debugger listening on ws://127.0.0.1:49723/71a5e187-3b2e-452e-a284-5c4464aa3e64
For help, see: https://nodejs.org/en/docs/inspector
```
Screenshots - the all white window in the background is the running Symbol wallet:

<img width="1584" alt="Screenshot 2021-03-11 at 17 57 13" src="https://user-images.githubusercontent.com/17701581/110832673-7d5d4500-8293-11eb-9bc0-70a7df5326c3.png">

<img width="1591" alt="Screenshot 2021-03-11 at 17 57 32" src="https://user-images.githubusercontent.com/17701581/110832708-86e6ad00-8293-11eb-94a4-6951c43b85c0.png">

<img width="1580" alt="Screenshot 2021-03-11 at 17 57 41" src="https://user-images.githubusercontent.com/17701581/110832743-9108ab80-8293-11eb-8712-5677dd1e5170.png">

**Comment by simonm99** [comment]
Also the NEM desktop wallet works fine:

<img width="1575" alt="Screenshot 2021-03-11 at 18 02 49" src="https://user-images.githubusercontent.com/17701581/110833150-0f654d80-8294-11eb-8038-cdb6ba9a8c3b.png">

As did all releases pre-0.13.6

**Comment by simonm99** [comment]
Sorry another comment! I also ran Debugtron (when I had the first instance open) on the second instance where the window does display:

```
Debugger listening on ws://127.0.0.1:50214/3e75d97e-b231-4f3e-a148-56ac815238dc
For help, see: https://nodejs.org/en/docs/inspector

DevTools listening on ws://127.0.0.1:50215/devtools/browser/5fd275e4-3ec9-4a54-ae19-77447b35caf2
(node:73356) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Debugger attached.
Debugger listening on ws://127.0.0.1:50214/3e75d97e-b231-4f3e-a148-56ac815238dc
For help, see: https://nodejs.org/en/docs/inspector
```

Screenshots:

<img width="1644" alt="Screenshot 2021-03-11 at 18 26 24" src="https://user-images.githubusercontent.com/17701581/110836213-b4cdf080-8297-11eb-9878-d2ba9148d801.png">

<img width="1647" alt="Screenshot 2021-03-11 at 18 26 39" src="https://user-images.githubusercontent.com/17701581/110836231-bac3d180-8297-11eb-88ca-37f1c3b54c4c.png">

**Comment by bassemmagdy** [comment]
@simonm99 could you try clearing the old application cache and saved state for symbol-wallet on your mac?

**Comment by simonm99** [comment]
> @simonm99 could you try clearing the old application cache and saved state for symbol-wallet on your mac?

That solved it! Thank you! I just deleted the ~/.symbol-desktop-wallet directory and it opened without any issues
