### ISSUE TITLE
'Send' button is not clickable while adding metadata to the namespace

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1290]
**Steps to reproduce:**

1. Create a namespace for a non-multisig account
2. Go to Namespaces page
3. Click 'Add metadata' button
4. Specify the value and target
5. Click Send button

**Expected result:** A confirmation dialog appears
**Actual result:** No reaction of the Send button on clicking it

[Video](https://share.getcloudapp.com/eDu8OQWd)

**Comment by NikolaiB** [comment]
fixed in v1.0.0
