### ISSUE TITLE
There are no notifications if the node has > 10 harvested accounts on it

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1292]
WTR:
1. Verify that your public key is not in the list (Can not be more then 10 accounts) http://api-01.eu-west-1.testnet.symboldev.network:3000/node/unlockedaccount
2. Activate harvesting with eu-west-1 node

Result: Despite that your public key is not in the list, you can see **Activation in progress** status despite that the node can not hold > than 10 accounts.

![image](https://user-images.githubusercontent.com/11311924/112467043-bbc52a80-8d90-11eb-8522-1e538f05308f.png)

**Comment by bassemmagdy** [comment]
a node can decide what to do, might kick out any of the locked accounts to add a new one depending on delegatePrioritizationPolicy, so we should keep checking to notice any change in accounts.

**Comment by NikolaiB** [comment]
fixed
