### ISSUE TITLE
Save button on Supply Change Transaction page has broken design

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1299]
v0.15.0

WTR:
1. Go to aggregate transactions
2. Go to Supply Change Transaction page

Result: You can see that `save` button has broken design

![image](https://user-images.githubusercontent.com/11311924/110899729-d4165d80-832b-11eb-8b4e-90f2cc8a9377.png)

**Comment by Eugenity** [comment]
Verified. Closed.
