### ISSUE TITLE
QR codes on paper wallets and account info page displaying the wrong chain ID

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1308]
As we can see from this paper wallet, the chain ID showing is the testnet chain ID and not the mainnet chain ID. You can get the ID by scanning the account QR. Scanning the Account QR on the Account's panel in the Dashboard has the same error too. 

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/10395907/110964422-8d276880-8329-11eb-88ff-d4dbd4b16c60.png">

here is the same seed imported into the a testnet account

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10395907/110964508-a3cdbf80-8329-11eb-8df7-cadc546a636d.png">

Deleting all profiles and wallets and reinstalling from scratch fixes the problem. This leads me to believe that somehow when the wallet updates some ChainID information gets held over from a place it isn't supposed to.

**Comment by surekabpm** [comment]
Tested and can be closed
