### ISSUE TITLE
tx secured by hash lock deposit tx timing out quickly and not getting confirmed in a block 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1326]
are there any nodes that are set to pick up old txs? some reports of txs with "recommended" fees not getting accepted, including one by me with a hash lock fund deposit.

**Comment by jabo38** [comment]
okay, here is the more clear report. 

I made a hash lock tx. It did finally get accepted by the network after maybe 15-20 minutes.  Here is the hash lock. http://explorer.symbolblockchain.io/transactions/94618CDAC968A99CAA77303E3B2922DA81ECF65807ECC8A9CAC7BCFF72CA0E4A

But in this 15-20 minutes, the multisig tx that was supposed to get signatures was pruned by the network I think. 

So then my hash lock got accepted and I couldn't even sign my tx as the multisig tx secured by the hash lock wasn't even there. 

This of course meant I will lose the 10 XYM deposit.

**Comment by NikolaiB** [comment]
@Peersyst could you attach the PR, please.
