### ISSUE TITLE
XYM transaction confirmed but shows 0 balance

### ISSUE THREAD

**Issue by helmetbean** [nemgrouplimited/symbol-desktop-wallet#1329]
xym incoming transfer is verified but the balance is showing 0 .  cross checked the transaction at http://explorer.symbolblockchain.io/   .. and it shows both the transaction verified and the proper balance in the account

**Comment by bassemmagdy** [comment]
@helmetbean what kind of os are you using?

**Comment by helmetbean** [comment]
Windows 10 Home

**Comment by bassemmagdy** [comment]
could you look here and clear those cached paths?  https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1330#issuecomment-800887606

**Comment by helmetbean** [comment]
i only ever installed 1 xym wallet.  There is no history of any other symbol wallets in my system.

**Comment by bassemmagdy** [comment]
can you share transaction Hash on explorer? and screenshots of the wallet?

**Comment by helmetbean** [comment]
I set up the wallet on my wife’s computer and everything the balance showed as being available.   My immediate concern is resolved although it’s strange to not work on my computer.
