### ISSUE TITLE
After startup, the screen is blank

### ISSUE THREAD

**Issue by Rhime-design** [nemgrouplimited/symbol-desktop-wallet#1330]
**▼Describe the error**
DesktopWallet does not start properly.
The window starts up, but it is a blank screen and the GUI is not drawn at all.

**▼Usage Environment**
- Windows10 20H2
- symbol-desktop-wallet-win-1.0.0

**▼To Reproduce**
1. Insta;ll "symbol-desktop-wallet-win-1.0.0.exe"
[Release v1.0.0 · nemgrouplimited/symbol-desktop-wallet](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v1.0.0)
2. Click on the shortcut "Symbol Wallet".
3. See error

**▼What I've tried**
- Reboot and reinstall
- Run as administrator
- Change compatibility options
- Switching Dark Mode in Windows 10
→No improvement.

**▼Expected behavior**
I don't know.

**▼Screenshots**
![2021-03-17_15h17_37](https://user-images.githubusercontent.com/34479640/111425932-352c9f80-8737-11eb-81e7-314d271fab67.jpg)

**Comment by bassemmagdy** [comment]
Hi Rhime, please have a look on https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1281

**Comment by Rhime-design** [comment]
Thanks, I should have looked more at the list of Issues 😆

I did a file search on my C drive for "symbol" and found three folders with the name "symbol-desktop-wallet" in "C:\Users\%username%\AppData\".
I then moved the folder to a different location and reinstalled the wallet and it started fine.

**Comment by Rhime-design** [comment]
Problem solved, but I'd like to talk a bit from a UX perspective, if that's okay.

I recently did a clean install of Windows, and I remember that I copied the folder corresponding to SymbolWallet from my backup to the AppDate folder.
I think this is a special case.

On the other hand, setting up a new wallet software from an older version is a common case, but have you confirmed that users can use the uninstaller (Uninstall Symbol Wallet.exe) to complete the removal of the old files?

**Comment by bassemmagdy** [comment]
@Rhime-design Windows uninstaller should completely remove old profiles and app settings. For setting a new wallet from older version I agree that's common but not for v1 :)

**Comment by bassemmagdy** [comment]
@Rhime-design Windows uninstaller should completely remove old profiles and app settings. For setting a new wallet from older version I agree that's common but not for v1 :)

**Comment by bassemmagdy** [comment]
@Rhime-design Windows uninstaller should completely remove old profiles and app settings. For setting a new wallet from older version I agree that's common but not for v1 :)
