### ISSUE TITLE
No symbol coins in my wallet after launch blockchain

### ISSUE THREAD

**Issue by fallingdown1984** [nemgrouplimited/symbol-desktop-wallet#1331]
Hello guys,
i was in contact with the nem Helpdesk in telegram regarding symbol coins in my symbol wallet (Version 1.0).
I did optin last year in October.

Cryptobeliver prefer me to contact you. I deinstall and install symbol wallet awe times also delete and import my symbol account with mnemonic. Nothing helped.

i really do not know why and i appreciate when you solve my issue.

Kind regards 

IKE

![Bildschirmfoto 2021-03-17 um 10 01 45](https://user-images.githubusercontent.com/29947956/111441665-d26fdf80-8707-11eb-9817-d6127a75a8ef.png)
![Bildschirmfoto 2021-03-17 um 10 01 34](https://user-images.githubusercontent.com/29947956/111441675-d439a300-8707-11eb-814c-d5dd33ce7d64.png)
![Bildschirmfoto 2021-03-17 um 10 01 23](https://user-images.githubusercontent.com/29947956/111441678-d56ad000-8707-11eb-8264-8afeab5502d2.png)

**Comment by fallingdown1984** [comment]
![Uploading Bildschirmfoto 2021-03-17 um 10.37.57.png…]()

**Comment by fallingdown1984** [comment]
here i new screenshot

![Bildschirmfoto 2021-03-17 um 10 37 57](https://user-images.githubusercontent.com/29947956/111447119-67290c00-870d-11eb-8425-92e6040e085c.png)

**Comment by bassemmagdy** [comment]
did you check this? https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1281

**Comment by fallingdown1984** [comment]
You can close this issue. I can see my symbol coins now in my wallet. I don't know why, but it works :)
