### ISSUE TITLE
Add Skip button on mnemonic confirmation page for testnet 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1332]
![image](https://user-images.githubusercontent.com/11311924/111454407-cce1bc00-873e-11eb-9a7c-141f6a61dd0f.png)

**Comment by NikolaiB** [comment]
@Peersyst could you attach the PR please.

**Comment by cryptoBeliever** [comment]
Fixed in gh1431-harvesting-fix

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
