### ISSUE TITLE
Selected Transaction Fee seems not to be taken

### ISSUE THREAD

**Issue by Thies1965** [nemgrouplimited/symbol-desktop-wallet#1333]
V1.0.0
On sending XYM, seleccted fee from drop-down seems not to be taken.
I transfered XYM from my Opt-In account to a newly created account. Within the "send" dialog, I selected the fee-option "fastest 1 symbol.xym".
My account had (as an example) 1.000.001,244691 XYM, I was sending the amount 1.000.000,244691 XYM, which is 1 less than my balance which should be the fee.
After sending and confirming the transaction, my account does not have 0 XYM but has some fractions left: 0,553398

Steps to reproduce:
- within your account select "Send"
- select a to account
- take the complete balance of your account and subtract 1 symbol.xym
- select from the fee dropdown the option "Fastest 1 symbol.xym"
- Press send

I would expecct that the balance of the account is exactly 0 symbol.xym. But some fractions remain.

Regards,
Markus

<img width="1284" alt="Bildschirmfoto 2021-03-17 um 13 25 37" src="https://user-images.githubusercontent.com/7998827/111467306-9303bc00-8724-11eb-8a44-9a4bb6ed5827.png">

<img width="778" alt="Bildschirmfoto 2021-03-17 um 13 26 21" src="https://user-images.githubusercontent.com/7998827/111467301-926b2580-8724-11eb-90d5-0636e1808f89.png">

<img width="1283" alt="Bildschirmfoto 2021-03-17 um 13 27 05" src="https://user-images.githubusercontent.com/7998827/111467290-9008cb80-8724-11eb-80ef-dd8ae08bb0be.png">

**Comment by bassemmagdy** [comment]
@Thies1965  Hi Marcus, Selected fees are applied but, the values represented in the fee selector are the maximum values for each case but not the actual amount that you'll pay. From the screenshots you provided, you can easily notice in transaction details that Max Fee is 1, not the actual fee which is right.
