### ISSUE TITLE
Moving Funds from Opt-In Seed Account to Another Seed Account

### ISSUE THREAD

**Issue by jlpkc65** [nemgrouplimited/symbol-desktop-wallet#1336]
My opt-in seed account has the message "This account is obtained by an older derivation. It is recommended that you move the funds to a Seed Account." I've attempted to move the funds from the opt-in account to a new seed account, but I'm not having any luck. I don't receive any error messages. Thanks for any advise you can provide for resolving my issue.

**Comment by bassemmagdy** [comment]
@jlpkc65 Did you import any seed account to transfer funds to it? if yes what happens when you try to send a transaction?

**Comment by jlpkc65** [comment]
Thanks for responding. I'm not sure I completely understand your questions however. Let me try to describe things a little better. I created my wallet profile by importing my mnemonic passphrase and account (named "Opt In Seed Account 1" in the wallet) that I had created months ago when I opted in for the snapshot. After importing, I was forced to also select/create a new seed account (named as "Seed Account 1" in the wallet). I was trying to then move or send my tokens from the "Opt In Seed Account 1" (which has the message "This account is obtained by an older derivation. It is recommended that you move the funds to a Seed Account") to "Seed Account 1." When I go through the send process, everything appears to work successfully when I submit (no error messages), but the tokens are never sent to the new account. I'm sure I'm not doing something incorrectly for moving or sending the tokens, but not sure what it is. My goal of is to do the delegated harvesting next, but wanted to move the tokens to the new account first.

**Comment by smalleke** [comment]
i have the same problem, hopefully someone can telle us whats wrong?

**Comment by jabo38** [comment]
there have been some problems with fees on the network. please wait one day and try again as the network fee multiplicator adjust fees back to a reasonable range. 

please also just test sending a few XYM first.

**Comment by jlpkc65** [comment]
Sounds good. I was letting the Fee default to "Recommended" and hadn't tried to change that option. I'll wait until tomorrow evening (around UTC 00:45) and test with a few tokens.

**Comment by jlpkc65** [comment]
I'm unable to test at this point because I can't connect to the node now. I've not been able to connect all day for some reason.

**Comment by jlpkc65** [comment]
Okay. Definitely there's some type of bug with the desktop wallet for Mac. After updating the desktop wallet to version 1.0.0 (which resolved my node connection issue), I attempt to send XYM from my opt-in account to my new seed account. No matter what fee option I selected, nothing worked (no errors or warning about insufficient fees). So, I decided to install the wallet on my iPhone and try. I was able to send the XYM instantly with the iPhone wallet.

**Comment by jlpkc65** [comment]
One more update. The harvesting functionality in the desktop wallet for Mac is not working either. At least I couldn't get past the linked keys process, and there were no errors received. When I tried in the iPhone wallet, the linked keys and activation processed instantly.

**Comment by Peersyst** [comment]
Thanks for the feedback @jlpkc65 , the problem may be caused by the storage on your wallet being corrupted. If you can tell us the OS you are using we will explain how you can it.

Be sure to have a safe back up before trying anything

**Comment by jlpkc65** [comment]
Thanks. I'm running macOS Big Sur (ver 11.2.3).

**Comment by NikolaiB** [comment]
@Peersyst @bassemmagdy I can not reproduce it with v1.0.0

**Comment by cryptoBeliever** [comment]
Most probably it was because old application version cache.
Try clear it. On Mac should be located in one of:
~/Library/Saved\ Application\ State/<app package name>
~/Library/Application\ Support/<app package name>
~/Library/Cache/<app package name>
~/.symbol-desktop-wallet

Because all similar issues were cache-related, I assume that this should fix the problem.
