### ISSUE TITLE
Ledger - harvesting + multisig problems

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1337]
I got report that user is unable start harvesting on Ledger:

![image](https://user-images.githubusercontent.com/17684281/111550781-236eea80-877f-11eb-907d-6b6ae7d368f8.png)

I also imported my account to verify unlinking keys. And unlink keys also doesn't work:

![image](https://user-images.githubusercontent.com/17684281/111550800-34b7f700-877f-11eb-8292-e28c80345eba.png)

Dave also reported that user experience problems with converting to 1 of 1 multisig on Ledger:

"there is some bug with ledger. If i convert account to multisig 1 of 1 with ledger as cosigner, I can not sign any tx for multisig acc: Failure_signature_not_verifiable"

**Comment by jabo38** [comment]
I had a problem trying to harvesting that may or may not be related to this. 

Trying to harvest from the optin account, I could not activate it.  But moving funds to a fresh account and trying to harvest from that was fine if using ledger.

**Comment by cryptoBeliever** [comment]
Fixed in 1.0.1
