### ISSUE TITLE
Disable linking delegated harvest button when the importance is 0

### ISSUE THREAD

**Issue by xembook** [nemgrouplimited/symbol-desktop-wallet#1338]
It seems to me that linking delegated harvest fails until the importance is calculated.
I think it would be better to control the button to link when the importance value is 0 so that it cannot be pressed.

**Comment by segfaultxavi** [comment]
If the button is disabled, there should be a message explaining why. Something like "Your importance score (link to the docs) is too low, harvesting will not be effective. Please increase your balance and wait for the importance score to be recalculated."
Ideally, it could also include a countdown to the next importance recalculation (it happens every multiple of 720 chain height).
Doc link: https://docs.symbolplatform.com/concepts/consensus-algorithm.html#importance-calculation
