### ISSUE TITLE
Sending txs with too low of a fee and the network won't take them, but no error

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1339]
I have tried to send some txs with a "slowest fee" of 0.005 XYM and the network won't take them. That is fine, but I sign the tx and get messages in green that all is good, but then no message saying the network won't accept my tx.  So normally I expected to see a "pending tx" in the dashboard. And now not. Which again is fine. That is the networks choice, but I as a user am confused because I didn't get a message anywhere saying "hey, that tx isn't actually pending, you need to try again with a higher fee"

**Comment by bassemmagdy** [comment]
@jabo38 is this still causing a problem as we already re-built the fees calculations transaction in the desktop-wallet. so slowest should work fine too!

**Comment by bassemmagdy** [comment]
fixed
