### ISSUE TITLE
Multisig txs that are partial are visible at first but once signed and are pending are not

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1340]
I have a 3-of-3 signer on Alice's account. She is sending to Bob. 

When I initiate the tx I can see it as a partial in the dashboard of all three signers an Alice, and I think even Bob too (I'd have to double check on Bob). 

After the 3 signers sign, the transaction can no longer be seen on Alice's dashboard, nor any of the signers. I tried viewing it this way or that way, but none of them work. 

Eventually the tx is confirmed, and then it is clearly visible on Alice and Bob's dashboard. But in between that time, I don't know if they network has accepted the tx or rejected it. 

*This can lead a person to initiate a second time, thinking there was a network error or fee was too low when actually the tx will go through.

**Comment by cryptoBeliever** [comment]
Looks ok on branch gh1487-partial-transactions-disappears

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
