### ISSUE TITLE
Account restrictions confirmation buttons are displaced 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1341]
v 1.0.0
WTR:

1) Go to Accounts page
2) Click + button and choose account restriction tab

Result: you can observe that Cancel and Confirm buttons are displaced 
![image](https://user-images.githubusercontent.com/11311924/111768233-dfd8c580-88d1-11eb-8a41-17d5f71dcb34.png)

**Comment by OlegLialin** [comment]
Do buttons have to look like this?
![photo_2021-03-25_19-06-12](https://user-images.githubusercontent.com/20932742/112513648-9b539b00-8da5-11eb-94e6-d3052c09885f.jpg)

**Comment by bassemmagdy** [comment]
fixed
