### ISSUE TITLE
Multisig account is requested to sign a multisig tx

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#1354]
Steps to reproduce:
- Convert an account into multisig with two of two cosigners.
- Initialize a multisig tx with one of the cosigners.
- Switch to multisig account and display the aggregate bonded transaction details.
-> A request to sign the tx is displayed (see screenshot below). This obviously makes no sense because only the cosigners can sign it.
- Switch to the cosigner account who didn't sign yet and open the tx details (the signing request is now correctly displayed).
- Switch back to the multisig account and open tx details.
-> Now the signing request is not shown, but a message "You have already sent a co-signature for this transaction.", which is also wrong.

![grafik](https://user-images.githubusercontent.com/77545287/111908021-eabd6280-8a57-11eb-9ec9-27ae75f2f7a5.png)

**Comment by bassemmagdy** [comment]
Hi @myxmaster is that issue still reproducible in latest-version?

**Comment by bassemmagdy** [comment]
Thanks @myxmaster  for reporting, seems like the issue is fixed, please re-open if you could reproduce
