### ISSUE TITLE
In Account Information, improve display of Multisig Tree/Signers required.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#1355]
I think here should also be displayed 2 of 4. For different configurations, perhaps  " 2/1 of 4 " or something similar would be better.

---

![multisig](https://user-images.githubusercontent.com/46584115/111912871-d3887000-8a6b-11eb-8e0b-1aa84edbeba9.png)

---

![multisig2](https://user-images.githubusercontent.com/46584115/111912885-dd11d800-8a6b-11eb-9dae-220fdd27ecbf.png)

**Comment by coiki** [comment]
User Story: “As a user of a Multisig account, I want signers to be expressed correctly everywhere it is used, so I can easily understand the configuration of that Multisig account.”

Acceptance Criteria:
- AC1: When referencing the Multisig Tree’s account config, the text displayed should always correctly identify the account.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch. For example:

![image](https://user-images.githubusercontent.com/17684281/123485868-4b39de00-d60b-11eb-92e6-419e6a915738.png)
