### ISSUE TITLE
Harvesting - Wallet not showing income from 25% harvester service fee

### ISSUE THREAD

**Issue by kodty** [nemgrouplimited/symbol-desktop-wallet#1358]
Reproduce:
1. set up a node leaving automatic harvesting on
2. set the beneficiary account to be the same address as the node account
3. credit the node account (which is already converted to multisig) with some xym and allow it to harvest
4. go to the wallet and select the cosigner account
5. open the harvesting page of the wallet and select the multisig account above

In the list of blocks harvested, it will show the income from the 75%, but the 25% beneficiary income does not show in the wallet while it does show in the explorer.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
Before:
![image](https://user-images.githubusercontent.com/17684281/123484671-07de7000-d609-11eb-8970-2f2b346fdea4.png)
After fix:
![image](https://user-images.githubusercontent.com/17684281/123484687-0e6ce780-d609-11eb-98ae-bc86912fd365.png)
