### ISSUE TITLE
Create a warning for hash locks. Users may not receive the 10XYM back

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1359]
WTR:

1. Go to Harvesting page and activate harvesting
2. Stop Harvesting

Result: you can see that 10 XEM is locked and can not be unlocked 
Example: http://explorer.testnet.symboldev.network/transactions/94912C70F59B4FD30050012079B79CBAD0211974181F913937F355EC7846A594

**Comment by cryptoBeliever** [comment]
Same problem was identified when unlinking harvesting keys for multisig account.
