### ISSUE TITLE
OptIn account shows 0 balance 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1361]
WTR:

1. Import OptIn account with mnemonic
2. At the `Address to interact with` page you can see the OptIn address with 0 balance

![image](https://user-images.githubusercontent.com/11311924/112111045-e0c56c00-8bdd-11eb-8191-5624c207ae39.png)

3. Choose this address and you can see in Profile import it has 0 balance

![image](https://user-images.githubusercontent.com/11311924/112111245-23874400-8bde-11eb-9fc7-b8f4216112d2.png)

4. When you submit you can see OptIn account with 0 balance and having two the same assets. One is 0 enother with some XYM.

![image](https://user-images.githubusercontent.com/11311924/112112256-7f9e9800-8bdf-11eb-843f-2758e1faca61.png)

Please Note with mobile wallet it works well.

**Comment by cryptoBeliever** [comment]
- What version of wallet?
- Did you tried prune cache?

Depends on system it's in different places:

Windows:
C:\Users\<user>\AppData\Roaming\<yourAppName>\Cache
I believer there is couple of other places in windows holding data as mentioned here https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1330#issuecomment-800887606
Linux:
/home/<user>/.config/<yourAppName>/Cache
OS X:
~/.symbol-desktop-wallet
~/Library/Saved\ Application\ State/<app package name>
~/Library/Application\ Support/<app package name>
~/Library/Cache/<app package name>

**Comment by cryptoBeliever** [comment]
@NikolaiB could you check on Monday according to my comment above? I'm not able to reproduce.

**Comment by cryptoBeliever** [comment]
This was probably related to not cleared cache from previous wallets. @NikolaiB if you could reproduce just reopen.
