### ISSUE TITLE
Reproduce sounds when receiving transactions

### ISSUE THREAD

**Issue by Peersyst** [nemgrouplimited/symbol-desktop-wallet#1362]

**Comment by jabo38** [comment]
I guess we are talking about the same thing. https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1365

**Comment by surekabpm** [comment]
tested the branch .. I can hear the sound for the transactions.. this PR can be merged

**Comment by surekabpm** [comment]
This issue is tested in integration this can be closed
