### ISSUE TITLE
Cannot enter Node URL directly in Delegated Harvesting

### ISSUE THREAD

**Issue by xembook** [nemgrouplimited/symbol-desktop-wallet#1363]
I can select a node from the list box, but when I type the URL value directly, it shows "Invalid node" and I cannot link to it.

**Comment by bassemmagdy** [comment]
@xembook are you trying to input a custom node, or you're using one of the available peer nodes?

**Comment by cryptoBeliever** [comment]
@xembook I guess this is duplicate https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1116.
