### ISSUE TITLE
Redundant space in mosaics amount when imported from QR code with prepared invoice

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1373]
**Steps to reproduce:**

1. Go to Invoice tab
2. Provide needed data into the fields on the page, specify mosaics amount with thousands (i.e. 1000 or 2000, 10000 etc.)
3. Download QR code
4. Import that QR code
5. Click Send button
**Expected result:** Mosaics amount is imported in the right format w/o redundant symbols
**Actual result:** There is a redundant space in mosaics amount preventing a user from successfully initiating a transaction

[Video](https://share.getcloudapp.com/llu5mkQ7)

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
