### ISSUE TITLE
A user can try change duration for symbol.xym mosaic

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#1376]
**Steps to reproduce:**

1. Go to Mosaics page
2. Go under 'Create new namespaces' tab
3. Specify 'Namespace Name' field with "symbol"
4. Click Send button

**Expected result:** There is an error message pop-up informing a user that such operation for reserved namespaces is imposible
**Actual result:** An operation is initiated but fails with an error message about invalid duration (which literally means that it tries to change the 'symbol' mosaic duration as far as I can assume)

[Video](https://share.getcloudapp.com/YEuRjywb)

**Comment by cryptoBeliever** [comment]
Not fixed. My comments in https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1452

**Comment by bassemmagdy** [comment]
related to https://github.com/nemtech/catapult-rest/issues/631

**Comment by cryptoBeliever** [comment]
Ok, As a temp fix it's ok :+1:

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
