### ISSUE TITLE
Offline transaction - not able import QR on offline machine

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1388]
Steps:

1. Close wallet and clear all profiles (Linux ~/.symbol-desktop-wallet)
2. Turn off Internet Connection
3. Open wallet again.
4. Create or import profile
5. Logout
6. Go to Offline transaction
7. "Cosign transaction" tab
8. "Import QR Code"
9. Try import QR

When we try import QR (for example by file upload) scanner is not processing.

I checked on web version and wallet is trying connect to network to get resource (not sure if same issue is on Electron app but it's very likely). Js should be included to app.
https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js

**Comment by surekabpm** [comment]
the issue is tested , under the cosign transaction during offline(withut internet), imported QR code and it worked. so this can be closed 
![image](https://user-images.githubusercontent.com/49143210/114513793-337fca00-9c58-11eb-8631-cb5f3ddeb721.png)
