### ISSUE TITLE
The wallet is using "average" fee still and the fees on the network are still going up

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1391]
I guess first off, a slowest fee or slow fee transaction is not often any "slower" so that naming system should be changed. To just 

No
Lowest
Low
Average
High

Second of all there is a new wallet build, 1.0.1 and it is still choosing "Average" fee when it should be defaulting to Lowest or Low to help bring down the network fees.

**Comment by surekabpm** [comment]
@AdriaCarrera based on our slack discussion , SLOW: minFeeMultiplier
SLOWEST: minFeeMultiplier + 0.35 * averageFeeMultiplier
 FAST: minFeeMultiplier + 0.65 * averageFeeMultiplier
the calculation is not correct , see below screenshots , min fee multiplier is 65 , avg fee multiplier is 39017
![image](https://user-images.githubusercontent.com/49143210/114180083-632f8900-995d-11eb-9a13-c37570eb3852.png)
![image](https://user-images.githubusercontent.com/49143210/114180325-ad186f00-995d-11eb-94cb-56fead0a2f2d.png)

**Comment by Peersyst** [comment]
Those are multipliers, not final fee so I think it's all right

**Comment by surekabpm** [comment]
ok.. then it can be merged

**Comment by surekabpm** [comment]
the transaction fees loks reasonable but not able to verify teh calculation of fees, as no information on transaction size

**Comment by surekabpm** [comment]
The transaction fees looks reasonable but not able to verify the calculation of fees, as no information on transaction size 
![image](https://user-images.githubusercontent.com/49143210/114500602-fdd1e580-9c45-11eb-8471-b0699496f26c.png)
