### ISSUE TITLE
Node local storage overrides all the nodes when swapping profiles

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-desktop-wallet#1406]
Related objects:

https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/services/NodeService.ts#L40
https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/core/database/storage/NodeModelStorage.ts

1) The list is [re-saved ](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/services/NodeService.ts#L83)resetting any manually added node in another profile (with different network type)
2) The list only filters by [network type](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/services/NodeService.ts#L37), if in the future the wallet handles multiple private network types (with different generation hashes), the list won't work

The solution would be to migrate (code and data) NodeModelStorage from VersionedObjectStorage to VersionedNetworkBasedObjectStorage, so only the nodes related to a network generation hash is loaded and stored leaving the other nodes untouched.

**Comment by coiki** [comment]
For point #1 mentioned in the previous comment by @fboucquez 

User Story: “As a node owner, I want my edited files to remain untouched unless absolutely necessary when working with profiles or any other object that could force a re-write of the files, so I can continue to have my stored preferences or changes I have made on those files.”

Acceptance Criteria: 
- As a node owner creating a new profile, I don’t want to lose any configuration I have changed in my node
- As a node owner, I don’t want th files NodeService.ts and NodeModelStorage to be automatically overriden unless absolutely necessary.

For Point #2 

It will be tackled on task #752 .

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
