### ISSUE TITLE
Login Screen. Naming issue

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1416]
![image](https://user-images.githubusercontent.com/33131259/114159721-c0f8ac80-992e-11eb-8627-a5c0645ed25d.png)

> Login to your Symbol *account* 

should be 

> Login to your Symbol *profile*

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
@bassemmagdy on spring-fixes branch I got still "account" instead of "profile":

![image](https://user-images.githubusercontent.com/17684281/122104140-a30c6400-ce17-11eb-94ed-ad9d57f59cc3.png)

**Comment by cryptoBeliever** [comment]
@bassemmagdy thanks, fixed.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
