### ISSUE TITLE
when you import QR code for a transaction , slow fee changes as slowest 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#1424]
Did a  transaction with slow fees and downloaded from invoice tab, then i imported the QR code , the fees says slowest 
![image](https://user-images.githubusercontent.com/49143210/114542991-38537680-9c76-11eb-874d-5a36c8233757.png)

**Comment by NikolaiB** [comment]
@bassemmagdy I still can reproduce it. While generating an invoice I choose Slow transaction fee. When I do import QR I still can see Slowest fee from UI

![image](https://user-images.githubusercontent.com/11311924/121490684-13ba1780-c9f7-11eb-8a07-69e67422e5ad.png)

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
