### ISSUE TITLE
Open desktop wallet when transactionURI is clicked

### ISSUE THREAD

**Issue by dgarcia360** [nemgrouplimited/symbol-desktop-wallet#1426]
When I click a button linked to a  [Transaction URI](https://github.com/nemtech/NIP/blob/main/NIPs/nip-0002.md) in decentralized app (browser), I'd like the wallet to open  with the transaction defined in the schema pending to be signed.

Motivation: https://github.com/nemtech/NIP/blob/main/NIPs/nip-0002.md#motivation

**Comment by coiki** [comment]
Good idea. Falls under #1425
