### ISSUE TITLE
When making large Multisig edits the text is jumbled. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1429]
![image](https://user-images.githubusercontent.com/10395907/114753994-131e4100-9d26-11eb-8dbd-68e1ead4ed5f.png)

**Comment by jabo38** [comment]
![Uploading image.png…]()

**Comment by jabo38** [comment]
testing on the Mac build 1.0.2

**Comment by jabo38** [comment]
![image](https://user-images.githubusercontent.com/10395907/114754478-9dff3b80-9d26-11eb-8e0b-88cc2b86ead1.png)

**Comment by bassemmagdy** [comment]
Should be fixed in #1457
