### ISSUE TITLE
Fees selector options not ordered

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1430]
Options on fees selector are in strange order in all places except simple transfer form when putting address:

Current result:
![image](https://user-images.githubusercontent.com/17684281/114906600-7db0a900-9e1a-11eb-8d88-c96498b4d2b4.png)

Expected result:
No fee, Slowest, Slow, Average, Fast

**Comment by cryptoBeliever** [comment]
Now it's ordered but there is a lack of consistency comparing to situation when fees amounts are calculated.

![image](https://user-images.githubusercontent.com/17684281/120900528-6a110a00-c635-11eb-828d-99ff7f7e57ce.png)

![image](https://user-images.githubusercontent.com/17684281/120900536-7301db80-c635-11eb-9068-46d0c68851fb.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever would you check that [branch](https://github.com/nemgrouplimited/symbol-desktop-wallet/tree/gh1503-QRCode-scan-issue)? should be ordered correctly there

**Comment by bassemmagdy** [comment]
@cryptoBeliever Should be consisting now on branch `gh1503-QRCode-scan-issue`

**Comment by cryptoBeliever** [comment]
@bassemmagdy now it's ok :+1:

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
