### ISSUE TITLE
Harvesting - Problem when importing harvesting private key on other device - node is not saved

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1431]
Steps:

1. Start harvesting on one device (you have link node, vrf, remote).
2. Try import a private key on another device

Result:

![image](https://user-images.githubusercontent.com/17684281/114907294-37a81500-9e1b-11eb-90f0-1b7be1eef71e.png)

Which is correct. When we fill node we receiving correct status of harvesting:

![image](https://user-images.githubusercontent.com/17684281/114907427-57d7d400-9e1b-11eb-89e7-ad4a218513ba.png)

**But when we now go to other view and go back node is cleared. It shouldn't be.**

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
Fixed in integration branch
