### ISSUE TITLE
Harvesting - Problem when importing harvesting private key from node operator on other device - not valid status

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1432]
Preconditions: I have the private key for account that harvesting directly on node (node operator account) with linked only VRF and Remote account (without node link).

Steps:
1. Import private key for an account above
2. Go to harvesting view
3. You have view as follow on harvesting:

![image](https://user-images.githubusercontent.com/17684281/114907848-ca48b400-9e1b-11eb-9c55-f459dc81d3b0.png)

4. When we try put node manually nothing happens. Only /node/info endpoint is called. Status is not changing..

**Comment by cryptoBeliever** [comment]
Not fixed. When you switch to another view and go back you have to put node again.

**Comment by bassemmagdy** [comment]
@cryptoBeliever this is a seperate [issue](https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1431) and fixed in a different [pr](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1436)

**Comment by cryptoBeliever** [comment]
I see thanks :)

**Comment by NikolaiB** [comment]
@bassemmagdy When I import an account with private key, I can see that the node status is Key Linked instead of Active

![image](https://user-images.githubusercontent.com/11311924/122274617-8e59ca00-cf04-11eb-9f39-53054b67eaa0.png)

![image](https://user-images.githubusercontent.com/11311924/122276106-450a7a00-cf06-11eb-8cb9-d67c69949c6c.png)

**Comment by cryptoBeliever** [comment]
I waited for the integration test to check that -> https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1432#issuecomment-857704821

It doesn't work as it should:
- node URL disappear after switching to another view

Video: https://share.getcloudapp.com/JruDn6NA

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
