### ISSUE TITLE
Harvesting - node not visible on harvesting view after linking keys for multisig transaction

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1433]
Choose node and link keys for multisig account and confirm on cosigners side.
Result:
Keys are linked but in Node Url input node is not presented
![image](https://user-images.githubusercontent.com/17684281/114910832-a3d84800-9e1e-11eb-85ca-e7a33634a835.png)

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
It doesn't work. I checked with 1 of 1 multi-sig.
Video: https://share.getcloudapp.com/geugpzKN

**Comment by cryptoBeliever** [comment]
Fixed in integration.
