### ISSUE TITLE
Failed to create profile (Ledger)

### ISSUE THREAD

**Issue by HauRuck** [nemgrouplimited/symbol-desktop-wallet#1437]
I got the following error trying to create a profile for a ledger account on Ubuntu 18.04.5 installed version linx-amd64-1.0.2.deb

after entering username and passport, hitting "next":

![Screenshot from 2021-04-16 09-11-33](https://user-images.githubusercontent.com/3307460/114980077-3400a680-9e8c-11eb-9798-677c7949f354.png)

**Comment by TriPhan96** [comment]
Hi @HauRuck
It seems that your PC is missing the libstdc++ library. On my side, this issue is solved when I add these commands to the terminal

```
add-apt-repository ppa:ubuntu-toolchain-r/test -y
apt-get update
apt-get install libstdc++6 -y
```

For more information, you can have a look [here](https://askubuntu.com/questions/726539/sudo-apt-get-install-libstdc)

**Comment by HauRuck** [comment]
Hi @TriPhan96 

Thank you for your help, it works perfectly now.
