### ISSUE TITLE
Harvesting screen. The tabs aligment issue

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1441]
**Current behaviour**
Tabs are scrolled with the page
![image](https://user-images.githubusercontent.com/33131259/115350785-35004380-a1be-11eb-8044-53123457f91e.png)

**Expected behaviour**
Tabs are fixed at the top
![image](https://user-images.githubusercontent.com/33131259/115350544-e652a980-a1bd-11eb-926f-689bd6da9d14.png)

**Version**
1.0.2

**Comment by cryptoBeliever** [comment]
Fixed on branch gh1430-fees-selector-ordering

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
