### ISSUE TITLE
Fees selector. Redundant caption

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1443]
**Current behaviour**
Fees selector displays the fee multiplier caption, which has no sense for the regular end user
![image](https://user-images.githubusercontent.com/33131259/115353951-c91fda00-a1c1-11eb-977e-7caa3f837fb7.png)

**Expected behaviour**
Fees selector should not display the fee multiplier caption

**Version**
1.0.2

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
