### ISSUE TITLE
Form items are not aligned

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1445]
**Current behaviour**
Form items are not aligned.
![image](https://user-images.githubusercontent.com/33131259/115356567-7136a280-a1c4-11eb-80f8-97f6920118d5.png)
![image](https://user-images.githubusercontent.com/33131259/115357042-e73b0980-a1c4-11eb-9536-b7549fc9f10c.png)
![image](https://user-images.githubusercontent.com/33131259/115357358-3b45ee00-a1c5-11eb-998f-7b5e6f648afa.png)

**Expected behaviour**
Form items are aligned.

**Version**
1.0.2

**Comment by bassemmagdy** [comment]
fixed

**Comment by cryptoBeliever** [comment]
@bassemmagdy fixed in which branch? I don't see fix in integration branch.

**Comment by coiki** [comment]
@bassemmagdy When you have time, please confirm if this has been fixed and pending merge.

**Comment by bassemmagdy** [comment]
@cryptoBeliever @coiki should be fixed already on integration branch
![Screen Shot 2021-06-10 at 3 20 03 PM](https://user-images.githubusercontent.com/9143194/121532581-c55d4680-c9ff-11eb-8d6e-38fce639142e.png)

**Comment by cryptoBeliever** [comment]
@bassemmagdy checked on integration branch 
Harvesting view (private keys "Not linked" not aligned):

![image](https://user-images.githubusercontent.com/17684281/121802704-0478db00-cc3e-11eb-9020-38859157b98f.png)

Aggregate (supply change) not aligned:

![image](https://user-images.githubusercontent.com/17684281/121802725-27a38a80-cc3e-11eb-96f7-952de0a007c8.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever would you check #1507?

**Comment by cryptoBeliever** [comment]
Ok. I tough it should check on integration branch because of your comment (https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1445#issuecomment-858619496).

On branch gh1446-fix-icons-consistency it's fixed :+1:
