### ISSUE TITLE
Icons size and position are inconsistent

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1446]
**Current behaviour**
Icon sizes and positions are inconsistent.

![image](https://user-images.githubusercontent.com/33131259/115358227-1c942700-a1c6-11eb-8d9c-9e2b23336706.png)
![image](https://user-images.githubusercontent.com/33131259/115357735-a0014880-a1c5-11eb-988b-2028ba7bd70a.png)
![image](https://user-images.githubusercontent.com/33131259/115358544-71d03880-a1c6-11eb-8c7f-dc99197cb55e.png)

**Expected behaviour**
Icon sizes and positions are consistent.

**Version**
1.0.2

**Comment by surekabpm** [comment]
Tested and the issue can be closed
