### ISSUE TITLE
UI improvement in Account Restrictions screen's tables

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1447]
**Current behaviour**
Title, subtitle, tabs, buttons and table are not aligned properly. Redundant scrollbar
![image](https://user-images.githubusercontent.com/33131259/115359717-a09ade80-a1c7-11eb-9d01-d14d61e21935.png)
![image](https://user-images.githubusercontent.com/33131259/115359742-a7295600-a1c7-11eb-9659-e21665d1f28d.png)

**Expected behaviour**
Items aligned properly

**Version**
1.0.2

**Comment by coiki** [comment]
Acceptance Criteria for UI Defect:

- AC1: The styles in the Account Restriction table, labels, etc. should be correct and consistent.

**Comment by cryptoBeliever** [comment]
Fixed in 1.0.4
