### ISSUE TITLE
Settings form style issue

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1448]
**Current behaviour**
Form title and navgation tabs are scrolled with a content
![image](https://user-images.githubusercontent.com/33131259/115360874-b5c43d00-a1c8-11eb-9154-5bfcd6cc3726.png)

Redundant scrollbar
![image](https://user-images.githubusercontent.com/33131259/115361064-e2785480-a1c8-11eb-909e-983ab0dfd954.png)

The modal box "jumps" when navigating through tabs.
![image](https://user-images.githubusercontent.com/33131259/115361667-75b18a00-a1c9-11eb-87ed-70b8eb80093e.png)

**Expected behaviour**
Settings form without mentioned styles issues

**Version**
1.0.2

**Comment by cryptoBeliever** [comment]
@bassemmagdy now I have a scrollbar...

![image](https://user-images.githubusercontent.com/17684281/120900669-616d0380-c636-11eb-956d-3741a2b68b48.png)

![image](https://user-images.githubusercontent.com/17684281/120900673-66ca4e00-c636-11eb-9d6f-af980553dc60.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever [branch](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1509) updated

**Comment by cryptoBeliever** [comment]
@bassemmagdy 
Still problems mentioned in original ticket exits:
- Form title and navigation tabs are scrolled with a content
- Redundant scrollbar

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
