### ISSUE TITLE
Aggregate Bonded transaction details view overlaps cosignature form

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1461]
![image](https://user-images.githubusercontent.com/33131259/116146991-d2400800-a6e7-11eb-80ac-f6379e22269b.png)

**Comment by jabo38** [comment]
Not unlike this issue too https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1429

**Comment by cryptoBeliever** [comment]
Fixed in 1.0.3
