### ISSUE TITLE
Can't use the QR code reader in offline mode because there is a error message covering it 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1472]
When using the offline wallet, there is no easy way to scan QR codes. If a person goes to their profile and tries to scan a QR code, they can't because an error message on the top of the app covers the "Import QR code" button. The error message is about the wallet not being able to connect to nodes.

**Comment by surekabpm** [comment]
Fixed, tested and passed
