### ISSUE TITLE
Bug when displaying QR code in Aggregate Bonded txs

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#1479]
QR code is not shown for the Aggregate Bonded transactions when the number of inner txs = 24
`Uncaught Error: The amount of data is too big to be stored in a QR Code`
![image](https://user-images.githubusercontent.com/33131259/117126430-67f02d00-ada3-11eb-91de-554bafffb1ff.png)

**Comment by coiki** [comment]
Acceptance Criteria for defect:

- AC1: The Cosignature QR code for an Aggregate Bonded transaction should always be shown, regardless of the number of inner txs.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
