### ISSUE TITLE
Cannot create profile using Ledger

### ISSUE THREAD

**Issue by fredrikrab** [nemgrouplimited/symbol-desktop-wallet#1483]
I get the following error when trying to create a profile:

> Failed to create profile, reason: [object Object]

![screenshot_symbol_wallet](https://user-images.githubusercontent.com/69513590/117586451-9742c900-b118-11eb-9a4e-1524af620d0b.png)

**Platform:** Ubuntu 21.04
**Symbol wallet version:** 1.0.2

Using with Ledger Live (v. 2.26.1) and Ledger Nano S (firmware 2.0.0). Both are latest version at time of writing.

**What I did**

1. Fresh install on Ubuntu 21.04
2. Ledger Live unlocked, incl. Symbol app open on Ledger Nano S (optional)
3. Open Symbol Wallet and select "Access Ledger"
4. Complete information as per screenshot. Click "Next"

Same error occurs also without step 2. I included this just in case this is supposed to be required.

**Comment by fredrikrab** [comment]
Solved by using the following adjustments:

- **Close Ledger Live** and **open Symbol app** on Ledger Nano S

**Comment by segfaultxavi** [comment]
The error message should be improved, though...

**Comment by fredrikrab** [comment]
Reopened because error message should be improved.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
