### ISSUE TITLE
Aggregate bonded - Cosigner have to open tx details to check if it has to be signed

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#1488]
Steps:

1. Announce a few aggregates bonded from multisig account with minimum approval 3 (one cosigner)
2. Go to the second cosigner and sign one of the partial transactions.
3. Logout and login because of bug https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1487
4. Go to the transactions list. Now you can see a few partial transactions. One of them is already signed by this cosigner but there is no way to tell which one without opening details.

Expected result: It should be already visible on the list that the account has to sign partial.

**Comment by cryptoBeliever** [comment]
Resolved.

**Comment by surekabpm** [comment]
Tested in Sprint-fixes branch , good to go for the integration branch

**Comment by cryptoBeliever** [comment]
@bassemmagdy @AnthonyLaw there is a small issue. Right after signing tick is not presented. I have to switch to another account and go back and after that tick is presented. It should be right after signing if possible.

Video: https://share.getcloudapp.com/nOuP5znl

**Comment by cryptoBeliever** [comment]
Fixed in integration.
