### ISSUE TITLE
Transaction addresses incorrect in history

### ISSUE THREAD

**Issue by simonm99** [nemgrouplimited/symbol-desktop-wallet#1493]
Apologies if this has already been reported but I am having an issue with the wallet history not showing the correct addresses for transactions (Mac v1.0.2). E.g. clicking the top transaction in the wallet:

<img width="918" alt="Screenshot 2021-05-13 at 12 16 02" src="https://user-images.githubusercontent.com/17701581/118118798-53d0af00-b3e5-11eb-8291-4063b70ff046.png">

Shows the correct transaction but it does not correspond to what is displayed in the wallet "to/from" field:

<img width="1309" alt="Screenshot 2021-05-13 at 12 16 04" src="https://user-images.githubusercontent.com/17701581/118118838-63e88e80-b3e5-11eb-8e06-a2199958ed38.png">

Have an example video below:

https://user-images.githubusercontent.com/17701581/118119528-65ff1d00-b3e6-11eb-9aa9-62be09be0f9c.mov

**Comment by bassemmagdy** [comment]
Hi @simonm99, thanks for reporting. Are you still able to reproduce that issue? also, is there any kind of scenarios you did to get this result?

**Comment by simonm99** [comment]
Hi,

Thanks for the reply. It seems that it was a one off that happened when several transactions were coming through live when the wallet was open. After I closed and came back to it next day the transactions displayed correctly. I haven't tried to reproduce it myself so I don't know if it was a freak occurrence or if it is more general and could be an issue with multiple transactions happening live when the wallet is open.

**Comment by bassemmagdy** [comment]
@simonm99 We couldn't reproduce on our end, might be an internet issue letting the wallet not syncing properly, will close it for now. please reopen if you could reproduce.
