### ISSUE TITLE
Consider making more detailed release notes. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#1501]
So instead of this. 

![image](https://user-images.githubusercontent.com/10395907/119234033-b0288280-baf9-11eb-919a-6b57a447e3ef.png)

Something more like this. 

![image](https://user-images.githubusercontent.com/10395907/119234055-cd5d5100-baf9-11eb-87d6-43ce8e188daf.png)

**Comment by bassemmagdy** [comment]
Hi @jabo38  v1.0.3 release was specified for post-launch opt-in so it only had this change, Looking at other releases apart from v1.0.3  and [v1.0.0](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v1.0.0) you will find all changes, fixes, and additions detailed.

**Comment by jabo38** [comment]
Ahhh okay. Oops. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
