### ISSUE TITLE
 Scanning a QR Code for a Transfer Transaction without Mosaics breaks the Wallet

### ISSUE THREAD

**Issue by aleixmorgadas** [nemgrouplimited/symbol-desktop-wallet#1503]
**Steps to reproduce**
Scan:
![invoice](https://user-images.githubusercontent.com/49761379/119572524-2d325100-bdb3-11eb-8ded-ccfb2a54903a.png)

**Current behavior**
The wallet is unable to proceed

![Screenshot from 2021-05-26 22-00-25](https://user-images.githubusercontent.com/49761379/119723699-06852080-be6e-11eb-82f5-2c823a72ba11.png)

**Expected behavior**
Be able to Scan the QR Code, and the users see that they are asked to send a message to an account without any mosaic.
 
**Affected Version**
0.4.3-13

**Platform details**
 - OS: Android  11
 
**Additional context**
Supporting QR Codes for Transfer Transaction that doesn't include any Mosaic would enable multiple new use cases.

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
