### ISSUE TITLE
Sometimes the balance is not shown on the walletChoose page

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1514]
v.1.0.3

By importing account with mnemonic sometimes I can see on the walletChoose page next to the account address 0 or N/A Balance

![image](https://user-images.githubusercontent.com/11311924/120484758-33d54f80-c3d5-11eb-8949-7e6a8e0f01c0.png)
![image](https://user-images.githubusercontent.com/11311924/120485774-3dab8280-c3d6-11eb-8db6-1215cbd7d1f0.png)

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
