### ISSUE TITLE
Mosaic expiration is shown incorrectly from UI

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1519]
WTR:

1. Create New mosaic with duration 5 min

Result: you can see that Expiration time is shown wrong 23h 36m instead of 5 min and it's not reducing. 
After expiration time (>5m) it's still shown on mosaic and home pages.
 
![image](https://user-images.githubusercontent.com/11311924/121150321-3caaa300-c865-11eb-8cdf-7ad4db38914a.png)

**Comment by AnthonyLaw** [comment]
@NikolaiB I tested on my local, It seems working fine.

![Screenshot 2021-06-08 at 10 36 48 PM](https://user-images.githubusercontent.com/5649156/121206823-5c64ba00-c8ab-11eb-99a7-da7c75f9dde8.png)
![Screenshot 2021-06-08 at 10 41 36 PM](https://user-images.githubusercontent.com/5649156/121206831-5d95e700-c8ab-11eb-8782-5e8f206dfe3f.png)
![Screenshot 2021-06-08 at 10 45 04 PM](https://user-images.githubusercontent.com/5649156/121206840-5f5faa80-c8ab-11eb-83dd-52b5b904b79a.png)

**Comment by NikolaiB** [comment]
fixed
