### ISSUE TITLE
Click on retry is not working on network connection alert.

### ISSUE THREAD

**Issue by AnthonyLaw** [nemgrouplimited/symbol-desktop-wallet#1523]
![Screenshot 2021-06-10 at 3 48 16 PM](https://user-images.githubusercontent.com/5649156/121486023-5bdf3700-ca03-11eb-99f3-ac4d1a359a78.png)

Step:

1. Turn of wifi.
2. log in to the desktop wallet
3. node disconnect alert shows up.
4. turn back on the wifi and connected.
5. click on `Click to retry` nothing happen.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
