### ISSUE TITLE
Depending on the device's locale, amount input doesn't accept decimal comma or dot.

### ISSUE THREAD

**Issue by coiki** [nemgrouplimited/symbol-desktop-wallet#1531]
After testing the latest version, the team found a defect where depending on the locale being used, the amount input rejects the standard decimal comma/point.

For example, in most European countries you would write "1.000,00" and in other countries you would write "1,000.00", both to represent "one thousand".

**Comment by coiki** [comment]
JIRA Ticket: https://nem-software.atlassian.net/browse/WALL1-20

**Comment by cryptoBeliever** [comment]
It applies to branch 'sprint-fixes'. For integration it works correctly.

**Comment by NikolaiB** [comment]
fixed

**Comment by surekabpm** [comment]
This issue in Jira had moved to done status (fixed and tested )so closing this issue 
https://nem-software.atlassian.net/browse/WALL1-20

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
