### ISSUE TITLE
Version number shown is wrong

### ISSUE THREAD

**Issue by coiki** [nemgrouplimited/symbol-desktop-wallet#1532]
Defect description
===

Version shown isn’t the current version: shows 2.6.0 instead of 2.6.1

Expected Result
===

Show the correct current version always (2.6.1 in this case). Perhaps adding a test or some automation to our release workflow would help.

Steps to Reproduce
===

1. Install version 2.6.1
2. Go to Settings > About
3. Shows incorrect version

Affected Versions, OS, Device
===

All OSs, Version 2.6.1

**Comment by coiki** [comment]
JIRA link: https://nem-software.atlassian.net/browse/WALL1-21

**Comment by bassemmagdy** [comment]
Hi @coiki this is related to Nem Nis1 wallet not symbol.
