### ISSUE TITLE
Separate HD Wallets from Private Key wallets

### ISSUE THREAD

**Issue by decentraliser** [nemgrouplimited/symbol-desktop-wallet#221]
Import account page:
- Add a link around "more options are being worked on" to import a private key

Account creation:
- It should be possible to create a profile with a private key

Wallets import
- When using an HD profile, it should not be possible to import a private key
- When using a private key profile, it should not be possible to import a private key nor a wallet

**Comment by NemTechCN** [comment]
![image](https://user-images.githubusercontent.com/45383558/78989637-c29a6380-7b66-11ea-8033-73dfe3133f6e.png)
![image](https://user-images.githubusercontent.com/45383558/78989646-caf29e80-7b66-11ea-87e3-aa58e8fbfcef.png)
![image](https://user-images.githubusercontent.com/45383558/78989660-d1811600-7b66-11ea-90f3-7fc42eeb092f.png)

The entrance and importer pages, and compatible with profile
like this , is ok? or other better methods ？

**Comment by ABCDEFLY** [comment]
<img width="1151" alt="english" src="https://user-images.githubusercontent.com/30104472/79199330-6d609980-7e67-11ea-9749-f0864803fb9a.png">
should need to determine whether the separation interaction is feasible ? @decentraliser @evias @

**Comment by ABCDEFLY** [comment]
<img width="1169" alt="chinese" src="https://user-images.githubusercontent.com/30104472/79199602-cdefd680-7e67-11ea-978f-5cac69b159fb.png">

**Comment by decentraliser** [comment]
We'll need Jabo opinion about that

**Comment by decentraliser** [comment]
>New pages for pravite keys enter should need to determine whether the separation
@ABCDEFLY I'm sorry I'm not sure that I understand the question, could you please reformulate?

**Comment by decentraliser** [comment]
I'm not sure about the "new profile" switch above the form
I like it but I think it will be confusing

![image](https://user-images.githubusercontent.com/36499647/79213011-0c42c100-7e7b-11ea-91cb-870b9ce04f6c.png)

**Comment by ABCDEFLY** [comment]
yes, maybe some thing better

**Comment by evias** [comment]
Why is there a switch about "New Profile"

1. Please apply the proposed screens _as a new form_ (`FormCreatePrivateKeyWallet`) 
2. Use this form _in a new screen_ of the `create-account` page. 
3. Re-use the same form _in a new screen_ of the `import-account` page.
4. Adapt the `FormSubWalletCreation` to only permit: 
    4.1 Create by private key only in case of Private key profile
    4.2 Create child only in case of HD profile.

**Comment by ABCDEFLY** [comment]
![ prototype](https://user-images.githubusercontent.com/30104472/79222115-9134d700-7e89-11ea-8086-86b2d0c59e3e.png)
Make full use of old screens，Wireframes are words that need to be modified

**Comment by ABCDEFLY** [comment]
Remove the creation of private keys, standardize the entry, and unify the import style.
![画板 – 4](https://user-images.githubusercontent.com/30104472/79292574-0c3ad380-7f04-11ea-9a8c-5820b3b902e8.png)

**Comment by jabo38** [comment]
I don't think we need a "create private key" section. Only "import private key". People that have private keys from this way or that way can have a place to import them. They will already be backed up too that way. 

But if anybody is "creating" anything, they should just creating mnemonics. This way the desktop app and mobile app are following the same wallet creation pathway and will be cross-compatible. 

If we allow people to create a private key wallet on desktop, there won't be anyway for them to import that into the mobile app.

**Comment by jabo38** [comment]
If the community requests create private key wallets later, we can look into that. But almost all blockchain wallets have switched to mnemonic only wallets.
