### ISSUE TITLE
Add metadata to the wallet

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#225]
right now there is no metadata functionality in the wallet

**Comment by evias** [comment]
pending mockup / integration flow design

**Comment by NemTechCN** [comment]
There are three types of metadata: accountMetadata, masaicMetadata, and nameSpaceMetadata. 

Metadata as tags can be distributed among the modules of account, masaic, and mamespace, but the meaning of doing so is not obvious. So centralize it in one place for easy management.


The user can create metadata and may accept metadata from various accounts, which I incorporate into a table and want to complete filter with targetaddress.

**The interaction design model is as follows：**
1. Main page and program entry
![1](https://user-images.githubusercontent.com/45383558/79731769-55848c00-8325-11ea-8061-9b13b8521690.png)


2.View the specific data for each metadata by key
![5](https://user-images.githubusercontent.com/45383558/79731685-3685fa00-8325-11ea-9f9e-b0c331544880.png)

3.Metadata operation forms
![2](https://user-images.githubusercontent.com/45383558/79731753-4dc4e780-8325-11ea-9840-41708a354115.png)

![3](https://user-images.githubusercontent.com/45383558/79731758-50274180-8325-11ea-992e-5e00c99c03c6.png)

![4](https://user-images.githubusercontent.com/45383558/79731763-52899b80-8325-11ea-9901-23726ed30f78.png)

look forward to more coments.
thank you

**Comment by bassemmagdy** [comment]
Thanks, @jabo38 for reporting this, Note that the latest [release](https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5) has metadata for Account / Mosaic / Namespace.
