### ISSUE TITLE
add account restrictions

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#226]
Expected Behaviour

Add a Restrictions screen to manage Account Restrictions and Mosaic Restrictions. The components defined to manage restrictions can be re-used in the Accounts module and Mosaics module accordingly.

The restrictions module should provide with a list of active restrictions with their details.

There should also be a component for account restriction creation and one component for mosaic restriction creation.

**Actionable Items**
- Implement component AccountRestrictionTransactionForm
- Implement component MosaicRestrictionTransactionForm
- Implement component AccountRestrictionList
- Implement component MosaicRestrictionList

**Comment by evias** [comment]
pending mockup / integration flow design

**Comment by NemTechCN** [comment]
Masaic Restriction and Account Restrion is two completely different part.
Here will show Masaic Restriction model of interaction design as follows, hope receive some better optimization opinion. 

The role in the product for the management of their own Mosaic Restriction(an account of the masaicRetriction of passive marked will not be shown here), create and update globalRestrion, addresRestricion, referrenceMasaicID. And  fusion the create and update form in one, to reduce the complexity of the interaction.

**model of interaction design as follows:**
1.The entrance is located under the main navigation of masaic. The main page shows the overall situation of yourself masaicrestriction, shown like the form item. 
![masaicrestriction -1](https://user-images.githubusercontent.com/45383558/79714580-e5b1d980-8303-11ea-9a5e-e621a1a53542.png)

2.Displays the addresses associated with each global retriction
![masaicRestrition-2](https://user-images.githubusercontent.com/45383558/79714787-6ffa3d80-8304-11ea-859a-c962f5be3c72.png)

3. Set and update globalRectristion forms, addressesRestriction forms, renferenceRestriction by MasaicID forms
![马赛克限制](https://user-images.githubusercontent.com/45383558/79714937-d5e6c500-8304-11ea-8e99-7fdba91a992c.png)

![马赛克限制 – 3](https://user-images.githubusercontent.com/45383558/79714954-e4cd7780-8304-11ea-91a0-eed016ab0af8.png)

![马赛克限制 – 4](https://user-images.githubusercontent.com/45383558/79714963-e9922b80-8304-11ea-8cb8-3985950f02a7.png)

Better program entry, better integration with the original program, or more friendly interaction logic，etc.
Looking forward to your comments.
Thank you

**Comment by NemTechCN** [comment]
Here will show **Account Restriction** model of interaction design as follows, hope receive some better optimization opinion.

**model of interaction design as follows:**
1.The entrance is located under the main navigation of masaic. The main page shows the overall situation of yourself Account_Restriction, shown like the form item.
![A RT](https://user-images.githubusercontent.com/45383558/79722733-2c5cff00-8317-11ea-85bd-6e5f908f5537.png)

2.Displays the addresses associated with each AccountRetriction
![A RT1](https://user-images.githubusercontent.com/45383558/79722872-6af2b980-8317-11ea-9df0-7fe4cdf54806.png)

3.Addition or delete accountAddressRestrion form, accountMasaicRestricion form, accountNamespaceRestriction form
![账户限制-地址限制](https://user-images.githubusercontent.com/45383558/79723129-d472c800-8317-11ea-83c2-7951b62564fc.png)
![账户限制-masaic](https://user-images.githubusercontent.com/45383558/79723139-d76db880-8317-11ea-8dfa-8b264bf1330b.png)
![账户限制-操作](https://user-images.githubusercontent.com/45383558/79723158-dccb0300-8317-11ea-8c2c-c14d929f5c4b.png)


Looking forward to your comments.
Thank you

**Comment by yilmazbahadir** [comment]
already implemented
