### ISSUE TITLE
Slowest fee doesn't send the transaction

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#241]
When sending a transaction using the slowest fee setting (0.005 XYM) does not actually send the transaction. It says "Transaction announced successfully." but nothing happens. Also filling an amount of XYM that is larger than the amount in the wallet gives "Transaction announced successfully." when using the slowest fee setting (also not sending the transaction)

**Comment by evias** [comment]
This is probably that the transaction never gets accepted by any node.

Have you check unconfirmed transactions ?

**Comment by meyns** [comment]
No, it never gets in unconfirmed transactions. 
Is this normal behavior? Should there not be any warning about this?

**Comment by decentraliser** [comment]
@evias @fboucquez maybe we could do a system to check if a successfully announced transaction has been included in the unconfirmed transaction, and if not, somehow tell the user it was not included?

I like how Metamask is handling this:
A transaction you just sent will stay in a kind of staged state until it has been included in a block. While the transaction has not been included, you are given the option to re-send it with an increased gas cost in 2 clicks.

According to the feedback we had in the Slack, it seems to be a very common question, and such a feature would make sense IMO

**Comment by jabo38** [comment]
There should be a check to see if the tx is in unconfirmed on nodes. If not, then a message pops up and says "tx failed, please use a higher fee" or "tx failed, balance not enough" and so on. Something along those lines. If the tx is unconfirmed by the network, it is okay to proceed to dashboard and show the tx pending there and awaiting to be included in a block. 

As for resending a tx the second time when the first is pending, I'm not sure if that is possible on Catapult. What can happen is the 2nd tx with the high fee gets in the next block but the first tx is still in the memory pool as unconfirmed. Later on an unselfish node processing txs with low or no fees includes the first tx in a block. Now they have both been sent. 

Once the first tx is sent, the only thing a person can safely do is wait for it to time out or hope a node picks it up that accepts low fee or no fee txs.

**Comment by decentraliser** [comment]
related thread about resending the tx a second time: https://nem2.slack.com/archives/CEZKUE4KB/p1587089958051200

**Comment by evias** [comment]
> There should be a check to see if the tx is in unconfirmed on nodes. If not, then a message pops up and says "tx failed, please use a higher fee" or "tx failed, balance not enough" and so on.

An **unconfirmed** transaction is always a _valid_ transaction. The fee that is attached **may be fine for one node** but not for another node. This adds complexity in how (and _when_) to notify the end-user about the reason for the transaction to stay unconfirmed.

- It is probably good to revive this issue with REST now providing **fee estimations**. 
- In parallel, adding better status notification for the end-user would mitigate this issue. While a transaction is unconfirmed, some checks could be done to determine the _nature of the waiting period_.

To assess _which inclusion strategy_ is used by a node is difficult as of now. It is a per-node property that can be changed for any node restart. More discussion to happen.

**Comment by myxmaster** [comment]
I don't understand why this was closed. The warning "Please note that the minimal fee multiplier for the currently selected node is 100" is not understandable for me (and won't be for average users) and also the problem still exists: If you selected a too small fee (slowest in this case) the transaction seems to be sent but is never processed.

**Comment by segfaultxavi** [comment]
The documentation site also needs to be improved in this regard. See https://github.com/nemtech/symbol-docs/issues/489.
