### ISSUE TITLE
Expired namespaces when showing old Transactions

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-desktop-wallet#279]
One issue we need to consider is that when showing old transactions, the aliases could have been expired. The transaction details may need to dig into the block's receipts in order to know the right divisibility and alias names (unsure if this is possible though, maybe the namespace info is really gone?)

**Comment by evias** [comment]
I confirm @fboucquez the alias _resolution_ will hold information about said mosaic (Probably only the ID, and therefor will require other call to get properties..)

**Comment by fboucquez** [comment]
Right now the wallet is not showing old transactions, so the impact of this issue should not be that big but we should definitely have this in mind.

**Comment by bassemmagdy** [comment]
@fboucquez  @evias How can I reproduce this? knowing that the minimum duration for creating any namespace is 30 days.
