### ISSUE TITLE
The creation fee for creating mosaic should be shown to the accounts

### ISSUE THREAD

**Issue by Alicely** [nemgrouplimited/symbol-desktop-wallet#357]
To create a mosaic, accounts have to pay a fee in addition to the transaction fee.The fees will be deducted from the account’s balance after the announcement of a valid MosaicDefinitionTransaction.However, the creation fee is not shown in the creation process and transaction details.（relate#356）

**Comment by cryptoBeliever** [comment]
Estimated rental fee is presented.
