### ISSUE TITLE
transactions have the wrong sender address  v0.10.1

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#402]
![symbol-desk-v0 10 1](https://user-images.githubusercontent.com/46584115/83440251-e8e0cf00-a444-11ea-8c18-d65c65178577.png)
![6B1202A528D649D05D186C0C10878982157130B3B5B51DE88906899B12FB2B2C](https://user-images.githubusercontent.com/46584115/83440262-ee3e1980-a444-11ea-8618-7eb655a21290.png)

**Comment by vincent-lee90** [comment]
Can you describe it in more detail? Let's follow your steps to reproduce this problem

**Comment by garm01** [comment]
I spammed some addresses with transactions(bot). I noticed that the addresses of the sender / receiver in the dashboard sometimes did not match. It is displayed correctly in the transaction details and in Explorer.
This applies to transactions by the bot as well as normal transactions that took place at a different time.
I have sent both XYM and other mosaics(with different divisibility).

**Comment by evias** [comment]
The wallet is probably using the signer field to identify the sender and in cases of multisig, this could be wrong.

To be fixed.

**Comment by evias** [comment]
related to #482 and fixed with #483 to be merged soon :+1:

Thank you for the report @garm01, I will ping back when a release includes this fix :+1:

**Comment by cryptoBeliever** [comment]
@garm01 it should be fixed. Please verify and let me know if the problem still exists.
