### ISSUE TITLE
Improve the prompt text of the detail page in the multi-signature verification process

### ISSUE THREAD

**Issue by Alicely** [nemgrouplimited/symbol-desktop-wallet#410]
When all co-signers of a multi-signature transaction have signed off, the prompt text on the detail page should be changed.

<img width="764" alt="图片5" src="https://user-images.githubusercontent.com/47626403/84035351-2ce84c80-a9ce-11ea-8ffb-d555b30f0210.png">

**Comment by vincent-lee90** [comment]
The prompt text will be hidden when all co-signers of a multi-signature transaction have signed .

**Comment by fullcircle23** [comment]
> The prompt text will be hidden when all co-signers of a multi-signature transaction have signed .

@vincent-lee90 Instead of hiding the prompt text, might be better to change it to something like "Received required co-signatories".
