### ISSUE TITLE
csv-export for the desktop-wallet

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#416]
The desktop-wallet should contain a csv export for transactions and harvesting. This also has something to do with usability.
We should give the ordinary user the possibility to retrieve and store all transactions of his account without much effort and without being dependent on anyone else.

**Comment by garm01** [comment]
We should give ordinary users the ability to access all of their account transactions with little effort and without being dependent on someone else. And then, relatively easy to save.

**Comment by garm01** [comment]
We should give the ordinary user the possibility to retrieve and store all transactions of his account without much effort and without being dependent on anyone else.

**Comment by jabo38** [comment]
I agree that this is a great feature to have. I think it should be located in Settings. 

This is also something we could add to the explorer. One or the other is important.
