### ISSUE TITLE
“The profile's network is different from the network of the connected node...” shouldn't be shown

### ISSUE THREAD

**Issue by vincent-lee90** [nemgrouplimited/symbol-desktop-wallet#424]
![image](https://user-images.githubusercontent.com/10797419/85240705-a6bb1400-b46b-11ea-964f-b573d7365b60.png)
I am pretty sure this profile belongs to this network of the node !
what I did is that  i toggled the node to a different network node , but when i toggled back, i got this error tip.

**Comment by vincent-lee90** [comment]
I found the Root cause of the problem is that this profile's generation which is storaged in LocalStorage has been set empty
![image](https://user-images.githubusercontent.com/10797419/85258280-cb2de500-b499-11ea-8c7f-d4107af240f0.png).

**Comment by evias** [comment]
Related to #306
