### ISSUE TITLE
Creating a Mosaic should have a minimum duration when the unlimited duration flag is not selected.

### ISSUE THREAD

**Issue by David0817** [nemgrouplimited/symbol-desktop-wallet#429]
<img width="715" alt="mosaic_ duration_must_be_ minimum" src="https://user-images.githubusercontent.com/18167466/85270825-79428a80-b4ac-11ea-9175-6124e6e4be76.png">

**Comment by David0817** [comment]
Creating a mosaic if the duration is too short, i don't think it makes sense. but i’m not sure what minimum duration is an acceptable one. @evias

**Comment by vincent-lee90** [comment]
I think the minimum value is 1(block), and 0 represents Infinity

**Comment by fullcircle23** [comment]
@David0817 If duration is 0 then instead of `Estimated Period of Validity`, show `Estimated Period of Validity unlimited`
