### ISSUE TITLE
Transfer form. Entered data is cleared after the "New transaction confirmed" popup

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#438]
**Current behavior**
Form is cleared 2 times:
1. After the "New unconfirmed transaction" popup appears
2. After the "New transaction confirmed" popup appears

**Expected behavior**
The form must be cleared once after the transaction announcement

**Comment by vincent-lee90** [comment]
good issue!

**Comment by evias** [comment]
Possible origin: https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/views/forms/FormTransactionBase/FormTransactionBase.ts#L159

**Comment by bassemmagdy** [comment]
@evias  #85

**Comment by OlegMakarenko** [comment]
Still have the issue. The form is cleared after the transaction is confirmed, but should be cleared after the transaction is announced.  v0.13.1
