### ISSUE TITLE
error is cosignatures that have cosigned

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#445]
I made a couple of multisig accounts. 

I then went to confirm the contracts with the cosigners. In both cases I used the same cosigners. 

When click through the pending txs to review the data, I saw this. 

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/10395907/86057902-98e62f80-ba25-11ea-89d2-5cf68540fb50.png">

For some reason, it was repeating that the one account had signed so many times, but in fact it had not.

**Comment by vincent-lee90** [comment]
thanks your report  @jabo38 , i will check it !

**Comment by bassemmagdy** [comment]
thanks, @jabo38 for reporting that issue. It's not reproducible anymore, already solved
