### ISSUE TITLE
Review dependencies/devDependencies and peerDependencies

### ISSUE THREAD

**Issue by evias** [nemgrouplimited/symbol-desktop-wallet#458]
There is some `devDependencies` that should be moved over to `dependencies` (e.g. `symbol-qr-library` and `symbol-hd-wallets`).

This could possibly fix some of the issues arising when using the software on Linux OS.

**Comment by yilmazbahadir** [comment]
Reviewed the dependencies over time, noticed that moving symbol-qr-library from devDependencies to dependencies caused other issues during the release process with electron-builder.
