### ISSUE TITLE
Unconfirmed transactions from other child accounts visible in other accounts in same wallet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#460]
Steps to reproduce:

1. Create two accounts in the same wallet.
2. Switch to account 1 dashboard and send coins from the faucet to account 2.
3. Unconfirmed transaction from account 2 will be presented on account 1 dashboard. After confirmation, it still stays there.
4. When I switch to account 2 and back to account 1 dashboard transaction is not presented.

**Comment by evias** [comment]
Thank you for the report! 

There is probably some residual information that needs to be cleared. We will fix asap!

**Comment by evias** [comment]
Confirmed residual information about **transactions websocket listeners**. Seems when SET_CURRENT_ACCOUNT is called, not **all** subscriptions are being closed/terminated correctly.
