### ISSUE TITLE
Multisignature - added cosignature replaced when adding next one

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#478]
Steps to reproduce:

1. Go to multisig conversion view
2. Add first co-signer (for example, TDDDMCSA2MZCEQTELPJKTU4VXVEH7PCIRFA2XZQ)
3. Add the second co-signer (for example, TC4WXCNRLDXNWVLP4QRTWNLJFDNQNWU3WV4EPWQ)

Result: The first co-signer is replaced by the second one.
Expected result: Two co-signers added.

**Comment by cryptoBeliever** [comment]
I can see that it's fixed on bugfix-multisig_form branch

**Comment by evias** [comment]
This bugfix should now be fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/tree/main

Thank you @cryptoBeliever :v:
