### ISSUE TITLE
Desktop Wallet on Ubuntu 18.04.4 LTS display nothing.

### ISSUE THREAD

**Issue by reyesmarkfrancis** [nemgrouplimited/symbol-desktop-wallet#479]
Hi 

I try to install v0.12: Builds for 0.9.6.3 Testnet Compatibility on my  Ubuntu 18.04.4 LTS installation is sucessfull but after install i cant see anythin all blank page.

Thanks

**Comment by cryptoBeliever** [comment]
I think it may be duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/457

**Comment by evias** [comment]
confirmed, duplicate of #457 :+1: 

Nevertheless, thank you for the report @reyesmarkfrancis!
