### ISSUE TITLE
Adding Russian translation (symbol-desktop-wallet)

### ISSUE THREAD

**Issue by klimgeran** [nemgrouplimited/symbol-desktop-wallet#491]
I will add Russian translation for symbol-desktop-wallet

**Comment by klimgeran** [comment]
@dgarcia360

**Comment by cryptoBeliever** [comment]
@klimgeran if you consider adding Russian translation you can create a pull request.
Language files are here https://github.com/nemgrouplimited/symbol-desktop-wallet/tree/main/src/language

**Comment by cryptoBeliever** [comment]
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1478
