### ISSUE TITLE
When creating profile, "Verify Mnemonic Phrase" step shouldn't be skipped

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#492]
As per our discussion with @evias, we need to make sure that the user has a backup of his mnemonic passphrase. So to force the user to have a backup, the user shouldn't be able to skip the "Verify Mnemonic Phrase" step when creating a profile. Therefore the "Skip" button in the image below needs to be removed.

![image](https://user-images.githubusercontent.com/6256269/89890470-59396880-dbcb-11ea-969c-8d6071d28d90.png)

**Comment by jabo38** [comment]
Yes, for the mainnet release, it shouldn't be skipped, but for a testnet release, it is a really big pain to go through verification each time, so for a temporary status, I think it is okay to have it there to make testing easier.

**Comment by NikolaiB** [comment]
fixed.
