### ISSUE TITLE
Owned namespaces - not all namespace and subnamespaces visible

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#497]
Wallet: v0.12.1
Node: http://api-01.eu-central-1.096x.symboldev.network:3000

1. Create wallet and send funds to Seed Account.
2. Add an child account (w1). Send funds to child wallet (w1).
3. Create root namespace (nn1) for Seed account.
4. Create root namespace (nn2) for child wallet (w1).

For now owned namespaces shows correctly. For seed wallet nn1 and for child wallet nn2. 

5. Create sub namespace (nn2.snn1) for child wallet (w1). Created sub namespace is not visible for child walled owned namespaces (only nn2 is visible).
6. Create sub namespace (nn2.snn2) for child wallet (w1). It causes that owned namespace show only nn2.snn2 ...

Conclusion: Presenting owned namespaces is buggy. Sometimes from no reason root namespaces or some sub namespaces are not presented. Maybe it's related with having two or more wallets in profile.

![image](https://user-images.githubusercontent.com/17684281/91657249-e16ea780-eabf-11ea-960d-0d5343897005.png)

This bug causes not all owned namespaces are visible when we linking mosaic/address or creating new subnamespace (parent selectbox)

**Comment by jabo38** [comment]
I have had this same problem while testing. 

For instance, I make a root namespace. Then make a subnamespace. Now can not see the root namespace but can only see the subnamespace.

**Comment by segfaultxavi** [comment]
Same thing here. This is pretty serious as the namespace page becomes unusable.
