### ISSUE TITLE
Need a way to make complex aggregate txs. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#505]
something like this 

![image](https://user-images.githubusercontent.com/10395907/91991199-3a288500-ecf8-11ea-9f45-3ddd61a5afd2.png)

or even better like this 

![image](https://user-images.githubusercontent.com/10395907/91991248-4876a100-ecf8-11ea-8540-83f6112a8335.png)

**Comment by evias** [comment]
linked to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/514

**Comment by bassemmagdy** [comment]
related to #514
