### ISSUE TITLE
When creating the delegated account, no information is displayed if the NODE_URL was entered incorrectly or not at all

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#511]
When creating the delegated account, "The NODE_URL field is required" should appear if the NODE_URL field has not been filled out.
Even if the NODE_URL was entered incorrectly, an error message should appear.

**Comment by cryptoBeliever** [comment]
@garm01 harvesting was rebuilded. Please verify if it's fixed. If not please reopen or create seperate bug.
