### ISSUE TITLE
Add custom aggregate transaction creation

### ISSUE THREAD

**Issue by evias** [nemgrouplimited/symbol-desktop-wallet#514]
A user should be able to create custom aggregate transactions.

A mockup was created for this already and will be added here.

**Comment by evias** [comment]
More details linked in #505

**Comment by bassemmagdy** [comment]
Thanks, @evias  for reporting this, Note that the latest release has custom aggregate transactions included, currently support 3 types of inner transactions: Transfer / MosaicDefination / NamespaceRegistration. linked to #

**Comment by bassemmagdy** [comment]
Thanks, @evias  for reporting this, Note that the latest release has custom aggregate transactions included, currently support 3 types of inner transactions: Transfer / MosaicDefination / NamespaceRegistration.
