### ISSUE TITLE
Error in the user interface 0.13.1 - enter a mnemonic passphrase

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#522]
![Screenshot from 2020-09-30 20-34-52](https://user-images.githubusercontent.com/46584115/94727218-ae3d6380-035e-11eb-92a8-cdc2701e21e0.png)

**Comment by cryptoBeliever** [comment]
- "Return to password settings" don't fit button
- Copy button is expected here?

**Comment by yilmazbahadir** [comment]
Yes, already addressed with this pr => https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/521

![Screenshot 2020-09-30 at 21 50 20](https://user-images.githubusercontent.com/6256269/94738246-0d06db00-0367-11eb-8231-aed5fce433d8.png)
