### ISSUE TITLE
Harvesting wizard not working

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#523]
The harvesting wizard is not working for me on 0.13.1
Steps to reproduce:
- Show wizard
- (account link) Enter password -> create
- (Node selection) Enter node_url (I tried a few) and Fee selection (I tried fastest and recommended) -> next
- (confirmation) Enter password -> next

After this I'm back at the dashboard screen and nothing has changed. No transaction eather.
Also if I start the wizard again I'm getting the same screens.

**Comment by cryptoBeliever** [comment]
I was able to reproduce same scenario (debian package).

Also on confirmation step I have:

![image](https://user-images.githubusercontent.com/17684281/94796244-c9e84e80-03de-11eb-8928-68aebfc1b2f7.png)

"You can see the transaction(s) details displayed below." - but no transaction details are presented.

**Comment by jabo38** [comment]
I also tried to use the harvesting wizard and can see no tx in my dashboard, nor on an explorer.

**Comment by fboucquez** [comment]
Chrome's Dev tool report that the PersistentDelegationRequestMessage is incorrect. The VRF public key is missing. 

https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/views/forms/FormPersistentDelegationRequestTransaction/FormPersistentDelegationRequestTransactionTs.ts#L108

This VRF key is empty.  Also, the message expects the remote account Private key, not the public key. 

I believe Wallet needs to generate 2 accounts, the Remote Account and the VRF Account/Key.

My question, does VRF need to be linked? Should we link the VRF key to the Remote Account or to the Local Account? We should add a VrfKeyLinkTransaction to that list of transactions.

**Comment by fboucquez** [comment]
There are several problems with Wallet's harvesting setup feature in general. 

1. [VRF](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/views/forms/FormPersistentDelegationRequestTransaction/FormPersistentDelegationRequestTransactionTs.ts#L108) provided is always empty. 
2. `FormPersistentDelegationRequestTransaction` form populates **public** keys when remote and vrf **private** keys should we provided.
3. VRF private key is not stored in the profile.
4. There is no check validating that the locally stored remote/vrf private key matches what the blockchain stored in `AccountInfo.supplementalPublicKeys`
5. There should be a page, probably next to Account Details showing the currently linked accounts (vrf, remote, node and votings). This page could validate that the profile stored private keys are correct. It could also allow the user to unlink if there is a key mismatch between the local and blockchain stored data. 
6. There is a `AccountHarvestingPage` and `AccountAction` but not used and [commented out](https://github.com/nemgrouplimited/symbol-desktop-wallet/blob/main/src/router/routes.ts#L303)?
7. Missing `VrfKeyLinkTransaction` and `NodeKeyLinkTransaction` transaction views
8. In the wizard, when changing the "From" to a multisig account, the generated remote account is not changed. It's using the simple account remote key (`encRemoteAccountPrivateKey`). The signer selector should change the set of VRF and remote account used.
9. I'm not sure how the Mnemonic can restore the remote private key (and VRF private key when added). Should it be testing that the restored private key is the one from `AccountInfo.supplementalPublicKeys`? How can these keys from multiples accounts be restored?

**Comment by cryptoBeliever** [comment]
@yilmazbahadir have we list of nodes that have rest with `/unlockedaccount` endpoint?

**Comment by yilmazbahadir** [comment]
@cryptoBeliever I think, this is the only one we have at the moment => http://api-01.us-west-2.0.10.0.x.symboldev.network:3000/node/unlockedaccount

**Comment by cryptoBeliever** [comment]
Thank you. Will verify today :+1:

**Comment by cryptoBeliever** [comment]
I was able to start/stop/activate harvesting for a single and multi-sig account. New bugs will be reported as separated issues.
