### ISSUE TITLE
Removing cosignatories not working

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#524]
Removing cosignatories is not working in 0.13.1
Steps to reproduce:
- Make a multisig wallet 3of3 (used fastest fee in version 0.13.0 to get it working)
- Remove the 3 cosignatories in the Multisig screen
- Change Min approval and Min removal to 0
- (Tried fastest fee and recommended fee)
- A funds lock transaction is made but nothing is showing in the other cosignatories

**Comment by cryptoBeliever** [comment]
@meyns you can remove only one cosigner at once.
Should be fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
If not please reopen.
