### ISSUE TITLE
Cosigner removal (multisig modification) - cosign option visible when multisig account choosen

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#528]
Version: v0.13.1

1. Create multisig 3 of 3 (fastest fee because recommended doesn't work - reported in other issue)

M1 - multisig account
C1 - cosigner account 1
C2 - cosigner account 2
C3 - cosigner account 3

2. Init one cosigner (C3) removal from (C1).
3. Switch to multisig account (M1)
4. On transaction list is visible aggregated bounded transaction (cosigner removal) and app is asking for password to sign this transaction (on multisig account) which is invalid. App is asking for signing this transaction also on cosigners which is correct.

Transaction visible on multisig:
![image](https://user-images.githubusercontent.com/17684281/94872056-e5d60980-044b-11eb-8657-dc949b96a19f.png)

And when I'm trying put password and "Confirm" nothing happens.

**Comment by yilmazbahadir** [comment]
@cryptoBeliever  tried to reproduce the issue but no luck. Could you try to reproduce the issue with another transaction and provide a new screenshot containing the account selector components both on the top and the transaction list?

**Comment by cryptoBeliever** [comment]
Accounts:

```
TB5DOH5DEXOCSV556FV4QPYQNVWPOMKT7ZM34EY (multisig)
public key:  88CFEC062FDA5022F57B193A29C0A81C7A410A4363F4D9EF12715009A5480CB0
private key: 555277DE691D38F4228386D7733CB5CE6A4EE0046B92A88A62E29736F5006CD9

TAJD45BAMCUIEO4KPVEV2ZHF45FAJUQGPNBOPUI (cosigner 1)
public key:  AEDA93469076AACB5EBFD11520CB5D07F842E7131CE35EA323F30B34ECD2D90D
private key: 3AC1FCC0438C6107809CBB6ABB1FB245ECC27FF41987EF3552AA100299E25D3C

TDLDI6RSIZWYXXL3FXN5EAROUM5EJD5HCUBSDUY (cosigner 2)
public key:  F81A1C02C2A20437C86AD3654EFC76AC7B39116E30A2DED84BBACB8F2AE060B6
private key: D527305D6A27FF595E159E38056C1A369C502FE96D69E2671008B46B0C363A99

TDOWIYL6FFS3G7I3CDB7QK4U63PDYNWXOQVR4KQ (cosigner 3)
public key:  3482106C80AB008C157D5F809C768354A78D972B4977CA83AFA89BBC933EB263
private key: F92C423036B7BB50949EE2ADCB850C4C3F1FE632EEC774C26A91C14A93C6D34C
```

I initialized transaction (you can import multisig private key and verify):

![initalized](https://user-images.githubusercontent.com/17684281/95101336-502fc800-0732-11eb-9f3f-91a73cb7b190.png)

**Comment by cryptoBeliever** [comment]
Closing,
