### ISSUE TITLE
Scaling issues on import passphrase page

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#533]
There is an odd "copy" button visible. 

And "return to password settings" is too much wordage for a button. 

![image](https://user-images.githubusercontent.com/10395907/94966588-24f37180-04c3-11eb-8fa8-feac2ee72159.png)

**Comment by cryptoBeliever** [comment]
Duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/522

**Comment by cryptoBeliever** [comment]
Closing.
