### ISSUE TITLE
Link to explorer doesn't work

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#534]
When I click on the link to take me to the explorer. 

![image](https://user-images.githubusercontent.com/10395907/94968410-79e4b700-04c6-11eb-9c58-8272e91ea76a.png)

I get a 404 error in the explorer. 

![image](https://user-images.githubusercontent.com/10395907/94968430-8701a600-04c6-11eb-8a32-579acca87ace.png)

**Comment by trestoJP** [comment]
That's a misspelled URL.
wrong: http://explorer-0.10.0.x-01.symboldev.network/account/...
correct: http://explorer-0.10.0.x-01.symboldev.network/accounts/...

Similarly, Hash and Inner Transaction Hash in Details about a transaction
wrong: http://explorer-0.10.0.x-01.symboldev.network/transaction/...
correct: http://explorer-0.10.0.x-01.symboldev.network/transactions/...

**Comment by rg911** [comment]
Fixed
