### ISSUE TITLE
Pop-up windows for editing mosaics are a bit small

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#536]
The Pop-up windows for editing mosaics should be slightly larger. The drop down menu for the fees should be fully visible. There is enough space. The same with "Create an alias" etc..

![Screenshot from 2020-10-03 02-39-25](https://user-images.githubusercontent.com/46584115/94979631-2e60f600-0524-11eb-8a2a-96a8c42104eb.png)

**Comment by cryptoBeliever** [comment]
Looks like duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/526

**Comment by garm01** [comment]
Oh, I didnt saw this. Sry. I will delete the post.
