### ISSUE TITLE
Backup Mnemonic Phrase. Copy mnemonics buttons

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#537]
![image](https://user-images.githubusercontent.com/33131259/95024580-8fa3d900-068c-11eb-8db7-d1f95da11bc3.png)
There are 3 ways to copy mnemonics. **1** and **2** look redundant since **3** is in the backup options section.
I would propose to drop **1** and **2**

**Comment by cryptoBeliever** [comment]
@OlegMakarenko it's fixed.
