### ISSUE TITLE
Text Input component. Right mouse click doesn't invoke the context menu

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#538]
![image](https://user-images.githubusercontent.com/33131259/95026053-283f5680-0697-11eb-872c-e852876eb5ac.png)
There is no possibility to copy and paste text into the text input.

OS: Windows 10

**Comment by yilmazbahadir** [comment]
You are not using browser and this is an Electron app right?

**Comment by OlegMakarenko** [comment]
@yilmazbahadir Yes, an Electron app

**Comment by cryptoBeliever** [comment]
Same on Linux Electron app.

**Comment by cryptoBeliever** [comment]
@bassemmagdy @OlegMakarenko looks like now it's fixed. Closing.
