### ISSUE TITLE
Transfer form. Add dropdown with child account list to recipient field

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#539]
![image](https://user-images.githubusercontent.com/33131259/95026269-ddbed980-0698-11eb-9f47-a2e866ad8bba.png)
Add the ability to select a seed account in the "To" field

**Comment by cryptoBeliever** [comment]
@OlegMakarenko maybe we can use address book here somehow?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever yes since we have a address book dropdown here now, it would be good to add the wallet's account names to the list

**Comment by cryptoBeliever** [comment]
@OlegMakarenko closing this one because you created https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1098
