### ISSUE TITLE
Unable to convert account to multi-signature

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#540]
![image](https://user-images.githubusercontent.com/33131259/95026802-a2260e80-069c-11eb-95bd-dd288d5bd59b.png)
![image](https://user-images.githubusercontent.com/33131259/95026846-ddc0d880-069c-11eb-9566-aa60c5982335.png)
![image](https://user-images.githubusercontent.com/33131259/95026864-f204d580-069c-11eb-94f0-776f03843ab5.png)
![image](https://user-images.githubusercontent.com/33131259/95026884-0cd74a00-069d-11eb-9423-68dc372dd1a3.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko public key is known when there will be outgoing transaction. This address has only incoming transaction.
Is more like bug in explorer because it shows invalid public key for such address ... For sure it's not 000....0000

**Comment by cryptoBeliever** [comment]
I reported bug for explorer: https://github.com/nemgrouplimited/symbol-explorer/issues/663

**Comment by OlegMakarenko** [comment]
When I enter the accounts public keys from the account tab, the wallet doesn't show any warning and announce HASH_LOCK transaction

**Comment by cryptoBeliever** [comment]
To create multisig you need to have public keys of cosigners.
From address you can't query public key if it's not announced to network.

**Comment by yilmazbahadir** [comment]
> @OlegMakarenko public key is known when you do first outgoing transaction. This address has only incoming transaction. From wallet perspective all is IMO OK.
> @bassemmagdy @yilmazbahadir @evias please confirm.
> 
> Is more like bug in explorer because it shows an invalid public key for such an address ... For sure it's not 000....0000

I believe that's correct.

**Comment by bassemmagdy** [comment]
> @OlegMakarenko public key is known when you do first outgoing transaction. This address has only incoming transaction. From wallet perspective all is IMO OK.
> @bassemmagdy @yilmazbahadir @evias please confirm.
> 
> Is more like bug in explorer because it shows an invalid public key for such an address ... For sure it's not 000....0000

Confirmed.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever @yilmazbahadir @bassemmagdy This should work even if the cosignatory candidate accounts don't have any outgoing transaction. I have just double-check it with SDK and it works. 

http://explorer-0.10.0.x-01.symboldev.network/accounts/TDOSSZJVNHGFTDJ3LE7YTB5N4VU353WCLBIGIEI

**Comment by cryptoBeliever** [comment]
@OlegMakarenko in SDK you did it using public keys or addresses? IMO public keys.
If you will use public keys directly in cosigner input you can do this as well from wallet.

You can't calculate public key from address. It's not possible. That's why wallet app must ask network (/accounts/<address>) to get public key from address. If address don't have any outgoing transaction it has no public key known.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever addresses.

Check this: https://docs.symbolplatform.com/symbol-sdk-typescript-javascript/0.21.1/classes/_model_transaction_multisigaccountmodificationtransaction_.multisigaccountmodificationtransaction.html#addressadditions

**Comment by cryptoBeliever** [comment]
I was under the impression that public key is needed to convert. If not I leave it to verify by @bassemmagdy / @yilmazbahadir :)

**Comment by OlegMakarenko** [comment]
@evias @bassemmagdy @yilmazbahadir
So there are 2 bugs I've found:
1. The form doesn't allow you to add cosignatory candidate accounts address (if it doesn't have outgoing transaction)
2. The wallet announce incorrect HASH_LOCK transaction. Should be HASH_LOCK transaction followed by a AGGREGATE_BONDED transaction

**Comment by yilmazbahadir** [comment]
> @evias @bassemmagdy @yilmazbahadir
> So there are 2 bugs I've found:
> 
> 1. The form doesn't allow you to add cosignatory candidate accounts address (if it doesn't have outgoing transaction)
> 2. The wallet announce incorrect HASH_LOCK transaction. Should be HASH_LOCK transaction followed by a AGGREGATE_BONDED transaction

@OlegMakarenko 
1. As I explained in my previous comment, if this verification step is unnecessary then we can omit this step, it is an easy fix.
2. There is a bug already reported with https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/513 (which I'm currently working on) are you referring to the same issue here?

**Comment by cryptoBeliever** [comment]
Fixed.
