### ISSUE TITLE
Absence of the message in Transaction Details

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#541]
Details:
Symbol Wallet v0.13.1
Hash: 5098D9E301D9821897E22FC801E2F9C8F94FCC03FF52BC780B00FAF3331FC9FC

WTR:
1. Open Symbol Wallet v0.13.1
2. Add transaction with any message (for ex: 'Hello there!')
3. When transaction is accepted open Details about a transaction.
Result: you can see the absence of Message 

![1601895573122](https://user-images.githubusercontent.com/11311924/95071908-35f2eb80-072c-11eb-8259-faca93ec920b.jpg)

**Comment by cryptoBeliever** [comment]
@NikolaiB 
1) What wallet are you using exactly? Please use latest one (https://github.com/nemgrouplimited/symbol-desktop-wallet/releases) and please include version of wallet into issue.
2) Please paste transaction hashes to identify transaction (writing from screenshot is not nice).
3) Please describe the scenario. For example I tried on v0.13.1 and message is displayed.

**Comment by NikolaiB** [comment]
@cryptoBeliever please find the edited version above.

**Comment by cryptoBeliever** [comment]
Strange. I did exactly the same and I have message:

![image](https://user-images.githubusercontent.com/17684281/95076083-988abe00-0711-11eb-9e64-2aea15286c7f.png)

Hash: D5ABEC08D183442AC805CB9A3856531B229DCF27E1A6E3581BF247100E31BDB6

**Comment by bassemmagdy** [comment]
@NikolaiB is this happening in latest browser version or in the Electron desktop app?

**Comment by NikolaiB** [comment]
@bassemmagdy I will close the issue, because I built a web version from the main branch instead of release one. I can not reproduce it in a web and desktop app.
