### ISSUE TITLE
You can not change to any node in the network settings

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#542]
Defect Description : Not able to change to different nodes
Steps to reproduce: 
1. once the account is created , navigate to settings
2. click the network settings tab
3. select the node that is listed
4. or copy paste the link in node url
5. it says invalid node 

![image](https://user-images.githubusercontent.com/49143210/95064984-1359d600-071e-11eb-83c8-c5ccb50a3a2b.png)

**Comment by cryptoBeliever** [comment]
Pasted url is invalid. It should end on :3000 for example: http://138.197.177.10:3000

**Comment by surekabpm** [comment]
> Pasted url is invalid. It should end on :3000 for example: http://138.197.177.10:3000

Hi, But I tried to select one from the node list, as it is not selected, I will have to copy and pasted it. The above link is not there in the list.

**Comment by cryptoBeliever** [comment]
- This view is not for switching but for adding new node to list
- If you want add node you should put correct URL so "http://api-01.us-east-1.0.10.0x.symboldev.network:3000" instead "http://api-01.us-east-1.0.10.0x.symboldev.network:3000-API US East 1".
- Name of node shouldn't stuck together with the name. I reported this already here https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/499
- If you want switch between nodes you should use switch node view available then you click TEST_NET in top menu:

![image](https://user-images.githubusercontent.com/17684281/95186988-e8798b80-07ca-11eb-9ab6-b9dfc1a9f1f8.png)

**Comment by evias** [comment]
Thanks @cryptoBeliever for describing :+1:
