### ISSUE TITLE
Explorer link is not working 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#543]
Defect description : Explorer link is broken

Steps to reproduce : 
1. create an account and login to the account 
2. navigate to accounts tab
3.click the link Explorer "open in explorer" under useful links
4.it should directly open in browser (chrome), but it does'nt ,it is asking for app to open

![image](https://user-images.githubusercontent.com/49143210/95066574-338a9480-0720-11eb-861d-1a2a5e356019.png)

**Comment by evias** [comment]
The problem is happening because of previously stored `settings` that hold an explorerUrl.

A settings migration could work.
