### ISSUE TITLE
Hash links from the dashboard are broken

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#544]
Details:
Symbol Wallet v0.13.1

WTR:
1. Open the Symbol Wallet
2. Choose at any hash link
Result: you can observe 'This site can’t be reached'
explorer URL: http://explorer-97x.symboldev.network/
 
![1601892906706](https://user-images.githubusercontent.com/11311924/95068020-7fd8d300-0726-11eb-96cf-b5d3abc72b46.jpg)

**Comment by cryptoBeliever** [comment]
@NikolaiB please give:
- wallet version
- information what URL is open after clicking hash
- what URL you have in configuration as a explorer URL
