### ISSUE TITLE
Invalid transaction date presented

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#545]
Wallet: v0.13.1
http://explorer-0.10.0.x-01.symboldev.network/transactions/5F927F3C5ACA094C7408B55770420EC8A087F262E643667891A642669DD1298A

Transaction 5F927F3C5ACA094C7408B55770420EC8A087F262E643667891A642669DD1298A was done 12:42 UTC+2 time.
In explorer is presented correctly:

![image](https://user-images.githubusercontent.com/17684281/95070579-9d973f80-0708-11eb-9fcd-b34e000db3ae.png)

In desktop is presented as 14:42:

![image](https://user-images.githubusercontent.com/17684281/95070611-aa1b9800-0708-11eb-8072-b086ded1d749.png)

It should be 12:42

**Comment by cryptoBeliever** [comment]
It's because date is presented based on deadline and not send date.

**Comment by cryptoBeliever** [comment]
Fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5

**Comment by myxmaster** [comment]
The fix just displays deadline minus 2 hours, which is wrong, if the deadline was set manually to another date. We should probably show the block date instead (like the block explorer).
