### ISSUE TITLE
transaction_descriptor_16707 & 16963

### ISSUE THREAD

**Issue by meyns** [nemgrouplimited/symbol-desktop-wallet#546]
2 Transactions that do not show what the transaction is:
transaction_descriptor_16707  => VotingKeyLinkTransaction
transaction_descriptor_16963  => VrfKeyLinkTransaction
These transactions are made by symbol-bootstrap

http://explorer-0.10.0.x-01.symboldev.network/accounts/TCCZ6DAUR37RWCCARM3SC3263SSSOMZRYGJNAJY
http://explorer-0.10.0.x-01.symboldev.network/transactions/9C1847075854E66A5CA13170526BD41E5E9AAEE861B93472C1B9674C04E63776
http://explorer-0.10.0.x-01.symboldev.network/transactions/A5D8BE033BA27DCB3233CCA0CEFE5276D0415B12A67406CE3F784C9E3858A03B
![image](https://user-images.githubusercontent.com/6676974/95182974-9c781800-07c5-11eb-9dce-f99045d52fe0.png)

**Comment by evias** [comment]
Thank you for the report, views have not been added yet. :+1:
