### ISSUE TITLE
Symbol Wallet v0.13.1 Balance not shown in purple area

### ISSUE THREAD

**Issue by r3n3x** [nemgrouplimited/symbol-desktop-wallet#547]
Tx D5A0D476D46668FC524ED658718665723764D5E368FCE3D5985B7315D12D74D1
Balance in Transaction list visible. Tx confirmed. Not shown in purple box.
See https://share.getcloudapp.com/5zuwJ8EY Screenshare

**Comment by cryptoBeliever** [comment]
It's on Mac. May be related to system.

**Comment by bassemmagdy** [comment]
@r3n3x  please write down steps for reproduction.

**Comment by r3n3x** [comment]
Sorry not time now to write the steps, I advise to follow the video I posted in the original post. (Getcloudapp link)
The Symbol wallet shows the XYM 6000 balance today, upon firing it up and entering my password to log in. So perhaps a quit & restart of the wallet might have solved the bug earlier, too. 

Essentially, what I did earlier was to create a new account, fetch faucet XYMs and then see them come in, but not show in the purple box.

**Comment by garm01** [comment]
related to that         ...          OS = Ubuntu 20.04.1 LTS
After confirming the sent transaction, the amount in the purple area does not change automatically (under "my accounts" is the same false amount). I have to switch accounts before the correct amount is displayed.


![Balance_mistake](https://user-images.githubusercontent.com/46584115/96365847-d3deb100-1143-11eb-817c-2276ad63534e.png)

**Comment by cryptoBeliever** [comment]
Should work on latest version.
