### ISSUE TITLE
Click on TX hash in transaction view brings 404 error

### ISSUE THREAD

**Issue by r3n3x** [nemgrouplimited/symbol-desktop-wallet#548]
It links to http://explorer-0.10.0.x-01.symboldev.network/transaction/D5A0D476D46668FC524ED658718665723764D5E368FCE3D5985B7315D12D74D1 in my browser. That gives a 404 error. See: https://share.getcloudapp.com/6quPL9KO

**Comment by cryptoBeliever** [comment]
This is duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/534

**Comment by r3n3x** [comment]
OK.  i had not screened through github issues before i reported this bug.

**Comment by evias** [comment]
closed in favor of #534
