### ISSUE TITLE
No SEND TRANSACTION button in the app visible

### ISSUE THREAD

**Issue by r3n3x** [nemgrouplimited/symbol-desktop-wallet#549]
I can't seem to find a button to make a transaction (e.g. send XYM).
See my view: 
![Screenshot 2020-10-06 at 17 37 58](https://user-images.githubusercontent.com/23291787/95185052-cd267480-07fa-11eb-8831-8d0c27401ae6.png)

**Comment by cryptoBeliever** [comment]
It's tab "Transfer" next to "Dashboard".

**Comment by myxmaster** [comment]
I heard this feedback from another user as well. People, who use this wallet for the first time, really have trouble finding this main feature.

Unfortunately I have no idea how to improve this. Any suggestions?

**Comment by cryptoBeliever** [comment]
UI is improved now. Marking for now as an enhancement. 
@OlegMakarenko do you think we need to improve it more?

**Comment by libertyalpha** [comment]
<img width="1333" alt="Screenshot 2021-02-22 at 09 47 56" src="https://user-images.githubusercontent.com/79082229/108647231-113cbc00-74f3-11eb-8c74-3855cc9578a8.png">

OK it looks like this for me now. There's several UI improvements.
Mainly - the TRANSFER button is renamed to SEND alongside with an ICON illustrating sending something out.  Much better now. Thanks @OlegMakarenko and team.

**Comment by r3n3x** [comment]
<img width="1333" alt="Screenshot 2021-02-22 at 09 47 56" src="https://user-images.githubusercontent.com/23291787/108647365-6c6eae80-74f3-11eb-9efc-e311c5165b03.png">

Much better now. I see the "Transfer" is replaced with "Send" alongside an icon illustrating to send something out. 
Thanks @OlegMakarenko and team!

**Comment by OlegMakarenko** [comment]
@cryptoBeliever I think it should be improved more, but it require bigger UI rework. Marking it as **enhancement** makes sense, so we can come back to this issue later
