### ISSUE TITLE
Multisig Account Page - multiple cosignatories removal should be disallowed

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#550]
Wallet app shouldn't allow users to remove multiple cosignatories since only one cosignatory removal is allowed in a transaction.

![Screenshot 2020-10-07 at 09 26 02](https://user-images.githubusercontent.com/6256269/95362432-fbbd5180-08c5-11eb-82a2-d7331b08937b.png)

**Comment by cryptoBeliever** [comment]
@yilmazbahadir it's fixed so I'm closing.
