### ISSUE TITLE
Provided network configured Deadline when creating Transactions

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-desktop-wallet#555]
The SDKs won't be able to create deadlines by default anymore. The clients would need to provide the network configured `EpochAdjustment`. EpochAdjustment used to be hardcoded in the SDK but not anymore. This value can be retrieved via the `RepositoryFactory` like generation hash and network type.

This task is to upgrade the Wallet to the latest TS SDK (alpha for now) and update the way it creates the Deadlines. 

SDK issue and PR

https://github.com/nemtech/symbol-sdk-typescript-javascript/pull/686

https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/681

**Comment by rg911** [comment]
It is a breaking change from Symbol-SDK (next release) affecting the `Deadline.Create()` which requires `epochAdjustment` now. The epochAdjustment value should be retrieved from the network properties. The value is different between networks now. (it used to be hardcoded).

**Comment by cryptoBeliever** [comment]
@yilmazbahadir this is technical. Could you close if done?
