### ISSUE TITLE
Popup not fully visible in Invoice screen

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#557]
In the Invoice screen, hover the mouse over the small link icon at the very bottom of the page. A popup appears, but it is under the "Assets" box so it is not completely visible:

![image](https://user-images.githubusercontent.com/10949043/95783044-5218fe80-0cd1-11eb-8b9f-7be336573c66.png)

Symbol Wallet v0.13.1 for Windows.

**Comment by cryptoBeliever** [comment]
I'm closing it. https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/671 contains one more bug and this one too.
