### ISSUE TITLE
Relationship between Namespaces, Aliases and Links is not obvious

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#560]
Go to Mosaics and click the Pencil icon on an owned mosaic to edit it. A popup appears with two options: Link and Modify Supply.
If you click Link a dialog appears with the title "Create an alias". This is confusing, maybe the option should be "Alias"?

Symbol Wallet v0.13.1 for Windows.

**Comment by cryptoBeliever** [comment]
Just a small clarification. I guess you mean "go to namespaces" instead "go to mosaics" :)

**Comment by segfaultxavi** [comment]
Nope, it's the same behavior in both Mosaics and Namespaces. And I still find it confusing in Wallet 0.13.8.

**Comment by cryptoBeliever** [comment]
Option name changed.
