### ISSUE TITLE
Mosaic supply cannot be Decreased, only Increased

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#562]
Created my own mosaic (transferable, supply mutable but not restrictable) and tried to edit it to decrease its supply.
No matter what I select in the "Supply Change Direction:" box, the "Direction" field in the "Sign a transaction" dialog always says "Increase".
If I execute the transaction, it is indeed increased, not decreased as I selected.

Happens both with Desktop Wallet 12.1 and 13.1 (Windows).

**Comment by JackNEM** [comment]
duplicate of #497

**Comment by yilmazbahadir** [comment]
duplicate of #498
