### ISSUE TITLE
There should not be an option to backup the mnemonic on profiles created without mnemonic

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#565]
If I create an account from a private key and I go to Accounts->Display Mnemonic a nonsensical dialog appears:
"Please, make sure to backup the following 1 words in a safe place." and an almost-empty box for the mnemonic.

**Comment by cryptoBeliever** [comment]
Fixed. Right now you can't create such profile.
