### ISSUE TITLE
Diagnostic console has too many buttons to close it

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#567]
The diagnostic (log) console has 3 buttons that seem to do the exact same thing (dismiss the dialog): Cancel, OK and the X at the top.
This is confusing. It looks like if I press OK I might be performing some action I am not aware of, whereas Cancel is "safe".

**Comment by yilmazbahadir** [comment]
Since UI/UX has been changed with the latest release, we don't show diagnostic console and this issue is not relevant any more.
