### ISSUE TITLE
Need to separate private key wallets and HD wallets. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#597]
This has been discussed in issues #221, #516, #396. I'm not sure why the wallet still allows mixing of private keys and HD child accounts. 

Right now if I make an HD wallet with a passphrase from scratch, I can create child accounts. When I go to create a child account, it gives me the choice to enter a private key or create an account deterministically. There should ONLY be the option for creating an account deterministically. There should NOT be an option for importing a private key at this part. 

On the sign up screen, where a person is given the option to make a phase phrase, restore a passphrase, or login with Ledger, there is also at the bottom a chance for people to create a private key wallet. That is the only place in the wallet IMO where a person should be entering a private key. 

![image](https://user-images.githubusercontent.com/10395907/97339947-2f4e2480-1851-11eb-8409-02e679d19969.png)
When I'm in a wallet that was started by a passphrase and I'm making a child account, there should be no option to choose if I'm going to make the child account deterministically or via private key. It should only be via deterministically.

**Comment by jabo38** [comment]
mixing private keys and deterministic keys in one profile means that when a person backs up their passphrase, any accounts that were added to that profile not with the passphrase are not getting recreated when that passphrase is reimported on a new machine. It seems like common sense but many users don't get how HD wallets work. They think that when they import a private key in that wallet, it is now protected with the passphrase they have. In the past people have then trashed their private keys and only kept their passphrase. Yes.... I know that sounds silly but it has caused lost funds and many complaints before.

**Comment by jabo38** [comment]
When somebody is in a private key wallet that was made via the the intended "import private key" option shown below which is in the create new profile section, there needs to be further discussion. 

![image](https://user-images.githubusercontent.com/10395907/97340693-1bef8900-1852-11eb-9560-180ff5ea1375.png)

The point of discussion is as follows.  Once a person has imported a private key and now they are in their dashboard and go to accounts and create a new account, should the child accounts ONLY come from importing additional private keys, or should they be created from ONLY creating HD child accounts from the original imported private key? 

![Uploading image.png…]()

**Comment by segfaultxavi** [comment]
I, for one, have absolutely no idea what a "High Definition" wallet is, or what is stored in a mnemonic phrase. I have played with the wallet and didn't understand the different "kinds" of accounts there are. That needs some serious documentation work.

**Comment by jabo38** [comment]
Hierarchical Deterministic Wallet (HD Wallet) is a where all the private keys in a private key are derived deterministically from a random set of words which is often in this industry 12-24 words. 

In the start of blockchain, almost everyone managed profiles by creating random private keys. This was problematic as a person had to manage and record and back up lots and lots of private yes. At some point most of the industry moved over to HD wallets. The benefit of an HD wallet is it allows "one key to rule them all" and storing the key as a set of words instead of 64 character hexadecimal as 12 words has a lot less user error writing it down and backing up then 64 characters. 

By mixing a profile with an HD passphrase and a string of characters now means a person needs to back up both separately, but we have no clean and easy way to back up both at the same time, nor have I ever seen any wallet pull that off. It definitely can't be put in a QR code like we are doing now. This leads to people thinking they have backed up accounts and they haven't when the two systems are mixed.

**Comment by cryptoBeliever** [comment]
@jabo38 could you verify current behavior?

**Comment by myxmaster** [comment]
Right now hierarchical deterministic wallets allow to add a custom private key address. As described in this issue, this is not a good idea. Reopen this issue?
