### ISSUE TITLE
Display problems - display overlap

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#621]
check these 2
1: on the dashboard
![ 2020-11-03 11-38-28-770](https://user-images.githubusercontent.com/59822825/97946117-c0327c00-1dcc-11eb-84e6-ff040dfdc0b8.png)

2: on the multisig setting
![ 2020-11-03 11-39-26-527](https://user-images.githubusercontent.com/59822825/97945969-6e89f180-1dcc-11eb-87c9-b85d8a9b01b0.png)

![ 2020-11-03 11-39-36-799](https://user-images.githubusercontent.com/59822825/97945979-72b60f00-1dcc-11eb-96c9-665c56457c81.png)

![ 2020-11-03 12-13-41-735](https://user-images.githubusercontent.com/59822825/97946550-279cfb80-1dce-11eb-8442-ddc358d54fca.png)

**Comment by jabo38** [comment]
I had the same display problem in multisig. 

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/10395907/98173841-6491ec80-1eb9-11eb-8af4-41f65824bef4.png">

**Comment by jabo38** [comment]
I have the same problem with the search field being covered up. 

Before I created a multisig account, it is fine and looks normal. 

But after I create a multisig account, there is another dropdown and not enough space to accommodate it. 

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/10395907/98174225-28ab5700-1eba-11eb-83ac-f2844e0a7c68.png">

**Comment by cryptoBeliever** [comment]
@trestoJP should be fixed now. If yes, please close.

**Comment by cryptoBeliever** [comment]
Closing.
