### ISSUE TITLE
Issuing Mosaic in a Multi-Sig Account

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#622]
Multisig account A(2of2)
┣ Co-signer1
┗ Co-signer2

Co-signer1 sends a transaction to issue a mosaic on Multisig account A, but no signature request is sent to Co-signer2.

**Comment by cryptoBeliever** [comment]
As described in https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/624 you need to switch to multisignature account. Closing and leaving discussionin #624
