### ISSUE TITLE
Failure or non-display of signature request - Transferring from a Multi-Sig Account

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#624]
Multisig account A(3of2)
┣ Co-signer1
┣ Co-signer2
┗ Co-signer3

Co-signer1 sent a transaction from multisig account A, but Co-signer2 and Co-signer3 did not receive the signature request.

Multi-level case

Multisig account A(2of2)
┣ Co-signer1
┗ Co-signer2(Multisig account B(3of2))
　┣ Co-signer3
　┣ Co-signer4
　┗ Co-signer5

Co-signer1 sent a transaction from multisig account A, but Co-signer3, Co-signer4 and Co-signer5 did not receive the signature request.

**Comment by cryptoBeliever** [comment]
Hello @trestoJP 

Just for confirmation. Did you tried to use this switch on cosigner side to switch on multisig and receive notification about new transaction to sign? You should receive transaction cosignature notification when you switch to multisig.
Anyway this UI need to be rethought.

![image](https://user-images.githubusercontent.com/17684281/97952212-e6402800-1d9c-11eb-9a8d-e78ddc4fe990.png)

**Comment by trestoJP** [comment]
I did it
But this is an inconvenience. It's hard to notice the signature request.
Thank you.

**Comment by cryptoBeliever** [comment]
@bassemmagdy 
Can we do something about this? We want to let user know that something is to sign for one of his multisigs. Would be also good to give clear information which account it applies. What you think?

**Comment by bassemmagdy** [comment]
@cryptoBeliever what we could do is we can extend the partial transactions listener to listen over all the multi-sig signers' list of each account in order to show them in the current account but, it would be a bit messy in some cases, for example, the user has 7 or 8 signers receiving multiple partial transactions that need to be signed, in that case, all the txs would be stuffed in transaction list which would be a bit confusing to the user.

**Comment by cryptoBeliever** [comment]
@bassemmagdy, unfortunately, I don't have good idea how to handle this too. Listening to all multi-sig accounts could be confusing as you told. Maybe some UI designer can propose it something. 
In NIS1 wallet there was separate view to check all transactions to sign but I'm not sure if this is good idea too.

**Comment by Peersyst** [comment]
The idea for this version is to extend all partial transactions in the multisig tree to the row and get it signed in the tx modal. Its basically the same case and in the modal we should display all the info explaining the origin of this transaction and the tree for its signature.

**Comment by rg911** [comment]
The search box will be removed anyway (post launched enhancement), perhaps that could be fine for now?

**Comment by cryptoBeliever** [comment]
This should be improved when this fix will be released https://github.com/nemtech/catapult-rest/issues/278

**Comment by cryptoBeliever** [comment]
Partial transactions are now presented for cosigners too. Fixed.
