### ISSUE TITLE
login button font not centered. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#631]
Using a Mac, the font on the login button that says "login" isn't centered. 

<img width="419" alt="image" src="https://user-images.githubusercontent.com/10395907/98128992-39d67280-1e7e-11eb-9d1d-605400b24614.png">

**Comment by garm01** [comment]
the same here:
![Wallet-button](https://user-images.githubusercontent.com/46584115/99185745-2bc10580-274c-11eb-9851-b62dbd5f777f.png)

**Comment by myxmaster** [comment]
Probably duplicate of #813. Both issues have pull requests (#863 and #890) with different solutions...

**Comment by myxmaster** [comment]
@garm01 I created a seperate issue for that (#919) since the cause is not the same.

**Comment by cryptoBeliever** [comment]
@NikolaiB could you check on Mac (login and download buttons)?

**Comment by NikolaiB** [comment]
@cryptoBeliever yes, it's centered (Version: 0.13.8)

**Comment by cryptoBeliever** [comment]
Ok. Closing.
