### ISSUE TITLE
Confirm button on settings change is purple instead of grey. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#632]
On the settings page the "confirm" button is in purple but I haven't changed any settings. 

Normally the "confirm" button would be grey, until I've made a change. Then after making a change it would turn purple. 

Not a big issue at all, just thought I'd mention it. 

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/10395907/98130310-ba49a300-1e7f-11eb-9385-5216d551e738.png">

**Comment by NikolaiB** [comment]
Fixed.
