### ISSUE TITLE
On a desktop wallet it isn't intuitive how to get back to the login screen once logged in.  

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#633]
If I'm in my Dashboard after I've logged in, and then realize I'm in the wrong profile and want to go back to login screen, there isn't an intuitive way to do so. In some apps, this would be done by clicking the "Symbol from NEM" logo in the top left hand corner. 

<img width="257" alt="image" src="https://user-images.githubusercontent.com/10395907/98131794-401a1e00-1e81-11eb-8c80-be14ae53c05b.png">

**Comment by Peersyst** [comment]
The log out button has been removed. It can go inside settings or in the right of settings in the main menu

**Comment by yilmazbahadir** [comment]
Since the logout button is added to the settings page, this issue is fixed.
