### ISSUE TITLE
The private key doesn't show up until the end

### ISSUE THREAD

**Issue by GodTanu** [nemgrouplimited/symbol-desktop-wallet#638]
**Account Information**
Version: 0.13.2

Maximizing the screen doesn't show the last two characters.
![image](https://user-images.githubusercontent.com/20492223/98518274-8375f180-22b2-11eb-9f58-8ca3d49dca75.png)

**Comment by cryptoBeliever** [comment]
Presentation changed for same as for public key (copy button added).
Fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
