### ISSUE TITLE
Node URLs are not displayed in the delegated harvesting of a multisig account

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#649]
Harvesting status is active.
![2020-11-10 08-12-35-539](https://user-images.githubusercontent.com/59822825/98607865-53b7ff80-232d-11eb-8dbe-966782584675.png)

**Comment by cryptoBeliever** [comment]
This should be fixed now. There are some other issues with starting for multisig account but this is another issue.
Please close if fixed.

**Comment by yilmazbahadir** [comment]
Closing it since the latest release should fix it.
