### ISSUE TITLE
"password" typo when activating harvesting

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#650]
when making the transaction to activate harvesting, it says "passwor" instead of "password". 

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/10395907/98618155-30a63500-22c6-11eb-81cd-63dd6637b505.png">

**Comment by cryptoBeliever** [comment]
@jabo38 Could you verify on latest build if it's fixed? For me it's presenting correctly.

**Comment by garm01** [comment]
The current solution is also not optimal. Although there is enough space, you have to scroll to enter the password. This is not obvious at first glance.
The scrollbar is too light and too narrow. I know these may be minor details, but it should be as intuitive as possible to use.

**Comment by cryptoBeliever** [comment]
It's fixed now (http://desktop-build.symboldev.com/) 
Password input is always on the bottom on view and always visible:

![image](https://user-images.githubusercontent.com/17684281/100921455-e4bd6900-34dc-11eb-9097-6be665f1d690.png)

https://share.getcloudapp.com/kpuNmGO1
