### ISSUE TITLE
Scroll bars of the wallet cannot be used optimally

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#658]
It often need several attempts to use the scroll bars in the wallet.

**Comment by yilmazbahadir** [comment]
Can you share more details on this? (list of pages, screenshots etc. )

**Comment by garm01** [comment]
The scroll bars in the wallet are quite narrow. This makes the operation with the touchpad (Notebook) a bit unwieldy.
(e.g. selection of the fee,Dashboard etc.)
When operating the wallet, the user should be able to concentrate on the contents and not on catching the scroll bar.
Perhaps avoiding them whenever possible is enough.
This is my subjective impression, one should also consult the opinion of other users.

**Comment by cryptoBeliever** [comment]
This is how looks like scrollbars on Linux https://share.getcloudapp.com/GGu6kqqK
