### ISSUE TITLE
The term "Expired" will lead to confusion at this point.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#662]
I'm  not sure why "Expired" is displayed when all mosaics of a certain type have been sent form the wallet and the account-balance is 0.
That will lead to confusion. The mosaic is still valid for a while.
If I have sent all the XYM of an account and the status is 0, there is ultimately no such message. 

![expired-3](https://user-images.githubusercontent.com/46584115/98841507-7d197e00-2448-11eb-9437-66629f82fa14.png)

**Comment by cryptoBeliever** [comment]
Still replicable

**Comment by bassemmagdy** [comment]
fixed on latest integration
