### ISSUE TITLE
Unable to stop the delegate harvesting of a multisig account

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#665]
After updating to v0.13.4, delegate harvesting of a multisig account that was active in v0.13.3 cannot be stopped.
Transactions fail to be sent.
"Failure_Aggregate_Missing_Cosignatures"

**Comment by cryptoBeliever** [comment]
Thank you :+1:

**Comment by cryptoBeliever** [comment]
@trestoJP should be fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
Please verify and reopen if not. Harvesting was changed to two steps (linking and activating)
