### ISSUE TITLE
Date display error

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#666]
The date on the dashboard seems to be wrong. It shows 2 hours in the future for users from Japan.

**Comment by cryptoBeliever** [comment]
He @trestoJP. It's duplicate of https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/545.
I will ping devs regarding this issue.
Thank you.

**Comment by cryptoBeliever** [comment]
Fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
