### ISSUE TITLE
Delegated harvesting goes unresponsive.

### ISSUE THREAD

**Issue by GodTanu** [nemgrouplimited/symbol-desktop-wallet#667]
Ver 0.13.4

Delegated harvesting goes unresponsive.

After the aggregate comple, the pristentharvestdelegation will not be issued and will time out.
After that, you cannot operate from the desktop wallet.
If it fails, various unlinks need to be implemented.
and Maybe Delegated harvesting cannot be released in case of an error in the issuance of presistentharvestdelegation too.

**Comment by cryptoBeliever** [comment]
@GodTanu on current version I don't have problem. Could you confirm on your side?

**Comment by yilmazbahadir** [comment]
@GodTanu @cryptoBeliever Is this issue still valid(on 0.13.5)? If not can we close this issue?

**Comment by cryptoBeliever** [comment]
I think we can close. @GodTanu if you will still have any problem please let us know.

**Comment by GodTanu** [comment]
I think it's good because I split the tx into two stages. Thank you very much. Sorry for the delay in reporting.
