### ISSUE TITLE
Display of Harvested Blocks

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#669]
17 or more Harvested Blocks cannot be displayed. It need to add a scroller or something.
It might be useful to have a link from the block number to the explorer.

![ 2020-11-13 23-59-15-083](https://user-images.githubusercontent.com/59822825/99086397-d29e8800-260c-11eb-9faa-9e4783324e72.png)

**Comment by cryptoBeliever** [comment]
Blocks presentation fixed.
@yilmazbahadir can we add link to explorer when clicking on block height?

**Comment by yilmazbahadir** [comment]
This shouldn't be valid anymore (with the latest release)
