### ISSUE TITLE
Format of certain properties of an address

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#670]
The wallet should be easy to understand for the average user. After all, these are the people who use it.
This also applies to the "Importance" of an address. It should be displayed as in the explorer. 
e.g. "0.001352%"

![1Importance](https://user-images.githubusercontent.com/46584115/99153148-0201d300-26a7-11eb-83f0-af6292b3bd70.png)

**Comment by garm01** [comment]
and look at here: 

![2Importance](https://user-images.githubusercontent.com/46584115/99153856-9110ea00-26ab-11eb-9563-9fdd8cd7b232.png)

**Comment by cryptoBeliever** [comment]
Interesting. I guess it depends on localization because I can see:

![image](https://user-images.githubusercontent.com/17684281/99313005-23a5ba80-285f-11eb-9e31-8aad952ff295.png)

**Comment by garm01** [comment]
Not sure, I used " [0.13.4][v0.13.4] - 11-Nov-2020 "

**Comment by garm01** [comment]
The first picture :
#locale 
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
                                       -----
and here:
#locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
![locale-en](https://user-images.githubusercontent.com/46584115/99389292-1cba8e80-28d7-11eb-9b14-7a29c580864a.png)

**Comment by myxmaster** [comment]
In Germany (de_DE.UTF-8) this is correct: 12.345,987654

**Comment by cryptoBeliever** [comment]
Both issues:
- with importance score
- decimal seperator
fixed.
