### ISSUE TITLE
Note not visible with normal window size.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#671]
The note "Copy" should appear to the side or above the button.

![Copy-button2](https://user-images.githubusercontent.com/46584115/99187252-ba865000-2755-11eb-851e-9b74338eb8b5.png)

PS: Scroll bar(Message Field) should only appear when the message exceeds the size of the field and another line is required.

**Comment by garm01** [comment]
the same here, pop up only half visible:
![Pop-up](https://user-images.githubusercontent.com/46584115/99186927-ed2f4900-2753-11eb-8152-539f79fd5b8d.png)

**Comment by cryptoBeliever** [comment]
Same issue on aggregate 

![image](https://user-images.githubusercontent.com/17684281/100729819-8bb0e080-33c9-11eb-9f9d-65339303cdfd.png)

**Comment by cryptoBeliever** [comment]
Fixed in latest live build: http://desktop-build.symboldev.com/
