### ISSUE TITLE
Change request - add sound when sending/receiving transactions

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#678]
In the NIS1 desktop wallet are two sounds played when sending/receiving transactions.
The community is used to it and would be nice to have it also in Symbol wallet.
The suggestion is to allow to turn it on in Settings. Of course, is a low priority for now before lunch but worth implementing it.

Here is a pool on Twitter regarding this change request:
https://twitter.com/mikunnem/status/1327392413120225281?s=21

**Comment by imTheGlitch** [comment]
+1

**Comment by cryptoBeliever** [comment]
Done.
