### ISSUE TITLE
Multisig graph tree view display 

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#689]
Optimize the tree view in account info page to provide more meaningful display

**Comment by cryptoBeliever** [comment]
Current presentation:

![image](https://user-images.githubusercontent.com/17684281/100736488-1c3fee80-33d3-11eb-9165-ee7a8cd058de.png)

I guess it should be more like this:

w4
      \
       w1
     /
w2

**Comment by cryptoBeliever** [comment]
Looks correct now :+1:
