### ISSUE TITLE
 Not all cosigners visible when we have more than 11

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#691]

**Comment by cryptoBeliever** [comment]
Same for aggregate:

![image](https://user-images.githubusercontent.com/17684281/99659395-16f0b480-2a61-11eb-9649-05002eefcf6c.png)

**Comment by cryptoBeliever** [comment]
And screenshot for multisig creation:

![image](https://user-images.githubusercontent.com/17684281/99659438-296aee00-2a61-11eb-9fa2-60abcf7c60a8.png)

**Comment by cryptoBeliever** [comment]
Same when doing transaction:

![image](https://user-images.githubusercontent.com/17684281/100732663-56a68d00-33cd-11eb-9903-5edd91f60d4b.png)

**Comment by cryptoBeliever** [comment]
Fixed in live build :+1: 
Thank you @NikolaiYurchenko
