### ISSUE TITLE
Co-signer account indicated as Multisig in the From field

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#692]
On inactive Transfer page under Multisig account there is co-signer account indicated as Multisig in the From field

Steps to reproduce:
1. Create multisig account 
2. Go to Transfer on Home under Multisig acount 
3. Switch to another co-signer account via upper menu 
4. Switch back to Multisig account

Expected result: In From field on inactive Transfer page the Multisig account is indicated as such
Actual result: The co-signer account is indicated as Multisig in the From field on Inactive Transfer page

**Comment by NikolaiYurchenko** [comment]
can not reproduce

**Comment by cryptoBeliever** [comment]
@Eugenity could you please try reproduce and add more details if possible?

**Comment by Eugenity** [comment]
Although being not so major it is still reproducible - [Video](https://www.loom.com/share/527deecaedd54d35bd1d2f8cf2280067)

**Comment by cryptoBeliever** [comment]
@Eugenity please verify

**Comment by Eugenity** [comment]
Verified
