### ISSUE TITLE
Not all Aliases are displayed(when there are more namespaces)

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#694]
I have created 7 namespaces and linked to address, but alias in the account tab is not displaying all

**Comment by cryptoBeliever** [comment]
![Uploading image.png…]()

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/99876975-03795100-2bfb-11eb-9f20-6640fc65fc98.png)

**Comment by cryptoBeliever** [comment]
Now aliases are presented in multilines :+1: 

![image](https://user-images.githubusercontent.com/17684281/101633496-a1f11900-3a27-11eb-84da-0a915466a531.png)
