### ISSUE TITLE
Address QR code not able to export 

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#696]
Address QR code export option is not there .

**Comment by cryptoBeliever** [comment]
There is button to download QR in https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
![image](https://user-images.githubusercontent.com/17684281/99632918-5a85f700-2a3e-11eb-84d8-804e531cfe91.png)
