### ISSUE TITLE
 Issues on Invoice view

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#698]
There are some small issues on Invoice view:

1) Problem with missing recipient public key.
  A) Go to Invoice view (address is filled by default).
  B) Put random message.
  C) Check encrypted message
Result: Error Invalid recipient public key. When we put again same address into "To" input problem disappers. Probably public key in background is not initialized for default "To" value

2) No way to remove mosaic.
  A) Go to Invoice view (you have to at least one mosaic different than xym)
  B) Click "Add a mosaic" button. Button disappers but still it's visible plus icon. Should be?
Result: There is also no way to move added mosaic. Same issue is on Transfer view.

**Comment by cryptoBeliever** [comment]
It's fixed :+1:
