### ISSUE TITLE
Transaction type selection in aggregates is invisible

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#703]
Invisible
![ 2020-11-19 09-00-30-902](https://user-images.githubusercontent.com/59822825/99603139-0da61e80-2a46-11eb-93f1-e6716106de98.png)

**Comment by cryptoBeliever** [comment]
Something wrong on standalone versions. Confirmed on Linux snap version.

**Comment by cryptoBeliever** [comment]
@bassemmagdy we need to have a standalone build to verify this. Would be possible to build it?

**Comment by cryptoBeliever** [comment]
Fixed in 0.13.6
