### ISSUE TITLE
Missing Node Link Transaction Icon

### ISSUE THREAD

**Issue by fboucquez** [nemgrouplimited/symbol-desktop-wallet#705]
![image](https://user-images.githubusercontent.com/5390558/99611732-f8ec6b00-29f2-11eb-9846-63fac73f1eb6.png)

**Comment by cryptoBeliever** [comment]
@fboucquez you initialized this tx from outside of wallet right? Because from wallet is initialized as aggregate (three links).

**Comment by cryptoBeliever** [comment]
Fixed.
