### ISSUE TITLE
On transaction confirmation pop-up "From" is cosigner instead multisig when sending tx 

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#707]
Steps:

1. Go to cosigner of multisig account.
2. Go to send view and switch to multisig from which you want send
3. Init transaction. On pop-up "From" is a cosigner address instead multisig. 

Probably wallet is taking signer instead account from which coins will be send.

**Comment by bassemmagdy** [comment]
not reproducible

**Comment by cryptoBeliever** [comment]
I'm not able to reproduce now too. Closing.
