### ISSUE TITLE
Bug - Mnuemonics order changed - error message is not appearing 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#710]
While creating an account, via mnemonics , if I change the order, error message need to be displayed ,it is not displaying .screenshot attached 
![image](https://user-images.githubusercontent.com/49143210/99668962-68fefd80-2a94-11eb-9c6b-10659c26f87a.png)
![image](https://user-images.githubusercontent.com/49143210/99668987-71efcf00-2a94-11eb-9192-b89be19e19a8.png)

**Comment by cryptoBeliever** [comment]
@surekabpm please verify

**Comment by surekabpm** [comment]
![image](https://user-images.githubusercontent.com/49143210/101593062-59306480-3a15-11eb-931f-9fdccc980ed8.png)
 Mnuemonic is not correct  - is that the message need to be displayed ? is that the expectation? Also this message is displayed at the last , can this message be displayed when the wrong words are typed.please clarify @cryptoBeliever

**Comment by cryptoBeliever** [comment]
@surekabpm those are questions to @bassemmagdy

**Comment by bassemmagdy** [comment]
@surekabpm @cryptoBeliever  issue is now addressed on word entry not only when mnemonic is full. Please re-check when this [PR](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/795) is merged.

**Comment by surekabpm** [comment]
Tested and it is working now
