### ISSUE TITLE
Bug - Next button not working while importing an account 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#711]
While importing an account , the next button is not working, not able to navigate further
![image](https://user-images.githubusercontent.com/49143210/99669374-f2aecb00-2a94-11eb-85d7-2e3b63f4c7d2.png)

**Comment by bassemmagdy** [comment]
@surekabpm Have you tried to paste/write your backed-up mnemonic and still facing that problem? If yes can you please share your mnemonic?

**Comment by surekabpm** [comment]
@bassemmagdy , i have tried with mneumonic phrase , it is working , previously i have seen qr code import/download apart from mneumonics ,that is why is raised this issue, if this functionality is for only mneumonics import , then i can close this issue.but please confirm from your side

**Comment by bassemmagdy** [comment]
thanks, @surekabpm for reporting. The issue should be resolved in the latest release
