### ISSUE TITLE
Bug - Coins are transferred from co-signer account instead of Multisig

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#712]
Steps to reproduce:

1. Create a couple 'Miltisig account — co-signer' using different profiles (from one browser)
2. Initiate a simple transfer transaction from Multisig account under co-signer
3. Pay attention to coins being subsctracted from co-signer account and not substracted from Multisig

Actual result: Coins are trasfered from co-signer account
Expected result: Coins are transfered from Multisig account

**Comment by bassemmagdy** [comment]
@Eugenity can you please share your Multisig structure for different profiles/accounts?

**Comment by Eugenity** [comment]
@bassemmagdy 

TD5CPJFORQR322VWEFNLVGGA7P2ZQDUQM5NPVIY is Multisig account from which transfer should have been held. TAPFPMXMC7RSPIBNMNSMVU4TZHFQMKVKZPCAIRY is a co-signer account from which the actual transfer was made. TAIBJKGZRY35WL6ALUQ47VOJM7FWPXEVDTBNZEY is the recipient address. 

[Link to a transaction in the block explorer](http://explorer-0.10.0.x-01.symboldev.network/transactions/324AAC8254D513D9CB63EB17B005EDEB656114572C0C394FD4550E90D58DE05C)

It seems to me that the problem is that Multisig account is changed to a co-signer account before sending a transaction which we can see in the transfer confirmation dialog.

**Comment by bassemmagdy** [comment]
Thanks, @Eugenity for reporting that issue. It should be fixed now

**Comment by cryptoBeliever** [comment]
@Eugenity please test and close if all is OK.

**Comment by Eugenity** [comment]
Verified, works as expected now.
