### ISSUE TITLE
Different formats of Address QR in desktop wallet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#714]
In desktop wallet we have:
- paper wallet (where is presented Address QR)
- and account view - there is also Address QR

Address QR on account view has a different format than paper wallet Address QR. 
This should be changed to be consistent with the paper wallet Address QR.

**Comment by yilmazbahadir** [comment]
@cryptoBeliever Can you please test this on http://desktop-build.symboldev.com ? I believe https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/729 has already fixed this.

**Comment by cryptoBeliever** [comment]
@yilmazbahadir yes it works now. I'm closing.
