### ISSUE TITLE
message transfer with the amount set to "0"

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#719]
If you delete the amount and only enter a "0" to send a plain text message, you will get an error message.
With the basic setting "0", this error message does not appear.

![validation](https://user-images.githubusercontent.com/46584115/99802312-c8fab000-2b37-11eb-9e4b-213bd1939255.png)

**Comment by cryptoBeliever** [comment]
Steps:
1. Remove 0 from symbol.xym amount
2. Put again 0 into symbol.xym amount
3. Validation error is presented

Expected result: Application should allow send 0 XYM (because for example we want add message) when we chaning amount.

**Comment by cryptoBeliever** [comment]
Fixed in latest live build.
