### ISSUE TITLE
Import QR code , next button missing 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#725]
login to an account, click on the import QR code link, upload an QR code , what is the next step/button ?

![image](https://user-images.githubusercontent.com/49143210/99946567-900f4500-2d9c-11eb-950c-24f19d1a609a.png)

**Comment by surekabpm** [comment]
![address-qr-Seed Account 1](https://user-images.githubusercontent.com/49143210/99964736-c8714c00-2db9-11eb-87fe-521d57f067b9.png)

**Comment by yilmazbahadir** [comment]
I believe this is fixed by https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/729

**Comment by cryptoBeliever** [comment]
Verified using new QR.

![image](https://user-images.githubusercontent.com/17684281/100917519-8c379d00-34d7-11eb-8e80-7cb924cc66a9.png)

**Comment by surekabpm** [comment]
Tested from my side as well and issue fixed
