### ISSUE TITLE
scan via camera is not working 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#726]
login into account , click import QR code link,select scan via camera, it is blank page 
@AdriaCarrera 
    ![image](https://user-images.githubusercontent.com/49143210/99947441-fea0d280-2d9d-11eb-9d92-d7e3d5790744.png)

**Comment by yilmazbahadir** [comment]
@surekabpm It should ask your permission to access the camera and you should accept it before you can see it streaming. Can you describe your environment? (Operating System, thru Browser or Electron App)

**Comment by surekabpm** [comment]
Hi, I'm having windows ,chrome browser, I'm not getting any pop up for accessing camera

**Comment by cryptoBeliever** [comment]
@surekabpm please install app from here: https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5
Don't use live build http://desktop-build.symboldev.com/ for that. Browser is blocking if not HTTPS or localhost.

**Comment by yilmazbahadir** [comment]
@surekabpm Can you please close this issue if it is not valid?

**Comment by surekabpm** [comment]
Closing this issue as it is not valid
