### ISSUE TITLE
Bug - phone number , email validation in add an account 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#727]
When you add an account , in the contact information validation of email need to be fixed.Also need to know the length of numbers for phone number 
![image](https://user-images.githubusercontent.com/49143210/99952464-b9809e80-2da5-11eb-89c2-ce84560f475a.png)
![image](https://user-images.githubusercontent.com/49143210/99952518-cb624180-2da5-11eb-976a-77a7de579c4a.png)

**Comment by cryptoBeliever** [comment]
I don't think that validation of phone length make sense since in different countries you have different format.
Email could be validated.

**Comment by cryptoBeliever** [comment]
The email field is now validated. Closing.
