### ISSUE TITLE
Bug - Back up of address book is a JSON file 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#728]
Under the Accounts tab, click my contacts and when you click the back up address book , the file generated is a JSON file. is that ok ? i'm not sure on the expected result @AdriaCarrera 
![image](https://user-images.githubusercontent.com/49143210/99952871-5f340d80-2da6-11eb-8a1e-3cdda28cfa5f.png)

**Comment by cryptoBeliever** [comment]
@surekabpm yes. This is expected. In json file is backup of address book.
