### ISSUE TITLE
Graph API call for accounts that are not cosigners and multisigs

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#730]
For accounts that are not cosigners and not multisigs call for multisig/graph is not necessary (return always 404). 
If it's possible to avoid would be nice. 

![image](https://user-images.githubusercontent.com/17684281/99995734-176bb100-2dbb-11eb-90fe-d40effff6f18.png)

**Comment by yilmazbahadir** [comment]
We have to call this endpoint to find out if that's multi-sig related. So it is a must at the moment.

**Comment by cryptoBeliever** [comment]
ok
