### ISSUE TITLE
Confirmation modal on delete account

### ISSUE THREAD

**Issue by yilmazbahadir** [nemgrouplimited/symbol-desktop-wallet#732]
We should show a confirmation modal (with text) before deleting the account.

**Comment by cryptoBeliever** [comment]
Also when we deleting account we got title "Unlock your account"

![image](https://user-images.githubusercontent.com/17684281/100923069-f30c8480-34de-11eb-9e55-c227549606cf.png)

**Comment by cryptoBeliever** [comment]
Works correctly :+1:
