### ISSUE TITLE
User is able to initiate transfer transaction under Multisig account [BUG]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#733]
Steps to reproduce:

1. Create multisig account
2. Go to Transfer on Home under Multisig acount 
3. Switch to another co-signer account via upper menu 
4. Standing on Transfer under co-signer account select co-signer account in the From field 
5. Toggle back to Multisig account in the From field 
6. Switch to Multisig account via upper menu 
7. Initiate the transfer transaction

Expected result: The transfer could not be initiated under Multisig account
Actual result: The transfer is initiated and fails with an error

[Video](https://www.loom.com/share/a8a201fe68e6432d858e9885bfa420a4)

**Comment by yilmazbahadir** [comment]
Related to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/734

**Comment by cryptoBeliever** [comment]
@Eugenity could you verify?

**Comment by Eugenity** [comment]
Verified
