### ISSUE TITLE
Green pop-up about using Multisig acount is not displayed [BUG]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#734]
Steps to reproduce:

1. Create multisig account
2. Go to Transfer on Home under Multisig acount 
3. Switch to another co-signer account via upper menu

Expected result: The green pop-up about using Multisig acount in From field under co-signer account is displayed
Actual result: There is no green pop-up about using Multisig acount in From field under co-signer account

[Video](https://www.loom.com/share/98e8f0bced0c408faa281b3ea791047c)

**Comment by cryptoBeliever** [comment]
@Eugenity could you check?

**Comment by Eugenity** [comment]
Verified
