### ISSUE TITLE
empty window after logout

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#735]
Empty white window after logout.

Output bash:

~/0-13-5/symbol-desktop-wallet-linux-x64-0.13.5> ./symbol-desktop-wallet 
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

**Comment by cryptoBeliever** [comment]
Yes. Have the same (blank screen) on Linux electron build. On HTML build it work well.

**Comment by cryptoBeliever** [comment]
Will be checked after the standalone version release.

**Comment by cryptoBeliever** [comment]
Fixed in 0.13.6
