### ISSUE TITLE
Configuring new account - without data also , account is created 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#737]
From my contact page, click the add an account , without giving any name and address click confirm, an account is formed still without name 

@yilmazbahadir 

![image](https://user-images.githubusercontent.com/49143210/100191393-0a170980-2f16-11eb-9abf-decb5b47e330.png)
![image](https://user-images.githubusercontent.com/49143210/100191461-2a46c880-2f16-11eb-81ca-582ea2b93c61.png)

**Comment by bassemmagdy** [comment]
related to #727

**Comment by cryptoBeliever** [comment]
It's fixed now. Not possible to add contact without address or name.
