### ISSUE TITLE
Icons in contact information - no response (+ icon and delete icon)

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#738]
In my contact page, add an account , when you click the account ,edit pen icon then you can see + icon and delete icon, i'm not sure that is working , if i click delete icon, it is neither deleted nor when i click the + icon no reaction
![image](https://user-images.githubusercontent.com/49143210/100196083-6120dc80-2f1e-11eb-90e2-352f5d4ccfef.png)

**Comment by cryptoBeliever** [comment]
@surekabpm looks ok now. Icons now work and are accurate.

![image](https://user-images.githubusercontent.com/17684281/101670118-142b2300-3a53-11eb-98ee-eaf213de8ec7.png)
