### ISSUE TITLE
[News page] Getting Network Error while loading Latest news and articles

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#739]
WTR:
1. Go to News page
Result: you can observe loader and Network Error in console

![image](https://user-images.githubusercontent.com/11311924/100211776-bff25000-2f36-11eb-8158-5193ed9d42c5.png)

**Comment by cryptoBeliever** [comment]
@NikolaiB could you check on installed version (not live build):
https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/tag/v0.13.5

**Comment by NikolaiB** [comment]
@cryptoBeliever yep, it works on installed version
