### ISSUE TITLE
QR code is too small to scan

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#740]
Even though there's plenty of unused space in this screen, the QR code is too small and my phone fails to scan it.
If I download the code and show it a bit bigger using another program, it scans correctly.
In the screencap from my phone you can see the pixels of the QR code have approximately the same size as the LCD pixels of my monitor, so they are very hard to recognize.
If the code cannot be made bigger, I would suggest clicking on it brings a popup with a larger version.

![image](https://user-images.githubusercontent.com/10949043/100224774-8e20bf80-2f1d-11eb-873a-8c2c8a6f637e.png)

![image](https://user-images.githubusercontent.com/10949043/100225433-7bf35100-2f1e-11eb-8ebd-f69976cd7788.png)

**Comment by cryptoBeliever** [comment]
It works on my phone without any issue. However it's good idea to think about make it a little bigger or give option to present bigger version on layer.

**Comment by cryptoBeliever** [comment]
@segfaultxavi address QR has now bigger size. Please check when you will have a time.
For me it works fine.
