### ISSUE TITLE
[Bug][Multisig account] Can not Remove Cosignatory 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#741]
WTR:
1. Create multisig account from 2 separate desktop wallets (not child account)
2. Go to Multisig page and try to Removed Cosignatory a few times
3. Go to Dashboard

Result: You can see that found was locked a few times but cosignatory still not removed 

![image](https://user-images.githubusercontent.com/11311924/100236759-49664a00-2f58-11eb-85f2-d99e80ea0d07.png)

**Comment by bassemmagdy** [comment]
related to #760

**Comment by NikolaiB** [comment]
Fixed
