### ISSUE TITLE
Incorrect error message when setting empty Mosaic Metadata

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#742]
Select MOSAICS->ADD METADATA->SEND.
Three popups appear saying that there's information missing, but the middle one reads: ``The {field} field is required``
![image](https://user-images.githubusercontent.com/10949043/100241715-4a858000-2f34-11eb-9743-b3bf65638e9a.png)

**Comment by bassemmagdy** [comment]
@segfaultxavi thanks for reporting. Since we decided to restrict the target account to the selected signer on the wallet for mosaic and namespace metadata transactions, this issue is not valid anymore.
