### ISSUE TITLE
Carriage in "To" field for Simple transaction under Multisig account via Aggregate [Bug]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#749]
Steps to reproduce:
1. Select a Multisig account from your profile
2. Go to Aggregate page
3. Click on the "+" button near the Simple transaction
4. Paste any data into "To" field e.g. recipient's address

Expected result: There is no carriage in the "To" field for a Multisig account
Actual result: There is a carriage in the "To" field for a Simple transaction operation under Multisig account via Aggregate

[Video](https://www.loom.com/share/94975385b42f4f018901a1b53ddfda38)

**Comment by bassemmagdy** [comment]
related to #750

**Comment by cryptoBeliever** [comment]
@Eugenity please verify.

**Comment by Eugenity** [comment]
Verified
