### ISSUE TITLE
Not all the Aggregate page is inactive under Multisig account [Bug]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#750]
Steps to reproduce:
1. Go to Aggregate page under Multisig account
2. Click onto the left part of the fee selector button in the "My transactions" block

Expected result: All the Aggregate page space is inactive
Actual result: A user is able to activate a fee selector button under Multisig account on the Aggregate page

[Video](https://www.loom.com/share/cad828fd2b2943bf8b9475a75c9e0233)

**Comment by cryptoBeliever** [comment]
All is blocked now.
