### ISSUE TITLE
[UI issues] Content blocks on Harvesting page are not centered

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#751]
v0.13.5

WTR:

Go to Harvesting page

Result: you can see that blocks content are not centered

![image](https://user-images.githubusercontent.com/11311924/100615914-7e044800-3342-11eb-8c35-ababea3c7cfa.png)

**Comment by cryptoBeliever** [comment]
@NikolaiB could you verify?
