### ISSUE TITLE
[UI issues] Select Contact window is not informative

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#754]
WTR:
1. Go to Home page -> Transfer
2. Click Select Contact button
Result: you can see empty window if there are no contacts.
As a solution description can be added: There are no contacts.

![image](https://user-images.githubusercontent.com/11311924/100717078-cb84c180-33e3-11eb-80cf-2c8884dd09e9.png)

Note: If there are contacts then the window should be trimmed to remove empty spaces

![image](https://user-images.githubusercontent.com/11311924/100717309-1272b700-33e4-11eb-98aa-23b18f3cc180.png)

**Comment by cryptoBeliever** [comment]
@NikolaiB please check. First part is fixed.
