### ISSUE TITLE
[Bug][Aggregate transaction] `Transaction details` are not fully visible on `Details about a transaction` window

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#755]
v0.13.5

WTR:
1. Go to Aggregate page
2. Create 4 Simple transactions
3. Send aggregate transaction
4. Go to Home page
5. Click Aggregate Complete transaction on the Dashboard

Result: You can see that not all transaction details are visible. Out of 4 transaction details you can see two and half.

![image](https://user-images.githubusercontent.com/11311924/100719618-0d633700-33e7-11eb-9d5f-8fecc4c5ae11.png)

**Comment by cryptoBeliever** [comment]
Duplicate https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/691

**Comment by NikolaiB** [comment]
@cryptoBeliever  I don't think it's a duplicate because the bug you are pointing to, is for confirmation page. The bug above is for already made transaction. + this case wasn't mentioned in this bug report #691

**Comment by cryptoBeliever** [comment]
@NikolaiB IMO it is. I added you screenshot to #691 too

**Comment by NikolaiB** [comment]
ok, thanks
