### ISSUE TITLE
When put max value transaction details are not presented

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#758]
Video: https://share.getcloudapp.com/Jruqw5v9

Steps:
1. Go send transaction view.
2. Put max allowed value into the amount. It's 9000000000000000.
3. Try to send a transaction. 

Result: Only input to put password is presented. There is no transaction details on the pop-up.
Expected result: Transaction details should be visible on pop-up.

When I'm sending 9000000000 then all is OK.

**Comment by james-lin71** [comment]
This issue comes from symbol-sdk, when we pass large number as mosaic amount.
```
    /**
     * Compact higher and lower uint parts into a uint
     * @returns {number}
     */
    compact() {
        const result = format_1.RawUInt64.compact(this.toDTO());
        if (Array.isArray(result)) {
            throw new Error('Compacted value is greater than Number.Max_Value.');
        }
        return result;
    }
    ```
Once we pass a large number, this cause Number.Max_Value overflow issue by returning array. Maybe, we can consider the amount of mosaic value to be less than 9000000000, or any better solution for this one?

**Comment by rg911** [comment]
Yep, the mosaic amount type on server is 64 byte unsigned integer, so compact will throw if it over the max integer. 
One option is to cast the long to numeric string, then call UInt64.fromNumericString() to pass to the sdk. Check the UInt64 class on sdk, it provides basic add / subtraction operations

**Comment by coiki** [comment]
User Story: As a user sending mosaics, in the confirmation popup I want to see the details of my transaction regardless of any input, so I can confirm the details before entering my password and confirm the transaction.

Acceptance Criteria:

- AC1: When signing an outbound transaction, the details of the tx should always be shown.

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
