### ISSUE TITLE
Unable to convert account to multi-signature

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#760]
The wallet announce **HASH_LOCK** without **AGGREGATE_BONDED**
![image](https://user-images.githubusercontent.com/33131259/100784569-0c96c900-3418-11eb-8a58-06f113534a42.png)
![image](https://user-images.githubusercontent.com/33131259/100784598-17515e00-3418-11eb-9e0a-acaf9bdcdfba.png)
![image](https://user-images.githubusercontent.com/33131259/100784624-220bf300-3418-11eb-8c47-7f2e5c57f277.png)
![image](https://user-images.githubusercontent.com/33131259/100784638-26d0a700-3418-11eb-999b-5c6ecb3157cf.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko what not did you used?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever sorry, I don't understand your question

**Comment by cryptoBeliever** [comment]
@OlegMakarenko sorry. Autocorrect. 
Which one node was selected when you tried convert to multisig? I'm asking becauase there was problems with couple of nodes.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever I've just tried one more time and it works. I don't remeber I changed a node 
![image](https://user-images.githubusercontent.com/33131259/101035456-6b2c8600-3583-11eb-8c81-80bd16eab0b5.png)

**Comment by bassemmagdy** [comment]
@OlegMakarenko please confirm and provide reproduction steps if this's still happening. I couldn't reproduce it.

**Comment by OlegMakarenko** [comment]
@bassemmagdy 
1. Generate 3 seed accounts (let's call them **s1**, **s2**, **ms**)
2. Send 500 XYM to each of them
3. Select **ms** account and go to the Multisig page
4. Add **s1** and **s2** as cosignatories
5. Set minApproval = 2. Set minRemoval = 1
6. Confirm
7. Send

**Comment by cryptoBeliever** [comment]
@Eugenity @NikolaiB please check it too if possible.

**Comment by NikolaiB** [comment]
@cryptoBeliever I couldn't test it yesterday due to node issue. When the node issue is fixed I will test it.

**Comment by NikolaiB** [comment]
Fixed
