### ISSUE TITLE
Namespace creation is timed out 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#762]
I created a new namespace , it gives transaction signed successfully, the transaction is not shown in dashboard and after some time timed out error is shown. note: namespace was created  previously, i believe it is broken now 
![image](https://user-images.githubusercontent.com/49143210/100838580-abfba080-3498-11eb-9fa1-9380ca2a69cf.png)

**Comment by cryptoBeliever** [comment]
@surekabpm 
Are you able to reproduce every time? Is this happen also on each node?

**Comment by surekabpm** [comment]
Yes i'm able to reproduce every time  ... and looks like I'm not able to change the nodes 
![image](https://user-images.githubusercontent.com/49143210/100851619-74e2ba80-34ab-11eb-921d-8c0889691150.png)

**Comment by cryptoBeliever** [comment]
Node switch is in the bottom left corner.

**Comment by surekabpm** [comment]
getting error while changing node 
![image](https://user-images.githubusercontent.com/49143210/100852146-1407b200-34ac-11eb-8d04-e3319d4c4890.png)

**Comment by cryptoBeliever** [comment]
Node http://api-01.eu-central-1.0.10.0.x.symboldev.network:3000/chain/info is behind with height and this is probably reason of your error.
You have old list of nodes because api-01.eu-west is no longer active.
You can try switch to `http://api-01.ap-southeast-1.0.10.0.x.symboldev.network:3000`

**Comment by surekabpm** [comment]
yes it is working and the namespace is also created ,...old namespace also listed, so we can close this issue 
![image](https://user-images.githubusercontent.com/49143210/100855046-c0976300-34af-11eb-9acf-ad58743fe8c6.png)
