### ISSUE TITLE
[Bug][Import account with mnemonic] Balance is not visible

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#763]
WTR:
1. Try to import account with mnemonic.
2. Choose account with balance from Address to interact with column
Result: you don't see the balance amount from Select Accounts column **[Video](https://www.loom.com/share/eed309622f7c48e2a74d580356abd1f1)** 

![image](https://user-images.githubusercontent.com/11311924/100866199-83889c00-34c2-11eb-8562-f87b1dee8fa0.png)

**Comment by cryptoBeliever** [comment]
Hmmm... It worked for me:

![image](https://user-images.githubusercontent.com/17684281/100923719-e5a3ca00-34df-11eb-9cea-bd5fa425f75f.png)

Maybe it was node problem?

**Comment by NikolaiB** [comment]
@cryptoBeliever  I am trying with different accounts but I have the same result.

**Comment by cryptoBeliever** [comment]
@NikolaiB looks like fixed in the latest version (http://desktop-build.symboldev.com/). So I'm closing.
