### ISSUE TITLE
[Bug] Getting N/A in Balance column while importing account with mnemonic

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#765]
v.0.13.5

WTR:
1. Try to import account with mnemonic.

Result: on Select Account Page you will see that child accounts in Balance column have N/A instead of actual amount that is 0.

![image](https://user-images.githubusercontent.com/11311924/100992349-48e43980-357e-11eb-8c8d-7d1c822b6ed5.png)

**Comment by bassemmagdy** [comment]
related to #763

**Comment by bassemmagdy** [comment]
Hi @NikolaiB, thanks for reporting, can you spot that on latest [build](http://desktop-build.symboldev.com )?

**Comment by NikolaiB** [comment]
fixed
