### ISSUE TITLE
NEM Foundation still mentioned in wallet

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#766]
NEM Foundation is still mentioned in wallet:
- In privacy policy
- Greg contact is mentioned in the code of conduct

Please search for:
https://github.com/nemgrouplimited/symbol-desktop-wallet/search?q=foundation

Before change please consult with NGL how it should be changed. Maybe some of it will be changed with PrivacyPolicy update.

**Comment by cryptoBeliever** [comment]
Before change please consult with NGL how it should be changed. Maybe some of it will be changed with PrivacyPolicy update.

**Comment by cryptoBeliever** [comment]
@bassemmagdy 

Terms and Privacy Policy is the final version?

If yes:
1. There is a typo contact@nemn.io but should be contact@nem.io
2. Should we use contact@nem.io or different address? Where this address directs, how receiving this email?
3. NEM Group has the invalid address "NEM Group Limited. 57 Mohamed Sultan Rd., #01-05, Sultan-Link, Singapore 238997"

If no:
We should ask for the final versions.

**Comment by bassemmagdy** [comment]
@cryptoBeliever I think @Pow1404 should give us input on that.

**Comment by cryptoBeliever** [comment]
NGL address still is wrong:

![image](https://user-images.githubusercontent.com/17684281/105904051-f3c62080-6020-11eb-9931-6078ec68855b.png)
