### ISSUE TITLE
Transaction filter is not closed after clicking outside the dropdown [Bug]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#770]
**Steps to reproduce:** 

1. Go to Home / Dashboard
2. Click on the transaction filter
3. Click outside the dropdown

**Expected result:** The filter dropdown gets closed
**Actual result:** The filter dropdown remains opened even after invoking other buttons/filters

[Video](https://share.getcloudapp.com/qGuldR8v)

**Comment by cryptoBeliever** [comment]
It's fixed.
