### ISSUE TITLE
[Bug] Delegated harvesting is not activating

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#778]
WTR:
1. Create multisig account from 2 separate desktop wallets (not child account)
2. Go to Harvesting page
3. Choose multisig account from From dropdown list
4. Choose http://api-01.us-west-2.0.10.0.x.symboldev.network:3000 node from node list
5. Click Activate button

Result: Harvesting is not active. Go to http://api-01.us-west-2.0.10.0.x.symboldev.network:3000/node/unlockedaccount and you can not see the public key of multisig account there.

**Comment by cryptoBeliever** [comment]
@NikolaiB 
This node (http://api-01.us-west-2.0.10.0.x.symboldev.network:3000/chain/info) is in fork and doesnt work correctly.
At this moment we don't have node with unlockedaccount endpoint to test if it change in activate. Please remember about this case and retest when we will have any node to test it correctly.

**Comment by cryptoBeliever** [comment]
Reopened because @NikolaiB is still able to reproduce
