### ISSUE TITLE
No pop-up when the address of co-signatory is wrong on Multisig page [Bug]

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#780]
**Steps to reproduce:**

1. Go to Multisig page
2. Click "Add a cosignatory" button
3. Paste a wrong address
4. Click "+" button

**Expected result:** The pop-up informing that the address is wrong appears
**Actual result:** No pop-up informing that the address is wrong to a user

[Video](https://share.getcloudapp.com/OAuWJ9BK)

**Comment by cryptoBeliever** [comment]
@Eugenity please verify.

**Comment by Eugenity** [comment]
Verified
