### ISSUE TITLE
Sending to linked alias not possible

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#785]
Steps:
1. Create alias linked with account. For example  walias
2. Try send to this alias

Result: "The recipient field is incorrect." message presented

![image](https://user-images.githubusercontent.com/17684281/101539369-b5a46d00-399e-11eb-99f1-ca3f0e9243d2.png)

We should either:
- Change mask text for  "To" input from "Enter address or alias (e.g., nem.foundation)" to "Enter address"
- Allow sending to alias

As far as I remember sending to alias was functional.

**Comment by myxmaster** [comment]
(also here: Aggregate -> Simple transaction)

**Comment by cryptoBeliever** [comment]
Fixed.
