### ISSUE TITLE
Tips - Mneumonics for password backup is always displayed as invalid

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#787]
While generating the account , at the verification stage for the back up mneumonics Tips is displayed as "Your mnemonic words backup is invalid. Please, carefully select the words in the correct order.".
I have not yet entered any words, but is this display right? kindly review 
![image](https://user-images.githubusercontent.com/49143210/101596361-ecb86400-3a1a-11eb-8f7c-3204ace223d6.png)
@bassemmagdy

**Comment by cryptoBeliever** [comment]
Fixed by changeing tooltip.
