### ISSUE TITLE
[Bug][Multisig] Can not properly revert multisig account into simple account

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#789]
WTR:
1. Create multisig account from 2 separate desktop wallets or it can be child account.
2. Go to Multisig page and remove multisig account from co-signories 
3. Go to multisig account

Result: the web was not updated despite that accounts were untight 

![image](https://user-images.githubusercontent.com/11311924/101604534-41fc7180-3a2b-11eb-81a4-8969ba00e336.png)

![image](https://user-images.githubusercontent.com/11311924/101604465-2abd8400-3a2b-11eb-923e-df4465728a55.png)

**Comment by bassemmagdy** [comment]
@NikolaiB  should be fixed after this [PR](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/796) gets merged.

**Comment by userNikolai** [comment]
fixed.
