### ISSUE TITLE
Amount is not updated

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#797]
The display of the amount of a transaction that takes place shortly after opening the wallet is not updated. The correct display only takes place after the account has been changed.
My steps:

1)Open the wallet
2)Change from account-one to account-four
3)Transaction requested by faucet
4)Transaction from faucet confirmed
5)The display of the amount does not change

![transaction8](https://user-images.githubusercontent.com/46584115/101681984-4a709e80-3a63-11eb-9d88-b1546188a177.png)

**Comment by cryptoBeliever** [comment]
@garm01 would be possible to create video for example using https://share.getcloudapp.com/?
I used exactly your steps and it worked. May be related with node (please provide node you using) and websockets.
