### ISSUE TITLE
Can add contact with the same name and the same address

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#798]
WTR:
1. Go to Accounts page
2. Click Add Contact
3. Add two contacts with the same name and the same id

Result: duplicate contacts can be added

![image](https://user-images.githubusercontent.com/11311924/101732226-1048e080-3ae7-11eb-89f4-c0a261a9317b.png)

**Comment by cryptoBeliever** [comment]
There is no way to add same address twice. But you can add two difference with the same name. 
@NikolaiB please verify if this is OK for you.

**Comment by NikolaiB** [comment]
Fixed
