### ISSUE TITLE
[UI bug] Remove additional space in Select Contact window

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#799]
WTR:
1. Add a few contacts in contact list
2. Go to Home -> Transfer 
3. Click button Select Contact

Result: observe additional space above the contact list

![image](https://user-images.githubusercontent.com/11311924/101737321-e693b780-3aee-11eb-98a6-1526016d618a.png)

**Comment by cryptoBeliever** [comment]
@NikolaiB missing screenshot.

**Comment by cryptoBeliever** [comment]
It's fixed now.
