### ISSUE TITLE
Restrictions - Not possible to lift "account operation restriction" restriction

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#808]
Steps:

1. Add restriction:
Type: Account operation restriction
Restriction Additions: Account operation restriction
Restriction Flag: AllowOutgoingTransactionType

**Now all should be blocked except lifting restriction. And indeed I got Failure_RestrictionAccount_Operation_Type_Prohibited when trying send Transfer Transaction**

2. Try remove restriction. Not possible with error **Failure_RestrictionAccount_Invalid_Modification**

What is even stranger I'm able to add another operation restriction and I'm able to remove it.

**Comment by yilmazbahadir** [comment]
Then we should put a restriction to "account operation restriction" :)

**Comment by cryptoBeliever** [comment]
Fixed by removing "Allow" from "Type" and "Account operation restrictioin" from "Operation type" selectboxes. Network behaviour stays unchanged.
Thanks @bassemmagdy :+1:
