### ISSUE TITLE
Dashboard and Harvesting pages were not updated 

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#816]
v0.13.6

WTR:
1. Go to Desktop Symbol wallet
2. Initiate transaction

Result: transaction was initiated but it is not reflected on the dashboard [Video](https://www.loom.com/share/d7f0e7357a914b429fcef81108f11ffa)
Note: I can observe this issue while load testing is performed

![image](https://user-images.githubusercontent.com/11311924/102052328-2a006580-3e10-11eb-9e6a-e0fa9fb0bc76.png)

2. Go to Harvesting page

Result: instead of Incative you can see Key Linked state

![image](https://user-images.githubusercontent.com/11311924/102052723-b874e700-3e10-11eb-82e7-097debf976a3.png)

Note: I was trying to change nodes but it didn't help

**Comment by cryptoBeliever** [comment]
@NikolaiB could you still reproduce now when load testing are not done?

**Comment by NikolaiB** [comment]
@cryptoBeliever Can not reproduce. I will close the issue.
