### ISSUE TITLE
Unable to create mosaics when it is the first operation initiated in account

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#828]
**Steps to reproduce:**

1. Create a new account, make sure you did no operations
2. Go to Mosaics page
3. Send an operation for creating new mosaics (no matter how you configured it)
4. Confirm it

**Expected result:** New mosaics are created
**Actual result:** An error "Failure_Core_Zero_Public_Key" occurs, mosaics are not created

[Video](https://share.getcloudapp.com/llunk0GL)

**Comment by bassemmagdy** [comment]
Hi @Eugenity, This is not a valid scenario anyways as you will have to pay fees to be able to create your mosaic. So at the end of the day creating a mosaic with a virgin account(account with no transactions/funds) will not be possible. And for the failure/notification **Failure_Core_Zero_Public_Key** it will be updated after this [pr](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/826) gets merged to show **Faliure_Insufficient_Balance** instead.

**Comment by Eugenity** [comment]
Hi @bassemmagdy I had a balance there, in that account (taken from faucet link), so this scenario is possible to reproduce only while testing, right?

**Comment by bassemmagdy** [comment]
@Eugenity I thought you had no funds because you mentioned that the account should have no operations meaning it's a fresh one.
If the account already got funds you shouldn't observe that behavior at all. Please, re-verify that after merging #826

**Comment by cryptoBeliever** [comment]
It's not fixed. Same error as in OP

**Comment by cryptoBeliever** [comment]
Looks like fixed now.
