### ISSUE TITLE
[Desktop] networkCache was not updated

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#830]
v0.13.6

WTR:
1. Install desktop version v0.13.5 and run it
3. Go to networkCache
Result: you can see that the default node address is http://api-01.us-east-1.0.10.0.x.symboldev.network:3000
4. Remove the app
5. Install desktop version v0.13.6 and run it
6. Go to networkCache
Result: despite that the default node address was changed to http://api-01.us-west-1.0.10.0.x.symboldev.network:3000, you still can see http://api-01.us-east-1.0.10.0.x.symboldev.network:3000

**Comment by cryptoBeliever** [comment]
Is this problem also after installing 0.13.8?

**Comment by cryptoBeliever** [comment]
@NikolaiB ?

**Comment by NikolaiB** [comment]
@cryptoBeliever fixed.
