### ISSUE TITLE
Pdf file is not created after clicking download in desktop version 

### ISSUE THREAD

**Issue by surekabpm** [nemgrouplimited/symbol-desktop-wallet#833]
This is issue is in desktop version, in windows
While creating an account, when you click the download button, a default pdf file need to be saved, but here the windows open and gives only option as" all files", if I select it it is not saved as pdf form.
![image](https://user-images.githubusercontent.com/49143210/102475835-63d7a300-4080-11eb-8d3d-0f1fcfc44665.png)
![image](https://user-images.githubusercontent.com/49143210/102475858-6934ed80-4080-11eb-9c2e-43b1bedab564.png)

**Comment by cryptoBeliever** [comment]
If this is how it works on all Windows then I'm increasing priority.

**Comment by bassemmagdy** [comment]
@cryptoBeliever @surekabpm I cannot re-produce it on mac and windows, can you verify that this is still happening?

**Comment by cryptoBeliever** [comment]
@bassemmagdy on my Linux is ok. @surekabpm please check.

**Comment by surekabpm** [comment]
This issue is fixed ,we can close this issue
![image](https://user-images.githubusercontent.com/49143210/103738205-9cccbd00-5019-11eb-9865-79ce85e3cc16.png)
