### ISSUE TITLE
Under Multisig account co-signers are displayed as "(Multisig)" in "Multisig accounts" filter

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#838]
**Steps to reproduce:**

1. Create a Multisig account
2. Go to Dashboard or Accounts/restrictions page, Mosaics, Namespaces
3. Click on the "Multisig accounts" filter

**Expected result:** Co-signers are indicated as "(Co-signer)" or similar
**Actual result:** Co-signers are displayed as "(Multisig)" in the filter

[Screenshot](https://share.getcloudapp.com/4guOZ4Nm)

**Comment by cryptoBeliever** [comment]
@Eugenity please verify.

**Comment by Eugenity** [comment]
Verified
