### ISSUE TITLE
"Import Transaction URI" dialog window has wrong size

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#842]
**Steps to reproduce:**

1. Go to Transfer
2. Click "Import Transaction URI" higlighted text

**Actual result:** The dialog window modal element has wrong size, some elements are outside its background
**Expected result:** The dialog window modal element encapsulates all the elements

[Screenshot](https://share.getcloudapp.com/p9urOoep)

**Comment by cryptoBeliever** [comment]
It's fixed (check on live-build).
