### ISSUE TITLE
ctrl+r captured whenever windows app running

### ISSUE THREAD

**Issue by Drunkar** [nemgrouplimited/symbol-desktop-wallet#844]
When desktop app is running, short cut ctrl+r is captured by the desktop-wallet even if it's not focused.
This is why we use `globalShortcut` in `public/build.js` . `globalShortcut` in electron will capture all key input even if it's background.

https://github.com/electron/electron/issues/8491

In `public/build.js`, the comment says "do nothing to forbidden default refresh", but is there any reasons to disable it? When I built the app without the statements related to the shortcut, it looks working properly.

```diff
  if (process.platform === 'darwin') {
    app.on('ready', createMac)
  } else {
    app.on('ready', createWindow)
-    app.on('ready', function () {
-      globalShortcut.register('CommandOrControl+R', function () {
-        // do nothing to forbidden default refresh
-      })
-    })
  }
```

The problem is, when I enable it, I cannot use ctrl+r in any other applications. (You know it's a popular shortcut: refresh, search backwards, etc...)

**Comment by cryptoBeliever** [comment]
@bassemmagdy after I used ctr+R in the application something strange happened:

![image](https://user-images.githubusercontent.com/17684281/105903466-33403d00-6020-11eb-9a3d-713357d9085c.png)

**Comment by cryptoBeliever** [comment]
Looks like fixed now.
