### ISSUE TITLE
Getting Falure_Core_Past_Deadline and Failure_LockHash_Unknown_Hash just right after login

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#845]
WTR:
1. Login into web or desktop app

Result: I am getting a set of repeated errors [Video](https://www.loom.com/share/fd47ffd68578436ea5cac308289a6f1a)
Note: I am getting this errors while load testing is performed.

![image](https://user-images.githubusercontent.com/11311924/102880528-abda3980-4475-11eb-927f-5962407ca8f1.png)
![image](https://user-images.githubusercontent.com/11311924/102880545-b1378400-4475-11eb-88f7-064101ea1365.png)

**Comment by bassemmagdy** [comment]
@NikolaiB can you verify this is still happening?
