### ISSUE TITLE
URI link in Transfer page only appears if address is in plain format, not pretty

### ISSUE THREAD

**Issue by segfaultxavi** [nemgrouplimited/symbol-desktop-wallet#847]
Go to Transfer page and enter an address in the `To:` field in pretty format (with dashes): ` TDC3T5-KZOQC4-L6OAQB-B4FNBQ-5627BU-LJC6KK-DNI`
There will be no URI link (`web+symbol://...`) at the bottom of the form.
Now remove the dashes and the URI link will appear.

The form accepts both address formats (plain and pretty) so I think the URI link should appear when either one is used.

**Comment by cryptoBeliever** [comment]
Fixed.
