### ISSUE TITLE
"Send aggregate" and "bin" buttons on Aggregate page are inactive after toggling to Multisig account and back

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#851]
**Steps to reproduce:** 

1. Go to Aggregate page under non-Multisig account
2. Save any transaction to My transactions block
3. Toggle to Multisig account within the same profile
4. Toggle back to non-Multisig account
5. Click on "Send aggregate" or "bin" button within the saved transaction

**Actual result:** The buttons are inactive blocking a user from sending transaction(s) or deleting them
**Expected result:** The buttons are active allowing a user to send transaction(s) or to delete them

[Video](https://share.getcloudapp.com/d5uPyGLR)

Workaround: Go to any page e.g. Accounts or News and return back to the Aggregate page

**Comment by cryptoBeliever** [comment]
@Eugenity I guess it doesn't apply anymore because saved transactions disappear after switching to another account?

**Comment by Eugenity** [comment]
Yes, it is not reproducible anymore since what you mentioned. Closing.
