### ISSUE TITLE
harvest node url => invalid node

### ISSUE THREAD

**Issue by joarrries** [nemgrouplimited/symbol-desktop-wallet#859]
when I enter the node url, it keeps prompting invalid node.
![image](https://user-images.githubusercontent.com/54062081/103149946-a3516e00-47a9-11eb-891f-024b49cb075a.png)

**Comment by cryptoBeliever** [comment]
@joarrries you should put just 176.223.141.198 and it should work.

@yilmazbahadir iti should be more user friendly to put node IP, IP wit port, IP with port and protocol. Same applies to adding new node in Settings.

**Comment by cryptoBeliever** [comment]
I created:
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1115
https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1116
Closing this one.
