### ISSUE TITLE
can't select a node in Network settings

### ISSUE THREAD

**Issue by joarrries** [nemgrouplimited/symbol-desktop-wallet#860]
![image](https://user-images.githubusercontent.com/54062081/103149961-bd8b4c00-47a9-11eb-829c-5ddab10c3e75.png)
I tried to select a node, but it's not work.
![image](https://user-images.githubusercontent.com/54062081/103149964-c7ad4a80-47a9-11eb-99d0-5a79a69d62cd.png)

**Comment by bassemmagdy** [comment]
Hi @joarrries, thanks for reporting. Please note that you should be switching nodes using the left-bottom corner menu, not network sertings.

**Comment by cryptoBeliever** [comment]
@joarrries this view is only for adding new nodes. For switching please use "Node" in bottom left corner.

![image](https://user-images.githubusercontent.com/17684281/103150698-bc8cf700-4776-11eb-952f-3a43f37ffa92.png)

We have other issue reported to make it more user friendly here: https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/657
So I'm closing this one.
