### ISSUE TITLE
Able to see aggregate transaction from another account

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#866]
WTR:
1. Go to account A
2. Add account B 
3. You are in account A -> Go to Aggregate page 
4. Add Simple Transaction, Mosaic Transaction, Namespace Transaction
5. Switch to account B -> Go to Aggregate page 

Result: you will see aggregate transactions made by account A. [Video](https://www.loom.com/share/f7944e6325724b95bf9ae4b58fc15520)

**Comment by cryptoBeliever** [comment]
@NikolaiB could you verify?

**Comment by NikolaiB** [comment]
fixed
