### ISSUE TITLE
Namespaces - descending sorting doesn't work

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#874]
Go to namespaces list and try sort descending by any property (id, name, expiration, alias type, alias). 
Descending sorting doesn't work. Only ascending.

Example sorting descending by name:

![image](https://user-images.githubusercontent.com/17684281/103708127-46776400-4fb0-11eb-8f08-813e3c0f2e63.png)

Example sorting descending by expiration:

![image](https://user-images.githubusercontent.com/17684281/103708164-555e1680-4fb0-11eb-997b-c9cd00fc38d8.png)

Right now only the first page of namespaces is fetched using API (https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/855). Not sure if sorting is supported by API.

**Comment by Eugenity** [comment]
Verified. Closing.
