### ISSUE TITLE
Aggregate - From selector reseting when editing

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#875]
Steps:
1. Go to aggregates.
2. Add simple transaction and select in "From" multisig account. Save.
3. Open again transaction.

Result: From is reset and it's presenting cosigner instead multisig account.

Video: https://www.loom.com/share/c62eeb16640f44e78c782fcb107fda46

**Comment by rg911** [comment]
This should as well be fixed by https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1032

**Comment by cryptoBeliever** [comment]
@rg911 no. Still able to reproduce but now I have open twice:
https://share.getcloudapp.com/NQuJvejL

**Comment by cryptoBeliever** [comment]
Fixed.
