### ISSUE TITLE
Metadata - not possible add metadata to mosaic owned by multisig

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#877]
Steps:

1. Create mosaic for multisig.
2. Go to mosaics, switch to multisig account.
3. Add metadata.
4. Mosaic selector is empty.

Video: https://www.loom.com/share/c5b4591a39d84a1ebb1059707de43ceb

**Comment by NikolaiB** [comment]
@cryptoBeliever could you please verify.

**Comment by Eugenity** [comment]
@NikolaiB @cryptoBeliever this one looks like not fixed, right now rechecking it again.

**Comment by bassemmagdy** [comment]
@NikolaiB @Eugenity https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1241 not merged yet

**Comment by cryptoBeliever** [comment]
@bassemmagdy how can I edit it created metadata?
