### ISSUE TITLE
Namespaces - not possible to edit or view metadata for namespace owned by multisig

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#878]
Steps:
1. Create namespace for multisig
2. Go to namespaces and add metadata for namespace owned by multisig. Cosign transaction by cosigners.
3. Go to namespaces. There is no way to preview or edit metadata. 

![image](https://user-images.githubusercontent.com/17684281/103711165-17182580-4fb7-11eb-8c18-10554324bef1.png)
But as I can see in explorer this namespace have metadata:
http://explorer-0.10.0.x-01.symboldev.network/namespaces/testnamespacezzz

**Comment by bassemmagdy** [comment]
@cryptoBeliever I couldn't reproduce it on http://desktop-build.symboldev.com/

**Comment by cryptoBeliever** [comment]
Right now me too. Closing.
