### ISSUE TITLE
Restrictions - presenting multisig restrictions under cosigner

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#881]
Steps:

1. Open restriction pop-up on cosigner side and switch on pop-up to multisig.
2. Close restrictions pop-up
3. Open again pop-up. Now on selector, we have choosen cosigner account but restrictions are presented for multisig.

Video: https://www.loom.com/share/0cc37aa8d6744d4799a60699c199762a

**Comment by NikolaiB** [comment]
@cryptoBeliever fixed
