### ISSUE TITLE
Remove the value from `Address or public key` field when co-signor is added

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#886]
WTR:
1. Go to Multisig page
2. Add cosignor 

Result: cosignor address was not removed from `Address or public key` field

![image](https://user-images.githubusercontent.com/11311924/103870781-62851d80-50f6-11eb-90a8-39c9befd8a6a.png)

**Comment by cryptoBeliever** [comment]
Fixed in 0.13.8
