### ISSUE TITLE
Invoice tab is overlaid by filter

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#887]
WTR:

1. Go to multisig account Dashboard
2. Choose multisig account from Multisig dropdown list

Result: you can see that invoice selector is overlaid 

![image](https://user-images.githubusercontent.com/11311924/103905763-35059780-5129-11eb-9a13-6ecca32f05da.png)

**Comment by bassemmagdy** [comment]
@NikolaiB please verify this issue is still happening either in the standalone app or [here](http://desktop-build.symboldev.com/)

**Comment by NikolaiB** [comment]
@bassemmagdy I still can reproduce the issue on web and standalone apps

**Comment by cryptoBeliever** [comment]
@NikolaiB looks like fixed in latest version available here http://desktop-build.symboldev.com/
Closing.
