### ISSUE TITLE
Getting wrong notification about minimal fees

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#895]
v.0.13.8

WTR:
1. Go to Transfer page/ Multisig page

Result: you can see wrong notification `please note that minmimal fees for the current selected node is 13 symbol.xym
` in real the fee is 0.176 

![image](https://user-images.githubusercontent.com/11311924/104702794-b4562500-5740-11eb-964c-85b29de46e0a.png)

![image](https://user-images.githubusercontent.com/11311924/104711007-ff753580-574a-11eb-992f-b578b128b000.png)

**Comment by cryptoBeliever** [comment]
Fixed.
