### ISSUE TITLE
Code signing for Windows and Mac

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#903]
https://www.electronjs.org/docs/tutorial/code-signing

We would need to sign the wallet to stop showing the untrusted message when installing the native apps.

**Comment by cryptoBeliever** [comment]
It's in progress AFAIK. Already done for Mac, waiting for Windows certificate.

**Comment by cryptoBeliever** [comment]
Apps are signed now.
