### ISSUE TITLE
Node switch issue

### ISSUE THREAD

**Issue by rg911** [nemgrouplimited/symbol-desktop-wallet#921]
When select different nodes from the available nodes list, the newly selected one seems not used by default.

It seems the websocket after node switch is still connected to the previous node

**Comment by cryptoBeliever** [comment]
@bassemmagdy web sockets to the previous node should stay open or should be closed?

**Comment by cryptoBeliever** [comment]
Currently it's improved. When changing node two websockets are open (for account and for blocks). 
Old account websocket is closed when switching node but block websocket is not.

**Comment by cryptoBeliever** [comment]
Web sockets management will be checked by @rg911 in https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/1011
I'm closing this one.
