### ISSUE TITLE
Suggestions for purple box on Home page

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#928]
Some suggestions for this box:

![grafik](https://user-images.githubusercontent.com/77545287/104960574-6b1a0580-59cc-11eb-9e73-72b35325459f.png)

1. There should be an "Address:" label before the address.
2. The text "XYM WALLET" makes no sense and should be removed.
3. After the balance, the currency code (XYM) should be displayed.

**Comment by jabo38** [comment]
@myxmaster is right. that isn't your "XYM WALLET". If anything it is your "XYM BALANCE". Note, a wallet and a balance are different things. So if it isn't changed to a "balance XYM" format as suggested in this report, it should at least say "XYM BALANCE balance"

**Comment by segfaultxavi** [comment]
Also, there's something bogus in the number `9.771.7482`. Regardless of the locale, shouldn't the decimal point and the thousands separator have different representations?

**Comment by myxmaster** [comment]
@segfaultxavi right, see here: https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/670

**Comment by cryptoBeliever** [comment]
Fixed.
