### ISSUE TITLE
Suggestions for profile creation (rephrasing)

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#930]
1. The text of the link to the profile creation page on the login page ("Create a new profile?") should just be "Create profile". It makes no sense as a question.
2. The title on the profile creation page currently is "Access my profile". Why not just "Create profile" again?
3. "Create mnemonic": The mnemonic is just one part of what is actually created here - a profile with accounts including addresses, public keys, private keys and a mnemonic. So the text should be "Create Profile", the subtitle could be "Create a new wallet".
4. "Import mnemonic": Same problem, I suggest "Import Wallet" with subtitle "Create profile from existing wallet".
5. The subtitles of Trezor and Ledger are redundant. I'm not sure if it's technically correct but something like "Create profile from Trezor/Ledger" would be better.

**Comment by jabo38** [comment]
1. I guess I would word it like "No Profile? Create one." This follows the same structure and pattern as when it later says, "Do you already have a profile? Click here to login now"

2. I guess if you are restoring a profile, technically you are "recreating my profile". So I'm not exactly sure the best term. 

3. 
![image](https://user-images.githubusercontent.com/10395907/104978552-7115e380-59d8-11eb-992b-0ead115a3216.png)

I agree the "Create mnemonic" as the bold is wrong. It should be "Create Profile" as you suggested. But I think it is fine to say "Create a pneumonic passphrase" underneath it. 

Side not, "Create pneumonic" is incorrect grammar. "Pneumonic" is an adjective. This is the same as saying "Create Tall" or "Create Slow". "Pneumonic" as an adjective needs to be used with the noun it is modifying, in this case "passphrase". 

So the clear wording should be in bold letters "Create Profile" and then underneath it "Make a pneumonic passphrase" or something along those lines. 

As for the second box, same problem. It should just be "Import Profile" in bold letters, and under it, "Restore pneumonic passphrase". 

4. I agree the Trezor and Ledger Language is off. 

I think it is more accurate to say "USE LEDGER" in bold, and then underneath it to say "Open your Ledger profile".

**Comment by myxmaster** [comment]
1. "Do you already have a profile? Click here to login now" is also nice. Maybe a little long, but yeah, totally fine.
2. When you use an existing mnemonic you are technically still creating a new [symbol desktop wallet] profile since a profile consists more than just the mnemonic (e.g. contacts in address book, those are stored with the profile and will not be recreated if you enter your existing mnemonic). Also, recreation is also a way to create.
3. Question is if people will really get used to the word "mnemonic" / use it that much in the future. In the end it is just a representation of the private key. Once you created a mnemonic [passphrase] and made your backup, you will not get in touch with it again that soon (only if you need to reimport it). Maybe we should make a tooltip helptext next to the word mnemonic and explain what it is?
4. Agreed

**Comment by NikolaiB** [comment]
fixed

**Comment by cryptoBeliever** [comment]
> I think it is more accurate to say "USE LEDGER" in bold, and then underneath it to say "Open your Ledger profile".

@bassemmagdy @NikolaiB what with Ledger wording? Was decided to not change it?

**Comment by NikolaiB** [comment]
fixed

**Comment by surekabpm** [comment]
can we close this issue @NikolaiB , if so pls close it

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/123477333-2e4ade00-d5fe-11eb-9414-369b8a28e9dc.png)
