### ISSUE TITLE
login button font isn't centered on Mac

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#931]
The login button looks bad. 

![image](https://user-images.githubusercontent.com/10395907/104976988-d7006c00-59d4-11eb-8343-53aed0909402.png)

**Comment by myxmaster** [comment]
this might be fixed with this: https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/927

**Comment by cryptoBeliever** [comment]
@jabo38 in latest 0.13.8 version is still not centered? On Linux looks fine.

**Comment by cryptoBeliever** [comment]
@NikolaiB please check if possible.

**Comment by NikolaiB** [comment]
@cryptoBeliever in latest 0.13.8 version this button is centered.

**Comment by jabo38** [comment]
fixed. closing
