### ISSUE TITLE
Warning before deleting an account isn't strong enough. 

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#932]
First, none of my apps so readily have delete buttons so apparent and highlighted in a different color. Usually to get to a delete button a person has to go through multiple menus. So I think it is a flaw to give such prime real estate on an app to a delete button. The other day I was using an app and tried to delete an account and it took me a loooong time to get to it. Deleting accounts are something that is rarely done. I'm not sure why it is put on the same area and given even highlighted focus above things like copying an address which in theory is done a lot. 

Anyway, when a person goes to delete an account, the warning isn't so clear. 

![image](https://user-images.githubusercontent.com/10395907/104977761-aa4d5400-59d6-11eb-880c-bb73782bc269.png)

It says "Are you sure you want to delete said account? You may want to have a back up before you proceed." 

That is kind of passive.  

It should say something like, "Deleting an account is not recommended without backing up your account. Loss of funds may occur. Are you sure you would like to delete said account?" 

Then a check box they have to click "Yes, I would like to delete this account." And then they can click delete.

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
![image](https://user-images.githubusercontent.com/17684281/106502317-84d74480-64c4-11eb-8a90-3f9044d90b3b.png)
