### ISSUE TITLE
Remove the Trezor button

### ISSUE THREAD

**Issue by jabo38** [nemgrouplimited/symbol-desktop-wallet#933]
![image](https://user-images.githubusercontent.com/10395907/104979566-fa2e1a00-59da-11eb-848d-83a181840d79.png)

It is pretty clear we won't have Trezor anytime soon and definitely not before launch. That button should be removed then. Otherwise we are just fake news :-) and will confuse a lot of users as they try to connect a Trezor and nothing happens.

**Comment by cryptoBeliever** [comment]
Fixed.
