### ISSUE TITLE
No address check under "add a cosignatory"

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#941]
if I enter an invalid address under "Add a cosignatory", it will be accepted without further checking and the transaction will be confirmed. e.g. "TYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"  ... or similar 
(0.13.8 - linux)

![invalidaddress2](https://user-images.githubusercontent.com/46584115/105162258-a7f01480-5b12-11eb-9f38-57bc10104101.png)

----

![invalidaddress5](https://user-images.githubusercontent.com/46584115/105162288-b1797c80-5b12-11eb-9fdb-538d085d981a.png)

----

" http://explorer.testnet.symboldev.network/blocks/34590 "

**Comment by cryptoBeliever** [comment]
@OlegMakarenko after this change I'm unable to use as a cosigner account without transactions (unknown to a network).
Why we need to call API? TYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY is valid address?

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever my bad, yes we can cosign an aggregate with 0 balance

**Comment by cryptoBeliever** [comment]
@OlegMakarenko no problem @rg911 fixed it.
