### ISSUE TITLE
Cannot sign multisig Tx (Version: 0.13.8 (ALL))

### ISSUE THREAD

**Issue by GodTanu** [nemgrouplimited/symbol-desktop-wallet#942]
Version: 0.13.8 (ALL)

Cannot sign multisig Tx.

The screen  is not displayed multisig's sign address to sign.

But I can see the signature screen on the recive address.
The address in this image is not a multisig's sign  address.
This is recive address.

![image](https://user-images.githubusercontent.com/20492223/105195668-33eb5600-5b7e-11eb-9cdd-be76e43648bd.png)

![image](https://user-images.githubusercontent.com/20492223/105195217-c5a69380-5b7d-11eb-819f-2f7f3d22bc66.png)

**Comment by GodTanu** [comment]
https://github.com/nemtech/catapult-rest/issues/278

Is this relevant?

**Comment by rg911** [comment]
> [nemtech/catapult-rest#278](https://github.com/nemtech/catapult-rest/issues/278)
> 
> Is this relevant?

It is related. We are testing on rest at the moment

**Comment by cryptoBeliever** [comment]
@GodTanu it's a notification problem. The recipient should not receive notification and should not be able to accept it by password and sign. But if the recipient puts a password and accepts of course nothing happens. So it's more like a presentation issue - still important.

But multi-signature transaction signing works. Please check the video:
https://share.getcloudapp.com/YEuXqBqp

**Comment by GodTanu** [comment]
@rg911 
If the relevant problem(nemtech/catapult-rest#278) is cured, will the current problem not occur?

**Comment by cryptoBeliever** [comment]
Currently:
- recipient doesn't have a possibility to put a password (no password input visible)
- cosigners now see notification without the need to switch to multisig account

Live build: http://desktop-build.symboldev.com/
