### ISSUE TITLE
Application can be used without accepting terms and conditions

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#946]
Currently the modal dialog which prompts to accept the terms and conditions can be closed without accepting by using the cross on the top right corner or by clicking on the grayed out background. It is also possible, after clicking on the terms and conditions link, to navigate to all pages except Home. The terms and conditions should probably also be shown in a modal dialog.

**Comment by cryptoBeliever** [comment]
Fixed.

**Comment by cryptoBeliever** [comment]
Still I'm able to use wallet without accepted terms.
1. Click terms details
2. Go to transaction view.
Pop-up shows again only if I click home.

Maybe it should be enforced on profile creation/importing?

**Comment by cryptoBeliever** [comment]
Current solution prevents creating profile without accepting conditions. Not sure if those are final version and if not should be available "outside" wallet.
