### ISSUE TITLE
Warning about backup required when users add an account from private key

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#948]
Right now users can add a custom private key inside of their hd (hierarchical deterministic) wallet via Accounts -> Add an account. This will add a custom symbol account to their wallet (not derived from seed account). Therefore the mnemonic will not be enough to restore that custom symbol account.

Now, it is true that the backup feature (Accounts -> Back up Profile) does include that custom symbol accounts private key, but users would have to understand that independently and make a new backup. Many won't and lost funds will be the result.

-> So we need a serious warning dialog when a user is trying to add an account from a private key.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko 
Warning added but I'm able click 'x' or click outside warning window and result will be same as "Understood"


![image](https://user-images.githubusercontent.com/17684281/106503524-09769280-64c6-11eb-9b09-eb4c042ed946.png)

**Comment by cryptoBeliever** [comment]
Changing to P3 because warning is present. We need only fix that it's accepted only using "Understood"

**Comment by cryptoBeliever** [comment]
Fixed.
