### ISSUE TITLE
'Seed Account 1' remains in My accounts and upper menu after changing it with positive balance

### ISSUE THREAD

**Issue by Eugenity** [nemgrouplimited/symbol-desktop-wallet#949]
**Steps to reproduce:**

1. Create a profile from scratch
2. Use the faucet link and claim default amount of xym (not providing the sum)
3. Go to Accounts/My accounts
4. Change the Name of the 'Seed Account 1'

**Actual result:** There is a new entry with the name specified being created in My accounts, 'Seed Account 1' also remains there inactive (a user is able to select it via upper menu)
**Expected result:** Only newly created account name remains in My accounts and upper menu

[Screenshot](https://share.getcloudapp.com/kpuNX2Xz)

**Comment by cryptoBeliever** [comment]
@Eugenity what version of wallet are you using? I'm unable to reproduce on 0.13.8

**Comment by Eugenity** [comment]
@cryptoBeliever The issue is still reproducible in the latests version.

**Comment by Eugenity** [comment]
Moreover the issue has a **side effect:**

**A user is unable to add more than one seed account to the profile with 'Seed Account 1' bug.**

the error message "This private key already exists. The account name is Gene4child1" is displayed when trying to add it.

**Comment by Eugenity** [comment]
[Screenshot](https://share.getcloudapp.com/jkueqo54)

**Comment by cryptoBeliever** [comment]
@Eugenity please try provide reproduce steps. I had also such a situation but no ability to reproduce it with specific reproduction steps.

**Comment by OlegMakarenko** [comment]
@cryptoBeliever I can reproduce it following the steps on the description

> Create a profile from scratch
> Use the faucet link and claim default amount of xym (not providing the sum)
> Go to Accounts/My accounts
> Change the Name of the 'Seed Account 1'

**Comment by cryptoBeliever** [comment]
@Eugenity please confirm that it's fixed in http://desktop-build.symboldev.com/ :+1:

**Comment by Eugenity** [comment]
Verified
