### ISSUE TITLE
Japanese characters are garbled in metadata value

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#962]
Japanese characters are garbled in Namespace's metadata value.

Here're steps to reproduce:

1. Select  Namespaces tab and select Add metadata
![image](https://user-images.githubusercontent.com/28587337/105623387-b1ec7d00-5e5c-11eb-8e32-248e471c136e.png)

2. Input Japanese text in Namespace metadata dialog and Send transaction
![image](https://user-images.githubusercontent.com/28587337/105623532-d9901500-5e5d-11eb-9abf-07343d5579c1.png)

3. Confirm that Japanese text is ok
![image](https://user-images.githubusercontent.com/28587337/105623570-165c0c00-5e5e-11eb-9881-e3099f43541e.png)

4. View metadata
![image](https://user-images.githubusercontent.com/28587337/105623607-64710f80-5e5e-11eb-87ef-24c6289be7dd.png)

5. Confirm that Japanese text is NOT ok.
![image](https://user-images.githubusercontent.com/28587337/105623638-984c3500-5e5e-11eb-98ed-1d206b4ec85d.png)

Could you check it, please?

Thanks!

**Comment by cryptoBeliever** [comment]
I think it might be related to https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/880

**Comment by cryptoBeliever** [comment]
Tried with random text "新 あたら しい 記事 きじ を 書"
Works well:

![image](https://user-images.githubusercontent.com/17684281/106659990-c12ba300-659f-11eb-8fa1-e0d43a23080c.png)

You can verify before release here: http://desktop-build.symboldev.com/
