### ISSUE TITLE
Information about Harvesting status not clear engough

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#963]
v0.13.8 linux

When users activate harvesting, the information about the current status is not clear enough.
It is not easy for the ordinary user to see where there may be problems. You have the short pop-ups that are displayed at the top right, but these may not be meaningful enough for ordinary users. In addition, the time in which the **pop-ups are displayed is relatively short, which is particularly disadvantageous in the case of error messages**.
I think it would make sense to display clear instructions here that are also permanently visible until the error is corrected.

e.g .: 
 " Insufficient balance, the account needs to hold at least 10000 XYMs to start delegated harvesting." 
              Is displayed briefly when the credit is below 10000 XYM
              This should also be displayed if the account has exactly 10,000 XYM at the time of activation, i.e. does not have    
              enough balance after transaction fees are deducted. Instead you get the message " ACTIVATION IN PROGRESS ". 
etc.

In addition, it is not always possible to deactivate harvesting, although you have sent an unlink transaction and the harvesting status is also set to inactive. Instead, when you activate harvesting again, only the swap option is displayed.

See also :

-  #680
-  #938

**Comment by garm01** [comment]
PS: If I press the "Activate" button(deleg.Harvesting)  and see "Activating", but then switch e.g. from "Harvesting" to "Accounts" and back, the "Activate" button is highlighted purple again, as if no action had taken place.

**Comment by GodTanu** [comment]
Unable to press the enable character after Link is completed.
So PersistentDelegationRequestTransaction is not issued.

Is this a known bug?
Is it possible to do delegated harvesting from the wallet at this time?

Is there a workaround?

**Comment by cryptoBeliever** [comment]
@GodTanu 
Is this for specific node/account?
If you are using web version could you check if you don't have JS error in Chrome console?

**Comment by cryptoBeliever** [comment]
Removing P2 because this is enhancement. I assume that @GodTanu you are unable to reproduce bug in 0.14.0
