### ISSUE TITLE
Invalid Delegated Harvesting Node Url List

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#964]
Invalid delegated harvesting nodes are available in the desktop wallet.

![image](https://user-images.githubusercontent.com/28587337/105646241-36cdaa00-5ee2-11eb-90a5-cfbcbffecdf2.png)

The following nodes are NOT activated harvesting nodes.
sym-test-07.opening-line.jp
sym-test-08.opening-line.jp
sym-test-09.opening-line.jp
sym-test-12.opening-line.jp

Could you let me know what the conditions are needed for making the list?

Thanks.

**Comment by cryptoBeliever** [comment]
http://desktop-build.symboldev.com/ - please check here
On list are visible all peers. If peer is not dual then you need put manually public key (because wallet can't call API).

**Comment by ryo-opening-line** [comment]
@cryptoBeliever thanks for your kind feedback.

i checked http://desktop-build.symboldev.com/. but seems something wrong.
i have not-activated harvesting nodes on list yet.

here's the result:

![image](https://user-images.githubusercontent.com/28587337/106683406-c6bcd380-6607-11eb-93e8-0502b32ae658.png)

you can see the following not-activated harvesting nodes listed:

https://sym-test-08.opening-line.jp:3001/node/unlockedaccount
https://sym-test-09.opening-line.jp:3001/node/unlockedaccount
https://sym-test-10.opening-line.jp:3001/node/unlockedaccount

but activated nodes are not listed as following:
https://sym-test-01.opening-line.jp:3001/node/unlockedaccount

thanks!

**Comment by cryptoBeliever** [comment]
@ryo-opening-line what you mean by not-activated harvesting nodes? 
Those nodes are visible because you are able to start harvesting on it.

**Comment by cryptoBeliever** [comment]
Nodes with disabled harvesting returning 503 when using endpoint /node/unlockedaccount (It was fixed in https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1021)
Those above looks correct to me (have enabled harvesting possibility)

**Comment by ryo-opening-line** [comment]
@cryptoBeliever sorry! I could be wrong....
Will sort it out and reopen it if needed.
closing this issue.
