### ISSUE TITLE
Delegated Harvesting Node Url Selection Problem

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#965]
I found the issue related to selecting a delegated harvesting node in the desktop wallet as follows:

1. Select a node from list
![image](https://user-images.githubusercontent.com/28587337/105664887-21c03d80-5f19-11eb-93bc-0baaa16e1711.png)

2. Push Start and cancel the Sign transaction(s) dialog
![image](https://user-images.githubusercontent.com/28587337/105665038-6f3caa80-5f19-11eb-90ef-67230c855e73.png)

3. Type another node name 
![image](https://user-images.githubusercontent.com/28587337/105665088-8da2a600-5f19-11eb-815a-ac948a1100a0.png)

4. Start and confirm the Sign transaction(s) dialog
![image](https://user-images.githubusercontent.com/28587337/105665146-b4f97300-5f19-11eb-88ed-1a8659e22134.png)

You can see that the information of the previously selected node is still there.

Could you check it, please?

Thanks!

**Comment by cryptoBeliever** [comment]
@bassemmagdy could you check?

**Comment by cryptoBeliever** [comment]
Harvesting was reworked (still in tests). This bug was fixed (you can check in live build http://desktop-build.symboldev.com/)
