### ISSUE TITLE
No error message when swapping the harvesting node.

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#966]
Select the node that is no longer in the list, but to which another wallet account is still connected.
An empty window for entering the password is displayed.
No further error message. No reaction when confirming the password.

![swap](https://user-images.githubusercontent.com/46584115/105717439-6c918380-5f20-11eb-8861-7eae355a1696.png)

**Comment by cryptoBeliever** [comment]
@garm01 are you able to reproduce on 0.14.0?

**Comment by garm01** [comment]
Not reproducible under v0.14.0 .
