### ISSUE TITLE
Hints are not readable

### ISSUE THREAD

**Issue by garm01** [nemgrouplimited/symbol-desktop-wallet#968]
1) Enter address
2) If the fee is changed below the recommended amount, the hints overlap.
(PS: To set the recommended fee to 0 fee, two attempts are needed. I am not sure if this is intentional. )

---

![hint2](https://user-images.githubusercontent.com/46584115/105767395-4a692700-5f5b-11eb-9a9e-520ab48a4009.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko what about "(PS: To set the recommended fee to 0 fee, two attempts are needed. I am not sure if this is intentional. )"? Is this intentional?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever thanks. [Fixed](https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/984)

**Comment by cryptoBeliever** [comment]
Fixed.
