### ISSUE TITLE
Node selector doesn't work

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#970]
![image](https://user-images.githubusercontent.com/33131259/106003501-ed848280-60ba-11eb-8848-d003c3b9b2cc.png)

**Comment by bassemmagdy** [comment]
This is not supposed to be working for switching between your nodes. You should be able to switch them using left bottom corner menu.

**Comment by OlegMakarenko** [comment]
Got it. What is a purpose of this list?

**Comment by myxmaster** [comment]
Hm, I think this is really confusing and I think it should be possible to switch nodes at this point.

Most of the time people will add a node to use it. So it should be selectable here. Maybe even autoselect it after adding.

**Comment by garm01** [comment]
please have a look #657

**Comment by OlegMakarenko** [comment]
close this issue as duplicate of #657
