### ISSUE TITLE
Address with a hyphen when creating a simple transaction in Symbol desktop wallet 

### ISSUE THREAD

**Issue by moe8ius** [nemgrouplimited/symbol-desktop-wallet#971]
When I creating a simple transaction in Symbol desktop wallet, the address with a hyphen does not allow saving it.

![scr-27jan2021](https://user-images.githubusercontent.com/78087691/106005014-d8acec80-60c4-11eb-9721-7453dc042b9d.jpg)

Win7, Google Chrome, ver.0.13.8

**Comment by cryptoBeliever** [comment]
Fixed (you can check in live build http://desktop-build.symboldev.com/)
