### ISSUE TITLE
Modal views. Too many scrollbars

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#972]
![image](https://user-images.githubusercontent.com/33131259/106008835-633f1d00-60c0-11eb-8aab-811d9e363561.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I'm marking as P3 but if you have any time please fix it.

**Comment by cryptoBeliever** [comment]
@OlegMakarenko as I can see it's fixed. Thank you
