### ISSUE TITLE
Review and fix translations

### ISSUE THREAD

**Issue by OlegMakarenko** [nemgrouplimited/symbol-desktop-wallet#975]
![image](https://user-images.githubusercontent.com/33131259/106019504-67246c80-60cb-11eb-9506-7b5455caf973.png)

**Comment by cryptoBeliever** [comment]
@OlegMakarenko isn't this related with https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/662?

**Comment by cryptoBeliever** [comment]
@OlegMakarenko is this issue about all translations?

**Comment by OlegMakarenko** [comment]
@cryptoBeliever yes, we need to review and replace all hardcoded text strings with translation function within the wallet

**Comment by cryptoBeliever** [comment]
@OlegMakarenko I assume there was only this one issue with expire then and all others was checked too. Closing.
