### ISSUE TITLE
Notification popups can be missed too easily

### ISSUE THREAD

**Issue by myxmaster** [nemgrouplimited/symbol-desktop-wallet#976]
There are some issues with the notifications that are displayed in the top right corner:
- The timeout is too short. At least for errors there should either be no timeout or you should be able to look it up in some place.
- New notifications replace the previously shown notification. So some notifications might be displayed for a very short time so that you are not able to read it.

I suggest using a library like this:
https://maronato.github.io/vue-toastification/

**Comment by cryptoBeliever** [comment]
Fixed.
