### ISSUE TITLE
Mosaics Fee dropdown list is not fully visible

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#993]
Desktop v0.13.8

WTR:

1. Go to Mosaics page
2. Click Add metadata button
3. Select Fee

Result: you can see that dropdown list is not fully visible
![image](https://user-images.githubusercontent.com/11311924/106252822-e4252280-6240-11eb-83c3-82515ab09a81.png)

**Comment by bassemmagdy** [comment]
fixed on latest integration
