### ISSUE TITLE
Overlapping text message in transfer tab

### ISSUE THREAD

**Issue by ryo-opening-line** [nemgrouplimited/symbol-desktop-wallet#997]
When you select No fee/Slowest in transfer tab, the following messages is overlapping.
- Please note that the minimal fee multiplier for the currently selected node is 100
- Send Transaction with a less than recommended fee might not get accepted and eventually expire.

![image](https://user-images.githubusercontent.com/28587337/106381081-ccdd6500-63f9-11eb-8623-757c103267ef.png)

Could you check it, please?

**Comment by cryptoBeliever** [comment]
It's already fixed (https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/968)
You can check in live build http://desktop-build.symboldev.com/
