### ISSUE TITLE
cannot send any transactions(exe version)

### ISSUE THREAD

**Issue by trestoJP** [nemgrouplimited/symbol-desktop-wallet#999]
symbol-desktop-wallet-win-0.13.8.exe
If I use this, all transactions(mosaic,namespace,multisig,harvesting..all) will time out and cannot be sent.

symbol-desktop-wallet_0.13.8.all.zip
This one works. However, I have not confirmed that all of them work.

**Comment by cryptoBeliever** [comment]
@trestoJP is this on all nodes or specific one?

@surekabpm please verify.

**Comment by trestoJP** [comment]
I haven't tried it with all nodes, but I was able to send it when I switched other nodes. 
It seem still unstable.

**Comment by rg911** [comment]
@trestoJP  still have the problem now? Stress testing was on testnet last week. The transaction announcement was slow and the fee multiplier was hiked up. btw have you tried selecting faster fees

**Comment by cryptoBeliever** [comment]
@trestoJP could you verify if you are still able to reproduce?

**Comment by cryptoBeliever** [comment]
I was unable to reproduce on the latest version. @trestoJP if you still have this issue please let me know. I will reopen.
